export interface DemoTalent {
  slug: string
  name: string
  tagline: string
  genre: string
  tier: 'Marquee' | 'Core' | 'Rising'
  following: string
  networks: string[]
  categories: string[]
  imageUrl: string
}

export const demoRoster: DemoTalent[] = [
  {
    slug: 'talent-001',
    name: 'Sofia Valentina',
    tagline: 'Luxury lifestyle personality and fashion curator.',
    genre: 'Fashion, Lifestyle, Beauty',
    tier: 'Marquee',
    following: '2.1M+',
    networks: ['Bravo'],
    categories: ['Fashion', 'Lifestyle'],
    imageUrl: '',
  },
  {
    slug: 'talent-002',
    name: 'Darius Cole',
    tagline: 'Fashion forward TV personality and cultural tastemaker.',
    genre: 'Fashion, Drama, Entertainment',
    tier: 'Marquee',
    following: '1.4M+',
    networks: ['MTV', 'E!'],
    categories: ['Fashion', 'Entertainment'],
    imageUrl: '',
  },
  {
    slug: 'talent-003',
    name: 'Amara Ndiaye',
    tagline: 'Beauty entrepreneur and skincare authority.',
    genre: 'Beauty, Skincare, Wellness',
    tier: 'Marquee',
    following: '1.5M+',
    networks: ['OWN', 'Hallmark'],
    categories: ['Beauty', 'Skincare'],
    imageUrl: '',
  },
  {
    slug: 'talent-004',
    name: 'Kai Mitchell',
    tagline: 'Fitness coach and wellness advocate.',
    genre: 'Fitness, Wellness, Lifestyle',
    tier: 'Marquee',
    following: '1.8M+',
    networks: ['NBC', 'USA Network'],
    categories: ['Fitness', 'Wellness'],
    imageUrl: '',
  },
  {
    slug: 'talent-005',
    name: 'Mei Lin Zhang',
    tagline: 'Style icon and beauty content creator.',
    genre: 'Fashion, Beauty, Lifestyle',
    tier: 'Marquee',
    following: '2.3M+',
    networks: ['NBC', 'E!'],
    categories: ['Fashion', 'Beauty'],
    imageUrl: '',
  },
  {
    slug: 'talent-006',
    name: 'Jordan Reed',
    tagline: 'Comedy personality and entertainment host.',
    genre: 'Comedy, Entertainment, Hosting',
    tier: 'Marquee',
    following: '920K+',
    networks: ['MTV', 'CBS'],
    categories: ['Comedy', 'Entertainment'],
    imageUrl: '',
  },
  {
    slug: 'talent-007',
    name: 'Chef Adeline',
    tagline: 'Celebrity chef and culinary content creator.',
    genre: 'Food, Lifestyle, Entertaining',
    tier: 'Core',
    following: '2.7M+',
    networks: ['Food Network', 'Bravo'],
    categories: ['Food', 'Lifestyle'],
    imageUrl: '',
  },
  {
    slug: 'talent-008',
    name: 'Nina Williams',
    tagline: 'Parenting expert and family lifestyle creator.',
    genre: 'Parenting, Family, Lifestyle',
    tier: 'Core',
    following: '780K+',
    networks: ['OWN'],
    categories: ['Parenting', 'Family'],
    imageUrl: '',
  },
  {
    slug: 'talent-009',
    name: 'Marcus King',
    tagline: 'Fitness entrepreneur and motivational speaker.',
    genre: 'Fitness, Entrepreneurship, Motivation',
    tier: 'Core',
    following: '1.6M+',
    networks: ['BET', 'VH1'],
    categories: ['Fitness', 'Entrepreneurship'],
    imageUrl: '',
  },
  {
    slug: 'talent-010',
    name: 'Tessa Blake',
    tagline: 'Travel personality and adventure content creator.',
    genre: 'Travel, Adventure, Lifestyle',
    tier: 'Core',
    following: '1.1M+',
    networks: ['Bravo', 'Netflix'],
    categories: ['Travel', 'Lifestyle'],
    imageUrl: '',
  },
  {
    slug: 'talent-011',
    name: 'Devon Park',
    tagline: 'Music producer and nightlife personality.',
    genre: 'Music, Nightlife, Entertainment',
    tier: 'Rising',
    following: '640K+',
    networks: ['MTV', 'VH1'],
    categories: ['Music', 'Entertainment'],
    imageUrl: '',
  },
  {
    slug: 'talent-012',
    name: 'Priya Sharma',
    tagline: 'Wellness coach and mindfulness advocate.',
    genre: 'Wellness, Yoga, Mindfulness',
    tier: 'Rising',
    following: '520K+',
    networks: ['NBC'],
    categories: ['Wellness', 'Yoga'],
    imageUrl: '',
  },
  {
    slug: 'talent-013',
    name: 'Luca Romano',
    tagline: 'Celebrity chef and Italian cuisine specialist.',
    genre: 'Food, Italian Cuisine, Hospitality',
    tier: 'Rising',
    following: '890K+',
    networks: ['Food Network'],
    categories: ['Food', 'Hospitality'],
    imageUrl: '',
  },
  {
    slug: 'talent-014',
    name: 'Jasmine Torres',
    tagline: 'Dance personality and choreography content creator.',
    genre: 'Dance, Entertainment, Fitness',
    tier: 'Rising',
    following: '1.3M+',
    networks: ['Fox', 'BET'],
    categories: ['Dance', 'Entertainment'],
    imageUrl: '',
  },
  {
    slug: 'talent-015',
    name: 'Brandon Hayes',
    tagline: 'Home renovation host and design expert.',
    genre: 'Home, Design, DIY',
    tier: 'Core',
    following: '750K+',
    networks: ['HGTV', 'NBC'],
    categories: ['Home', 'Design'],
    imageUrl: '',
  },
  {
    slug: 'talent-016',
    name: 'Camille Rose',
    tagline: 'Country lifestyle creator and southern hospitality host.',
    genre: 'Country, Lifestyle, Hospitality',
    tier: 'Rising',
    following: '430K+',
    networks: ['CMT', 'Hallmark'],
    categories: ['Country', 'Lifestyle'],
    imageUrl: '',
  },
]
