export interface ServiceTier {
  name: string
  price: string
  priceNote?: string
  timeline?: string
  talent?: string
  content?: string
  usageRights?: string
  bestFor?: string
  includes: string[]
  addOns?: { label: string; price: string }[]
  ctaLabel: string
  ctaHref: string
  featured?: boolean
}

export interface ServiceDefinition {
  number: string
  slug: string
  title: string
  shortTitle: string
  description: string
  priceRange: string
  tiers: ServiceTier[]
}

export const services: ServiceDefinition[] = [
  {
    number: "01",
    slug: "campaigns",
    title: "Campaign Packages",
    shortTitle: "Campaigns",
    description: "Multi-talent, multi-platform sponsored content campaigns.",
    priceRange: "$15K – $250K",
    tiers: [
      {
        name: "Spark",
        price: "$15K – $25K",
        priceNote: "per campaign",
        timeline: "3–4 weeks",
        talent: "1 verified creator",
        content: "3–5 pieces",
        usageRights: "30 days",
        bestFor: "DTC brands testing creator content for the first time",
        includes: [
          "1 television-verified creator matched to your brand",
          "3–5 pieces of original short-form content",
          "Cross-platform delivery — TikTok, Reels, Shorts",
          "30-day organic usage rights",
          "One round of revisions",
          "Final performance report",
        ],
        addOns: [
          { label: "Whitelisting / spark ad rights", price: "+$3,500" },
          { label: "Extended 60-day usage", price: "+$2,500" },
          { label: "Additional revision round", price: "+$1,500" },
        ],
        ctaLabel: "Book Spark",
        ctaHref: "/book?service=campaigns&tier=spark",
      },
      {
        name: "Ignite",
        price: "$50K – $75K",
        priceNote: "per campaign",
        timeline: "4–6 weeks",
        talent: "3 verified creators",
        content: "10–15 pieces",
        usageRights: "60 days",
        bestFor: "Mid-market brands running seasonal pushes or product launches",
        featured: true,
        includes: [
          "3 television-verified creators with audience overlap",
          "10–15 pieces of original short-form content",
          "Pre-campaign strategy session",
          "Cross-platform delivery — TikTok, Instagram, YouTube",
          "60-day organic usage rights",
          "Two rounds of revisions",
          "Weekly performance reports",
          "Final case study deliverable",
        ],
        addOns: [
          { label: "Whitelisting rights", price: "+$8,500" },
          { label: "Live commerce activation (1 event)", price: "+$12,000" },
          { label: "Vertical drama add-on (3 episodes)", price: "+$45,000" },
          { label: "Extended 90-day usage", price: "+$5,000" },
        ],
        ctaLabel: "Book Ignite",
        ctaHref: "/book?service=campaigns&tier=ignite",
      },
      {
        name: "Primetime",
        price: "$100K – $250K",
        priceNote: "per campaign",
        timeline: "6–8 weeks",
        talent: "5–8 verified creators",
        content: "25–40 pieces",
        usageRights: "90 days",
        bestFor: "Fortune 500, major CPG, entertainment studios",
        includes: [
          "5–8 television-verified creators (mixed tier strategy)",
          "25–40 pieces of premium content across all platforms",
          "Pre-campaign strategy + audience analysis + brand alignment",
          "Whitelisted ad content rights",
          "Dedicated campaign manager",
          "Weekly performance reports + mid-campaign optimization",
          "90-day organic + paid usage rights",
          "Optional event appearance (1 talent, 1 event)",
          "Final case study + ROI analysis",
        ],
        addOns: [
          { label: "Additional event appearances", price: "+$15,000 each" },
          { label: "Live commerce series (4 events)", price: "+$45,000" },
          { label: "Vertical drama series (8 episodes)", price: "+$200,000" },
          { label: "Extended 6-month usage", price: "+$25,000" },
        ],
        ctaLabel: "Book Primetime",
        ctaHref: "/book?service=campaigns&tier=primetime",
      },
    ],
  },
  {
    number: "02",
    slug: "production",
    title: "Vertical Drama Production",
    shortTitle: "Production",
    description: "Original branded series produced by Big Films Only, starring our roster.",
    priceRange: "$125K – $500K",
    tiers: [
      {
        name: "Limited Series Pilot",
        price: "$125,000",
        priceNote: "3 episodes",
        timeline: "8–10 weeks",
        bestFor: "Brands wanting to test the format before committing",
        includes: [
          "Single brand sponsor",
          "3 episodes (pilot + 2 follow-ups)",
          "Full product integration in storyline",
          "Cast from BookTalent roster",
          "Produced by Big Films Only",
          "Title card and end card rights",
        ],
        ctaLabel: "Discuss Pilot",
        ctaHref: "/book?service=production&tier=pilot",
      },
      {
        name: "Multi-Sponsor Series",
        price: "$150K – $200K",
        priceNote: "per brand, 2–3 sponsors",
        timeline: "12–16 weeks",
        bestFor: "Category-exclusive sponsorships with shared production cost",
        featured: true,
        includes: [
          "Category exclusive — no competing brands",
          "8–12 episodes, 2–5 minutes each",
          "Per-episode brand spotlight + integration",
          "Title card co-billing",
          "Content rights for your brand's episodes",
          "Cross-platform distribution — TikTok, Shorts, Reels",
        ],
        ctaLabel: "Discuss Co-Sponsorship",
        ctaHref: "/book?service=production&tier=multi",
      },
      {
        name: "Single Sponsor Series",
        price: "$250K – $500K",
        priceNote: "sole sponsor",
        timeline: "12–16 weeks",
        bestFor: "Full creative control and exclusive brand integration",
        includes: [
          "Sole brand sponsor of the entire series",
          "8–12 episodes, 2–5 minutes each",
          "Full product integration in storyline",
          "Exclusive title card, end card, and content rights",
          "Cast from BookTalent roster",
          "Produced by Big Films Only",
          "Cross-platform distribution",
        ],
        ctaLabel: "Discuss Full Sponsorship",
        ctaHref: "/book?service=production&tier=single",
      },
    ],
  },
  {
    number: "03",
    slug: "commerce",
    title: "Live Commerce",
    shortTitle: "Commerce",
    description: "Real-time shopping events on TikTok Shop, Amazon Live, and Instagram.",
    priceRange: "$12K – $150K",
    tiers: [
      {
        name: "Single Event",
        price: "$12,000",
        priceNote: "per event",
        talent: "1 verified creator",
        bestFor: "Testing live commerce with a single high-impact event",
        includes: [
          "1 BookTalent creator trained for live selling",
          "Pre-event product training and script development",
          "60–90 minute live shopping broadcast",
          "Platform: TikTok Shop, Amazon Live, or Instagram",
          "48-hour pre-event promotion across talent channels",
          "Post-event analytics and sales data",
        ],
        ctaLabel: "Book Single Event",
        ctaHref: "/book?service=commerce&tier=single",
      },
      {
        name: "Quarterly Series",
        price: "$45,000",
        priceNote: "4 events over 3 months",
        talent: "2–3 creators rotated",
        bestFor: "Building a consistent live commerce presence",
        featured: true,
        includes: [
          "4 quarterly live shopping events",
          "2–3 different creators rotated across events",
          "Cross-platform broadcasting",
          "Quarterly strategy review and optimization",
          "Comprehensive sales reporting",
          "Save $3,000 vs. booking individually",
        ],
        ctaLabel: "Book Quarterly",
        ctaHref: "/book?service=commerce&tier=quarterly",
      },
      {
        name: "Annual Program",
        price: "$150,000",
        priceNote: "12 events over 12 months",
        talent: "5+ creators rotated",
        bestFor: "Brands committed to live commerce as a revenue channel",
        includes: [
          "12 monthly live shopping events",
          "5+ creators across the program",
          "Dedicated commerce strategist",
          "Monthly optimization based on sales data",
          "Optional revenue share model for top performers",
          "Multi-platform optimization",
        ],
        ctaLabel: "Book Annual Program",
        ctaHref: "/book?service=commerce&tier=annual",
      },
    ],
  },
  {
    number: "04",
    slug: "ugc",
    title: "UGC Content Retainers",
    shortTitle: "UGC",
    description: "Monthly retainers for whitelisted ad content at scale.",
    priceRange: "$5K – $20K / month",
    tiers: [
      {
        name: "Starter",
        price: "$5,000",
        priceNote: "per month, 3-month minimum",
        content: "8 pieces per month",
        talent: "2 creators",
        usageRights: "30-day rolling",
        bestFor: "Brands starting their UGC content pipeline",
        includes: [
          "8 pieces of UGC content per month",
          "2 BookTalent creators",
          "30-day usage rights (rolling)",
          "Whitelisted ad spark code rights",
          "Monthly delivery via shared drive",
          "Basic performance reporting",
        ],
        ctaLabel: "Start Starter",
        ctaHref: "/book?service=ugc&tier=starter",
      },
      {
        name: "Growth",
        price: "$10,000",
        priceNote: "per month, 3-month minimum",
        content: "15 pieces per month",
        talent: "4 creators",
        usageRights: "60-day rolling",
        bestFor: "Scaling paid creative with testing built in",
        featured: true,
        includes: [
          "15 pieces of UGC content per month",
          "4 BookTalent creators for audience variety",
          "A/B testing variants for ad optimization",
          "60-day usage rights (rolling)",
          "Whitelisted ad spark code rights",
          "Bi-weekly performance reporting",
          "Quarterly strategy call",
        ],
        ctaLabel: "Start Growth",
        ctaHref: "/book?service=ugc&tier=growth",
      },
      {
        name: "Enterprise",
        price: "$20,000",
        priceNote: "per month, 6-month minimum",
        content: "30 pieces per month",
        talent: "6–8 creators",
        usageRights: "90-day rolling",
        bestFor: "Full-scale UGC programs with dedicated management",
        includes: [
          "30 pieces of UGC content per month",
          "6–8 BookTalent creators across categories",
          "Dedicated account manager",
          "Full A/B testing matrix",
          "90-day usage rights (rolling)",
          "Weekly performance reporting",
          "Quarterly strategy reviews",
          "Priority creator access",
        ],
        ctaLabel: "Start Enterprise",
        ctaHref: "/book?service=ugc&tier=enterprise",
      },
    ],
  },
  {
    number: "05",
    slug: "management",
    title: "Talent Management",
    shortTitle: "Management",
    description: "Three tiers of representation for verified reality TV creators.",
    priceRange: "$0 – $1,500 / month",
    tiers: [
      {
        name: "Rising",
        price: "$750",
        priceNote: "per month + 25% commission, 6-month min",
        bestFor: "Strong TV pedigree, 25K–100K following",
        includes: [
          "Talent manager (shared, by category)",
          "Profile setup and optimization",
          "Brand matching for entry-level deals",
          "Content coaching and strategy",
          "Legal contract review",
          "Quarterly performance review",
          "Pathway to Core promotion",
        ],
        ctaLabel: "Apply as Rising",
        ctaHref: "/book?service=management&tier=rising",
      },
      {
        name: "Core Roster",
        price: "$1,500",
        priceNote: "per month + 20% commission, 6-month min",
        bestFor: "Solid TV credits, 100K–500K following",
        featured: true,
        includes: [
          "Dedicated talent manager",
          "Profile optimization across all platforms",
          "Pitch deck creation",
          "Priority placement in campaign matching",
          "Content strategy and posting cadence",
          "Legal contract review",
          "Monthly performance review",
        ],
        ctaLabel: "Apply as Core",
        ctaHref: "/book?service=management&tier=core",
      },
      {
        name: "Marquee",
        price: "$0",
        priceNote: "20% commission only, 1-year commitment",
        bestFor: "Recognizable names, 500K+ following",
        includes: [
          "Dedicated talent manager",
          "Priority pitch placement on all incoming briefs",
          "Premium positioning on BookTalent roster",
          "Career strategy and content roadmap",
          "Legal contract review and negotiation",
          "Featured in marketing and case studies",
          "Access to enterprise brand partnerships",
        ],
        ctaLabel: "Apply as Marquee",
        ctaHref: "/book?service=management&tier=marquee",
      },
    ],
  },
  {
    number: "06",
    slug: "enterprise",
    title: "Enterprise Partnership",
    shortTitle: "Enterprise",
    description: "The annual bundle. Roster access, production, UGC, commerce, all in one.",
    priceRange: "$500,000 / year",
    tiers: [
      {
        name: "Annual Partnership",
        price: "$500,000",
        priceNote: "12 months — save $218K vs. standalone",
        bestFor: "Brands spending $1M+ annually on creator marketing",
        includes: [
          "Priority access to 10 creators for 12 months",
          "1 branded vertical drama series (8–12 episodes)",
          "30 pieces of UGC content per month for 12 months",
          "4 quarterly live shopping events with 3 talent each",
          "Dedicated account manager",
          "Quarterly strategy reviews and monthly reporting",
        ],
        ctaLabel: "Schedule Enterprise Call",
        ctaHref: "/book?service=enterprise",
      },
    ],
  },
]

export function getServiceBySlug(slug: string): ServiceDefinition | undefined {
  return services.find((s) => s.slug === slug)
}
