export interface TalentProfile {
  slug: string
  name: string
  tagline: string
  credits: { show: string; network: string; seasons: string; role: string }[]
  following: string
  engagement: string
  networks: string[]
  specialties: string[]
  category: string
  image: string
  talentId: string
  previousBrands: string[]
  social: {
    instagram?: string
    tiktok?: string
    youtube?: string
  }
  highlightClip?: string
}

export const talentRoster: TalentProfile[] = [
  // ── Fashion & Lifestyle ──
  {
    slug: "sofia-valentina",
    name: "Sofia Valentina",
    tagline: "Luxury lifestyle personality, fashion curator, brand storyteller.",
    credits: [
      { show: "The Real Housewives", network: "BRAVO", seasons: "4 Seasons", role: "Cast" },
    ],
    following: "2.1M",
    engagement: "4.6%",
    networks: ["BRAVO"],
    specialties: ["Fashion", "Lifestyle"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-001",
    previousBrands: ["Revolve", "Net-a-Porter", "Dyson"],
    social: { instagram: "@sofiavalentina", tiktok: "@sofiavalentina" },
  },
  {
    slug: "darius-cole",
    name: "Darius Cole",
    tagline: "Fashion forward TV personality, style commentator, cultural tastemaker.",
    credits: [
      { show: "Wild 'N Out", network: "MTV", seasons: "2 Seasons", role: "Cast" },
      { show: "The Arrangement", network: "E!", seasons: "1 Season", role: "Featured" },
    ],
    following: "1.4M",
    engagement: "5.1%",
    networks: ["MTV", "E!"],
    specialties: ["Fashion", "Drama"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-002",
    previousBrands: ["Hugo Boss", "Hennessy", "Cash App"],
    social: { instagram: "@dariuscole", tiktok: "@dariuscole" },
  },
  {
    slug: "priya-sharma",
    name: "Priya Sharma",
    tagline: "Global fashion personality, travel creator, editorial model.",
    credits: [
      { show: "Below Deck", network: "BRAVO", seasons: "1 Season", role: "Guest" },
      { show: "Access Hollywood", network: "NBC", seasons: "2 Seasons", role: "Correspondent" },
    ],
    following: "890K",
    engagement: "5.8%",
    networks: ["BRAVO", "NBC"],
    specialties: ["Fashion", "Travel"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-003",
    previousBrands: ["Sephora", "Away Luggage", "Glossier"],
    social: { instagram: "@priyasharma", tiktok: "@priyasharma" },
  },
  {
    slug: "luca-moretti",
    name: "Luca Moretti",
    tagline: "Lifestyle entrepreneur, reality TV veteran, luxury brand consultant.",
    credits: [
      { show: "Rich Kids of Instagram", network: "E!", seasons: "1 Season", role: "Cast" },
      { show: "Temptation Island", network: "USA Network", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.1M",
    engagement: "4.3%",
    networks: ["E!", "USA Network"],
    specialties: ["Lifestyle", "Fashion"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-004",
    previousBrands: ["Tag Heuer", "Tesla", "Kith"],
    social: { instagram: "@lucamoretti", tiktok: "@lucamoretti" },
  },

  // ── Fitness & Yoga ──
  {
    slug: "kai-mitchell",
    name: "Kai Mitchell",
    tagline: "Fitness personality, wellness advocate, motivational coach.",
    credits: [
      { show: "American Ninja Warrior", network: "NBC", seasons: "2 Seasons", role: "Contestant" },
      { show: "Temptation Island", network: "USA Network", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.8M",
    engagement: "5.2%",
    networks: ["NBC", "USA Network"],
    specialties: ["Fitness", "Wellness"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-005",
    previousBrands: ["Nike", "Gymshark", "WHOOP"],
    social: { instagram: "@kaimitchell", tiktok: "@kaimitchell", youtube: "@KaiMitchellFit" },
  },
  {
    slug: "zara-okafor",
    name: "Zara Okafor",
    tagline: "Yoga instructor, wellness creator, mindfulness speaker.",
    credits: [
      { show: "Super Soul Sunday", network: "OWN", seasons: "2 Seasons", role: "Guest" },
    ],
    following: "1.3M",
    engagement: "6.4%",
    networks: ["OWN"],
    specialties: ["Yoga", "Wellness"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-006",
    previousBrands: ["Lululemon", "Calm", "Alo Yoga"],
    social: { instagram: "@zaraokafor", tiktok: "@zaraokafor" },
  },
  {
    slug: "atlas-rivera",
    name: "Atlas Rivera",
    tagline: "Athlete turned content creator, fitness entrepreneur, brand builder.",
    credits: [
      { show: "American Ninja Warrior", network: "NBC", seasons: "3 Seasons", role: "Finalist" },
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
    ],
    following: "2.4M",
    engagement: "4.9%",
    networks: ["NBC", "CBS"],
    specialties: ["Fitness", "Lifestyle"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-007",
    previousBrands: ["Under Armour", "Huel", "GoPro"],
    social: { instagram: "@atlasrivera", tiktok: "@atlasrivera", youtube: "@AtlasRiveraFit" },
  },
  {
    slug: "jade-chen",
    name: "Jade Chen",
    tagline: "Fitness model, wellness content creator, personal trainer.",
    credits: [
      { show: "The Challenge", network: "MTV", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "960K",
    engagement: "5.7%",
    networks: ["MTV"],
    specialties: ["Fitness", "Beauty"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-008",
    previousBrands: ["Fabletics", "Vital Proteins", "Peloton"],
    social: { instagram: "@jadechen", tiktok: "@jadechenfitness" },
  },

  // ── Chefs & Food ──
  {
    slug: "elijah-brooks",
    name: "Elijah Brooks",
    tagline: "Food entertainer, culinary comedian, live commerce natural.",
    credits: [
      { show: "MasterChef", network: "Food Network", seasons: "2 Seasons", role: "Finalist" },
      { show: "The Great American Recipe", network: "NBC", seasons: "1 Season", role: "Contestant" },
    ],
    following: "1.6M",
    engagement: "5.9%",
    networks: ["Food Network", "NBC"],
    specialties: ["Food", "Comedy"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-010",
    previousBrands: ["McCormick", "DoorDash", "Blue Apron"],
    social: { instagram: "@elijahbrooks", tiktok: "@elijahbrookscooks" },
  },
  {
    slug: "carmen-reyes",
    name: "Carmen Reyes",
    tagline: "Culinary storyteller, travel food creator, recipe developer.",
    credits: [
      { show: "Beat Bobby Flay", network: "Food Network", seasons: "1 Season", role: "Guest" },
      { show: "The Kitchen", network: "Food Network", seasons: "1 Season", role: "Co-host" },
    ],
    following: "1.1M",
    engagement: "5.4%",
    networks: ["Food Network"],
    specialties: ["Food", "Travel"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1614283233556-f35b0c801ef1?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-011",
    previousBrands: ["Trader Joe's", "Le Creuset", "HelloFresh"],
    social: { instagram: "@carmenreyes", tiktok: "@carmenreyescooks" },
  },
  {
    slug: "james-park",
    name: "James Park",
    tagline: "Modern fusion chef, food content creator, restaurant consultant.",
    credits: [
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
      { show: "Chopped", network: "Food Network", seasons: "2 Seasons", role: "Contestant" },
    ],
    following: "870K",
    engagement: "5.6%",
    networks: ["CBS", "Food Network"],
    specialties: ["Food", "Lifestyle"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1583195764036-6dc248ac07d9?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-012",
    previousBrands: ["Blue Apron", "Sake One", "Vitamix"],
    social: { instagram: "@jamespark", tiktok: "@jamesparkcooks" },
  },

  // ── Beauty & Skincare ──
  {
    slug: "amara-ndiaye",
    name: "Amara Ndiaye",
    tagline: "Skincare expert, beauty creator, wellness advocate.",
    credits: [
      { show: "Love & Marriage: DC", network: "OWN", seasons: "1 Season", role: "Cast" },
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "1 Season", role: "Guest" },
    ],
    following: "1.5M",
    engagement: "5.7%",
    networks: ["OWN", "Hallmark"],
    specialties: ["Beauty", "Skincare"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-013",
    previousBrands: ["Fenty Beauty", "Tatcha", "Olay"],
    social: { instagram: "@amarandiaye", tiktok: "@amarandiaye" },
  },
  {
    slug: "lily-monroe",
    name: "Lily Monroe",
    tagline: "Beauty mogul, fashion personality, editorial model.",
    credits: [
      { show: "Rich Kids of Instagram", network: "E!", seasons: "2 Seasons", role: "Cast" },
      { show: "Below Deck", network: "BRAVO", seasons: "1 Season", role: "Guest" },
    ],
    following: "2.8M",
    engagement: "3.9%",
    networks: ["E!", "BRAVO"],
    specialties: ["Beauty", "Fashion"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-014",
    previousBrands: ["Charlotte Tilbury", "SKIMS", "Morphe"],
    social: { instagram: "@lilymonroe", tiktok: "@lilymonroe" },
  },
  {
    slug: "mia-tanaka",
    name: "Mia Tanaka",
    tagline: "Skincare specialist, wellness creator, clean beauty advocate.",
    credits: [
      { show: "The Challenge", network: "MTV", seasons: "1 Season", role: "Cast" },
      { show: "Super Soul Sunday", network: "OWN", seasons: "1 Season", role: "Guest" },
    ],
    following: "1.2M",
    engagement: "6.2%",
    networks: ["MTV", "OWN"],
    specialties: ["Skincare", "Wellness"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-015",
    previousBrands: ["Glow Recipe", "Drunk Elephant", "Calm"],
    social: { instagram: "@miatanaka", tiktok: "@miatanaka" },
  },
  {
    slug: "ava-laurent",
    name: "Ava Laurent",
    tagline: "Beauty content creator, natural skincare expert, lifestyle personality.",
    credits: [
      { show: "The Real Housewives", network: "BRAVO", seasons: "3 Seasons", role: "Friend Of" },
    ],
    following: "990K",
    engagement: "5.3%",
    networks: ["BRAVO"],
    specialties: ["Beauty", "Lifestyle"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-016",
    previousBrands: ["Glossier", "Herbivore", "Sephora"],
    social: { instagram: "@avalaurent", tiktok: "@avalaurent" },
  },

  // ── Comedy & Entertainment ──
  {
    slug: "jordan-reed",
    name: "Jordan Reed",
    tagline: "Stand up comedian, variety show veteran, brand entertainer.",
    credits: [
      { show: "Wild 'N Out", network: "MTV", seasons: "2 Seasons", role: "Cast" },
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
    ],
    following: "920K",
    engagement: "5.8%",
    networks: ["MTV", "CBS"],
    specialties: ["Comedy", "Entertainment"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-017",
    previousBrands: ["Beats by Dre", "Cash App", "Chipotle"],
    social: { instagram: "@jordanreed", tiktok: "@jordanreed" },
  },
  {
    slug: "naomi-blake",
    name: "Naomi Blake",
    tagline: "Comedy actress, entertainment personality, content powerhouse.",
    credits: [
      { show: "Access Hollywood", network: "NBC", seasons: "2 Seasons", role: "Correspondent" },
      { show: "Wild 'N Out", network: "MTV", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "1.7M",
    engagement: "4.8%",
    networks: ["NBC", "MTV"],
    specialties: ["Comedy", "Drama"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-018",
    previousBrands: ["Netflix", "BetterHelp", "Fashion Nova"],
    social: { instagram: "@naomiblake", tiktok: "@naomiblake", youtube: "@NaomiBlakeComedy" },
  },

  // ── Parenting & Family ──
  {
    slug: "nina-williams",
    name: "Nina Williams",
    tagline: "Family lifestyle creator, parenting advocate, TV personality.",
    credits: [
      { show: "Love & Marriage: Huntsville", network: "OWN", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "780K",
    engagement: "6.5%",
    networks: ["OWN"],
    specialties: ["Parenting", "Lifestyle"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-019",
    previousBrands: ["Target", "Pampers", "Honest Company"],
    social: { instagram: "@ninawilliams", tiktok: "@ninawilliams" },
  },
  {
    slug: "david-osei",
    name: "David Osei",
    tagline: "Dad content creator, family lifestyle personality, comedic storyteller.",
    credits: [
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "1 Season", role: "Guest" },
      { show: "Love & Marriage: DC", network: "OWN", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "650K",
    engagement: "7.1%",
    networks: ["Hallmark", "OWN"],
    specialties: ["Parenting", "Comedy"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-020",
    previousBrands: ["Disney+", "LEGO", "Huggies"],
    social: { instagram: "@davidosei", tiktok: "@davidosei" },
  },

  // ── Fashion & Lifestyle (expanded) ──
  {
    slug: "ines-delacroix",
    name: "Ines Delacroix",
    tagline: "Parisian chic personality, travel storyteller, luxury brand curator.",
    credits: [
      { show: "The Real Housewives", network: "BRAVO", seasons: "2 Seasons", role: "Cast" },
      { show: "Rich Kids of Instagram", network: "E!", seasons: "1 Season", role: "Featured" },
    ],
    following: "1.9M",
    engagement: "4.4%",
    networks: ["BRAVO", "E!"],
    specialties: ["Fashion", "Travel"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-021",
    previousBrands: ["Chanel", "Louis Vuitton", "Farfetch"],
    social: { instagram: "@inesdelacroix", tiktok: "@inesdelacroix" },
  },
  {
    slug: "tatiana-obi",
    name: "Tatiana Obi",
    tagline: "Fashion editorial star, beauty authority, global brand ambassador.",
    credits: [
      { show: "Rich Kids of Instagram", network: "E!", seasons: "2 Seasons", role: "Cast" },
      { show: "Super Soul Sunday", network: "OWN", seasons: "1 Season", role: "Guest" },
    ],
    following: "2.5M",
    engagement: "4.1%",
    networks: ["E!", "OWN"],
    specialties: ["Fashion", "Beauty"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-023",
    previousBrands: ["Dior", "MAC Cosmetics", "Zara"],
    social: { instagram: "@tatianaobi", tiktok: "@tatianaobi", youtube: "@TatianaObiStyle" },
  },
  {
    slug: "erik-lindqvist",
    name: "Erik Lindqvist",
    tagline: "Scandinavian lifestyle creator, travel personality, outdoor adventurer.",
    credits: [
      { show: "Below Deck", network: "BRAVO", seasons: "1 Season", role: "Guest" },
      { show: "Access Hollywood", network: "NBC", seasons: "1 Season", role: "Correspondent" },
    ],
    following: "870K",
    engagement: "5.5%",
    networks: ["BRAVO", "NBC"],
    specialties: ["Lifestyle", "Travel"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-024",
    previousBrands: ["Fjallraven", "Volvo", "Away Luggage"],
    social: { instagram: "@eriklindqvist", tiktok: "@eriklindqvist" },
  },

  // ── Fitness & Yoga (expanded) ──
  {
    slug: "maya-johansson",
    name: "Maya Johansson",
    tagline: "Yoga educator, wellness thought leader, mindful living advocate.",
    credits: [
      { show: "American Ninja Warrior", network: "NBC", seasons: "1 Season", role: "Contestant" },
      { show: "Access Hollywood", network: "NBC", seasons: "2 Seasons", role: "Guest" },
    ],
    following: "2.2M",
    engagement: "5.3%",
    networks: ["NBC"],
    specialties: ["Yoga", "Wellness"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-025",
    previousBrands: ["Alo Yoga", "Headspace", "Manduka"],
    social: { instagram: "@mayajohansson", tiktok: "@mayajohansson", youtube: "@MayaJohanssonYoga" },
  },
  {
    slug: "kofi-asante",
    name: "Kofi Asante",
    tagline: "Fitness coach, lifestyle motivator, athletic brand partner.",
    credits: [
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
      { show: "Temptation Island", network: "USA Network", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.6M",
    engagement: "5.0%",
    networks: ["CBS", "USA Network"],
    specialties: ["Fitness", "Lifestyle"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-026",
    previousBrands: ["Adidas", "MyProtein", "Fitbit"],
    social: { instagram: "@kofiasante", tiktok: "@kofiasante" },
  },
  {
    slug: "valentina-cruz",
    name: "Valentina Cruz",
    tagline: "Fitness personality, beauty content creator, body positivity champion.",
    credits: [
      { show: "The Challenge", network: "MTV", seasons: "2 Seasons", role: "Cast" },
      { show: "Super Soul Sunday", network: "OWN", seasons: "1 Season", role: "Guest" },
    ],
    following: "1.1M",
    engagement: "5.6%",
    networks: ["MTV", "OWN"],
    specialties: ["Fitness", "Beauty"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-027",
    previousBrands: ["Fabletics", "Neutrogena", "Bala"],
    social: { instagram: "@valentinacruz", tiktok: "@valentinacruz" },
  },
  {
    slug: "trent-nakamura",
    name: "Trent Nakamura",
    tagline: "Athletic comedian, fitness entertainer, viral content machine.",
    credits: [
      { show: "American Ninja Warrior", network: "NBC", seasons: "2 Seasons", role: "Contestant" },
      { show: "Survivor", network: "CBS", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "980K",
    engagement: "6.0%",
    networks: ["NBC", "CBS"],
    specialties: ["Fitness", "Comedy"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1557862921-37829c790f19?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-028",
    previousBrands: ["Reebok", "C4 Energy", "GoPro"],
    social: { instagram: "@trentnakamura", tiktok: "@trentnakamura", youtube: "@TrentNakamuraFit" },
  },

  // ── Chefs & Food (expanded) ──
  {
    slug: "chef-adeline",
    name: "Chef Adeline",
    tagline: "Celebrity pastry chef, culinary storyteller, lifestyle personality.",
    credits: [
      { show: "Chopped", network: "Food Network", seasons: "2 Seasons", role: "Champion" },
      { show: "The Real Housewives", network: "BRAVO", seasons: "2 Seasons", role: "Guest" },
    ],
    following: "2.7M",
    engagement: "5.8%",
    networks: ["Food Network", "BRAVO"],
    specialties: ["Food", "Lifestyle"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1558898479-33c0057a5d12?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-029",
    previousBrands: ["KitchenAid", "Godiva", "Williams Sonoma"],
    social: { instagram: "@chefadeline", tiktok: "@chefadeline", youtube: "@ChefAdelineOfficial" },
  },
  {
    slug: "rashid-al-farsi",
    name: "Rashid Al-Farsi",
    tagline: "Global cuisine creator, food travel storyteller, spice authority.",
    credits: [
      { show: "MasterChef", network: "Food Network", seasons: "2 Seasons", role: "Finalist" },
      { show: "The Great American Recipe", network: "Food Network", seasons: "1 Season", role: "Contestant" },
    ],
    following: "1.4M",
    engagement: "5.3%",
    networks: ["Food Network"],
    specialties: ["Food", "Travel"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1605462863863-10d9e47e15ee?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-030",
    previousBrands: ["McCormick", "Airbnb", "Sur La Table"],
    social: { instagram: "@rashidalfarsi", tiktok: "@rashidalfarsi" },
  },
  {
    slug: "yuki-tanaka",
    name: "Yuki Tanaka",
    tagline: "Culinary comedian, fusion food creator, viral recipe developer.",
    credits: [
      { show: "Beat Bobby Flay", network: "Food Network", seasons: "1 Season", role: "Winner" },
      { show: "Access Hollywood", network: "NBC", seasons: "1 Season", role: "Guest" },
    ],
    following: "920K",
    engagement: "6.3%",
    networks: ["Food Network", "NBC"],
    specialties: ["Food", "Comedy"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1593104547489-5cfb3839a3b5?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-031",
    previousBrands: ["Trader Joe's", "Instant Pot", "DoorDash"],
    social: { instagram: "@yukitanaka", tiktok: "@yukitanakacooks" },
  },
  {
    slug: "elena-vasquez",
    name: "Elena Vasquez",
    tagline: "Farm to table advocate, food and beauty creator, recipe storyteller.",
    credits: [
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
      { show: "The Kitchen", network: "Food Network", seasons: "2 Seasons", role: "Co-host" },
    ],
    following: "1.8M",
    engagement: "5.1%",
    networks: ["CBS", "Food Network"],
    specialties: ["Food", "Beauty"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1499887142886-791eca5918cd?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-032",
    previousBrands: ["Whole Foods", "Le Creuset", "Glossier"],
    social: { instagram: "@elenavasquez", tiktok: "@elenavasquezcooks" },
  },

  // ── Beauty & Skincare (expanded) ──
  {
    slug: "zuri-kimani",
    name: "Zuri Kimani",
    tagline: "Skincare innovator, beauty mogul, wellness authority.",
    credits: [
      { show: "Love & Marriage: Huntsville", network: "OWN", seasons: "2 Seasons", role: "Cast" },
      { show: "Rich Kids of Instagram", network: "E!", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "3.1M",
    engagement: "4.2%",
    networks: ["OWN", "E!"],
    specialties: ["Beauty", "Skincare"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-033",
    previousBrands: ["Fenty Skin", "The Ordinary", "Ulta Beauty"],
    social: { instagram: "@zurikimani", tiktok: "@zurikimani", youtube: "@ZuriKimaniBeauty" },
  },
  {
    slug: "camille-dubois",
    name: "Camille Dubois",
    tagline: "Clean skincare advocate, wellness creator, natural beauty expert.",
    credits: [
      { show: "The Real Housewives", network: "BRAVO", seasons: "1 Season", role: "Friend Of" },
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "1 Season", role: "Guest" },
    ],
    following: "1.6M",
    engagement: "5.4%",
    networks: ["BRAVO", "Hallmark"],
    specialties: ["Skincare", "Wellness"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-034",
    previousBrands: ["Drunk Elephant", "Herbivore", "Sephora"],
    social: { instagram: "@camilledubois", tiktok: "@camilledubois" },
  },
  {
    slug: "hana-park",
    name: "Hana Park",
    tagline: "K beauty specialist, fashion forward beauty creator, editorial model.",
    credits: [
      { show: "The Arrangement", network: "E!", seasons: "2 Seasons", role: "Cast" },
      { show: "The Challenge", network: "MTV", seasons: "1 Season", role: "Cast" },
    ],
    following: "2.0M",
    engagement: "4.7%",
    networks: ["E!", "MTV"],
    specialties: ["Beauty", "Fashion"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-035",
    previousBrands: ["Laneige", "Charlotte Tilbury", "Revolve"],
    social: { instagram: "@hanapark", tiktok: "@hanapark" },
  },
  {
    slug: "diego-santos",
    name: "Diego Santos",
    tagline: "Men's skincare authority, grooming expert, lifestyle content creator.",
    credits: [
      { show: "Below Deck", network: "BRAVO", seasons: "1 Season", role: "Guest" },
      { show: "Temptation Island", network: "USA Network", seasons: "1 Season", role: "Cast" },
    ],
    following: "750K",
    engagement: "5.9%",
    networks: ["BRAVO", "USA Network"],
    specialties: ["Skincare", "Lifestyle"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-036",
    previousBrands: ["Harry's", "CeraVe", "Dollar Shave Club"],
    social: { instagram: "@diegosantos", tiktok: "@diegosantos" },
  },

  // ── Comedy & Entertainment (expanded) ──
  {
    slug: "chris-okonkwo",
    name: "Chris Okonkwo",
    tagline: "Veteran comedian, dramatic actor, live event powerhouse.",
    credits: [
      { show: "Wild 'N Out", network: "MTV", seasons: "3 Seasons", role: "Cast" },
      { show: "Access Hollywood", network: "NBC", seasons: "1 Season", role: "Guest" },
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
    ],
    following: "2.9M",
    engagement: "4.5%",
    networks: ["MTV", "NBC", "CBS"],
    specialties: ["Comedy", "Drama"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-037",
    previousBrands: ["Netflix", "Pepsi", "State Farm"],
    social: { instagram: "@chrisokonkwo", tiktok: "@chrisokonkwo", youtube: "@ChrisOkonkwoComedy" },
  },
  {
    slug: "sasha-volkov",
    name: "Sasha Volkov",
    tagline: "Entertainment personality, comedic actress, pop culture commentator.",
    credits: [
      { show: "Wild 'N Out", network: "MTV", seasons: "2 Seasons", role: "Cast" },
      { show: "The Arrangement", network: "E!", seasons: "1 Season", role: "Featured" },
    ],
    following: "1.3M",
    engagement: "5.2%",
    networks: ["MTV", "E!"],
    specialties: ["Entertainment", "Comedy"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-038",
    previousBrands: ["Hulu", "BetterHelp", "Savage X Fenty"],
    social: { instagram: "@sashavolkov", tiktok: "@sashavolkov" },
  },

  // ── Parenting & Family (expanded) ──
  {
    slug: "aisha-thompson",
    name: "Aisha Thompson",
    tagline: "Family lifestyle authority, parenting content creator, heartfelt storyteller.",
    credits: [
      { show: "Love & Marriage: DC", network: "OWN", seasons: "2 Seasons", role: "Cast" },
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "2 Seasons", role: "Judge" },
    ],
    following: "1.4M",
    engagement: "6.3%",
    networks: ["OWN", "Hallmark"],
    specialties: ["Parenting", "Lifestyle"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-039",
    previousBrands: ["Target", "Gerber", "Honest Company"],
    social: { instagram: "@aishathompson", tiktok: "@aishathompson" },
  },
  {
    slug: "marcus-andersen",
    name: "Marcus Andersen",
    tagline: "Dad life comedian, family content creator, relatable parenting voice.",
    credits: [
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "1 Season", role: "Guest" },
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
    ],
    following: "560K",
    engagement: "7.4%",
    networks: ["Hallmark", "CBS"],
    specialties: ["Parenting", "Comedy"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1545167622-3a6ac756afa4?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-040",
    previousBrands: ["LEGO", "Pampers", "Disney+"],
    social: { instagram: "@marcusandersen", tiktok: "@marcusandersen" },
  },

  // ══════════════════════════════════════════════
  // ── NEW TALENTS (BT-041 through BT-080) ──
  // ══════════════════════════════════════════════

  // ── Fashion & Lifestyle (new additions) ──
  {
    slug: "yuna-kim",
    name: "Yuna Kim",
    tagline: "Seoul born fashion personality with three seasons of reality TV experience and a loyal following in luxury streetwear.",
    credits: [
      { show: "The Real Housewives", network: "BRAVO", seasons: "2 Seasons", role: "Cast" },
      { show: "The Challenge", network: "MTV", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.7M",
    engagement: "5.4%",
    networks: ["BRAVO", "MTV"],
    specialties: ["Fashion", "Lifestyle"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1545912452-8aea7e25a3d3?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-041",
    previousBrands: ["Revolve", "Gentle Monster", "Aritzia"],
    social: { instagram: "@yunakim", tiktok: "@yunakim" },
  },
  {
    slug: "olivier-baptiste",
    name: "Olivier Baptiste",
    tagline: "Haitian French fashion creator known for two seasons on E! and editorial campaigns with global luxury houses.",
    credits: [
      { show: "Rich Kids of Instagram", network: "E!", seasons: "1 Season", role: "Cast" },
      { show: "Below Deck", network: "BRAVO", seasons: "1 Season", role: "Guest" },
    ],
    following: "980K",
    engagement: "6.1%",
    networks: ["E!", "BRAVO"],
    specialties: ["Fashion", "Drama"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-042",
    previousBrands: ["Balenciaga", "Hennessy", "Mr Porter"],
    social: { instagram: "@olivierbaptiste", tiktok: "@olivierbaptiste" },
  },
  {
    slug: "mei-lin-zhang",
    name: "Mei Lin Zhang",
    tagline: "Four season TV veteran and beauty authority who blends traditional Chinese aesthetics with modern fashion storytelling.",
    credits: [
      { show: "Access Hollywood", network: "NBC", seasons: "2 Seasons", role: "Correspondent" },
      { show: "The Arrangement", network: "E!", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "2.3M",
    engagement: "4.8%",
    networks: ["NBC", "E!"],
    specialties: ["Fashion", "Beauty"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-043",
    previousBrands: ["Shiseido", "Net-a-Porter", "SK-II"],
    social: { instagram: "@meilinzhang", tiktok: "@meilinzhang" },
  },
  {
    slug: "alejandro-vega",
    name: "Alejandro Vega",
    tagline: "Mexican American lifestyle creator with three seasons on MTV and a reputation for building viral fashion moments.",
    credits: [
      { show: "Wild 'N Out", network: "MTV", seasons: "2 Seasons", role: "Cast" },
      { show: "Temptation Island", network: "USA Network", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.5M",
    engagement: "5.7%",
    networks: ["MTV", "USA Network"],
    specialties: ["Lifestyle", "Fashion"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-044",
    previousBrands: ["Nike", "Modelo", "StockX"],
    social: { instagram: "@alejandrovega", tiktok: "@alejandrovega" },
  },
  {
    slug: "nadia-petrova",
    name: "Nadia Petrova",
    tagline: "Eastern European fashion and travel personality with three seasons on BRAVO and editorial work across five continents.",
    credits: [
      { show: "The Real Housewives", network: "BRAVO", seasons: "3 Seasons", role: "Friend Of" },
    ],
    following: "1.1M",
    engagement: "5.9%",
    networks: ["BRAVO"],
    specialties: ["Fashion", "Travel"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-045",
    previousBrands: ["Away Luggage", "Zimmermann", "Tumi"],
    social: { instagram: "@nadiapetrova", tiktok: "@nadiapetrova" },
  },
  {
    slug: "takeshi-yamamoto",
    name: "Takeshi Yamamoto",
    tagline: "Tokyo streetwear icon with two seasons on E! and a growing presence in global menswear collaborations.",
    credits: [
      { show: "The Arrangement", network: "E!", seasons: "1 Season", role: "Featured" },
      { show: "Wild 'N Out", network: "MTV", seasons: "1 Season", role: "Cast" },
    ],
    following: "820K",
    engagement: "7.2%",
    networks: ["E!", "MTV"],
    specialties: ["Fashion", "Lifestyle"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-046",
    previousBrands: ["BAPE", "Uniqlo", "Comme des Garcons"],
    social: { instagram: "@takeshiyamamoto", tiktok: "@takeshiyamamoto" },
  },
  {
    slug: "serena-adeyemi",
    name: "Serena Adeyemi",
    tagline: "Nigerian British fashion and beauty creator with four seasons spanning OWN and BRAVO, known for effortless editorial style.",
    credits: [
      { show: "Super Soul Sunday", network: "OWN", seasons: "2 Seasons", role: "Guest" },
      { show: "The Real Housewives", network: "BRAVO", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "2.0M",
    engagement: "5.3%",
    networks: ["OWN", "BRAVO"],
    specialties: ["Fashion", "Beauty"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1523450001312-faa4e2e37f0f?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-047",
    previousBrands: ["Fenty", "ASOS", "MAC Cosmetics"],
    social: { instagram: "@serenaadeyemi", tiktok: "@serenaadeyemi" },
  },

  // ── Fitness & Yoga (new additions) ──
  {
    slug: "ji-won-park",
    name: "Ji-Won Park",
    tagline: "Korean yoga and wellness creator with three seasons on network TV and a devoted following in mindful movement.",
    credits: [
      { show: "American Ninja Warrior", network: "NBC", seasons: "2 Seasons", role: "Contestant" },
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.9M",
    engagement: "5.6%",
    networks: ["NBC", "CBS"],
    specialties: ["Yoga", "Wellness"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1611672585731-fa10603fb9e0?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-048",
    previousBrands: ["Lululemon", "Calm", "Manduka"],
    social: { instagram: "@jiwonpark", tiktok: "@jiwonpark" },
  },
  {
    slug: "dante-williams",
    name: "Dante Williams",
    tagline: "Four season fitness veteran who combines athletic training with lifestyle storytelling across NBC and USA Network.",
    credits: [
      { show: "Temptation Island", network: "USA Network", seasons: "2 Seasons", role: "Cast" },
      { show: "American Ninja Warrior", network: "NBC", seasons: "2 Seasons", role: "Finalist" },
    ],
    following: "2.6M",
    engagement: "4.9%",
    networks: ["USA Network", "NBC"],
    specialties: ["Fitness", "Lifestyle"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-049",
    previousBrands: ["Nike", "WHOOP", "Muscle Milk"],
    social: { instagram: "@dantewilliams", tiktok: "@dantewilliams", youtube: "@DanteWilliamsFit" },
  },
  {
    slug: "sakura-ito",
    name: "Sakura Ito",
    tagline: "Japanese yoga and beauty personality with two MTV seasons and a growing audience in holistic wellness content.",
    credits: [
      { show: "The Challenge", network: "MTV", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "1.0M",
    engagement: "6.8%",
    networks: ["MTV"],
    specialties: ["Yoga", "Beauty"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-050",
    previousBrands: ["Alo Yoga", "Tatcha", "Headspace"],
    social: { instagram: "@sakuraito", tiktok: "@sakuraito" },
  },
  {
    slug: "rafael-torres",
    name: "Rafael Torres",
    tagline: "Puerto Rican fitness comedian with three seasons on CBS and NBC, known for making workouts entertaining and accessible.",
    credits: [
      { show: "Survivor", network: "CBS", seasons: "2 Seasons", role: "Cast" },
      { show: "Access Hollywood", network: "NBC", seasons: "1 Season", role: "Guest" },
    ],
    following: "1.4M",
    engagement: "7.1%",
    networks: ["CBS", "NBC"],
    specialties: ["Fitness", "Comedy"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-051",
    previousBrands: ["Under Armour", "C4 Energy", "Chipotle"],
    social: { instagram: "@rafaeltorres", tiktok: "@rafaeltorres" },
  },
  {
    slug: "leila-ahmadi",
    name: "Leila Ahmadi",
    tagline: "Iranian American fitness and wellness creator with two seasons on OWN and USA Network, advocating for inclusive training.",
    credits: [
      { show: "Super Soul Sunday", network: "OWN", seasons: "1 Season", role: "Guest" },
      { show: "Temptation Island", network: "USA Network", seasons: "1 Season", role: "Cast" },
    ],
    following: "870K",
    engagement: "6.5%",
    networks: ["OWN", "USA Network"],
    specialties: ["Fitness", "Wellness"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1584863231364-2edc166de576?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-052",
    previousBrands: ["Gymshark", "Vital Proteins", "Bala"],
    social: { instagram: "@leilaahmadi", tiktok: "@leilaahmadi" },
  },
  {
    slug: "kwame-mensah",
    name: "Kwame Mensah",
    tagline: "Ghanaian fitness personality with three seasons across NBC and MTV, building a global community around strength training.",
    credits: [
      { show: "American Ninja Warrior", network: "NBC", seasons: "2 Seasons", role: "Contestant" },
      { show: "The Challenge", network: "MTV", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.7M",
    engagement: "5.2%",
    networks: ["NBC", "MTV"],
    specialties: ["Fitness", "Lifestyle"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1548372290-8d01b6c8e78c?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-053",
    previousBrands: ["Adidas", "Huel", "Fitbit"],
    social: { instagram: "@kwamemensah", tiktok: "@kwamemensah" },
  },
  {
    slug: "ananya-desai",
    name: "Ananya Desai",
    tagline: "Indian yoga and lifestyle creator with two seasons on OWN, blending ancient practice with modern wellness storytelling.",
    credits: [
      { show: "Super Soul Sunday", network: "OWN", seasons: "2 Seasons", role: "Guest" },
    ],
    following: "1.2M",
    engagement: "6.3%",
    networks: ["OWN"],
    specialties: ["Yoga", "Lifestyle"],
    category: "Fitness & Yoga",
    image: "https://images.unsplash.com/photo-1590086783191-a0694c7d1e6e?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-054",
    previousBrands: ["Alo Yoga", "Calm", "Whole Foods"],
    social: { instagram: "@ananyaDesai", tiktok: "@ananyadesai" },
  },

  // ── Chefs & Food (new additions) ──
  {
    slug: "chef-hyun-soo",
    name: "Chef Hyun-Soo",
    tagline: "Korean culinary star with four Food Network seasons and a reputation for turning traditional recipes into viral sensations.",
    credits: [
      { show: "Chopped", network: "Food Network", seasons: "3 Seasons", role: "Champion" },
      { show: "Beat Bobby Flay", network: "Food Network", seasons: "1 Season", role: "Winner" },
    ],
    following: "2.9M",
    engagement: "5.8%",
    networks: ["Food Network"],
    specialties: ["Food", "Lifestyle"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-055",
    previousBrands: ["KitchenAid", "Trader Joe's", "Samsung"],
    social: { instagram: "@chefhyunsoo", tiktok: "@chefhyunsoo", youtube: "@ChefHyunSoo" },
  },
  {
    slug: "isabella-moreno",
    name: "Isabella Moreno",
    tagline: "Colombian food and travel creator with three seasons on Food Network and BRAVO, celebrating Latin cuisine worldwide.",
    credits: [
      { show: "The Kitchen", network: "Food Network", seasons: "2 Seasons", role: "Co-host" },
      { show: "Below Deck", network: "BRAVO", seasons: "1 Season", role: "Guest" },
    ],
    following: "1.5M",
    engagement: "5.5%",
    networks: ["Food Network", "BRAVO"],
    specialties: ["Food", "Travel"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1583394293214-28ded15ee548?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-056",
    previousBrands: ["HelloFresh", "Le Creuset", "Airbnb"],
    social: { instagram: "@isabellamoreno", tiktok: "@isabellamorenocooks" },
  },
  {
    slug: "chef-amir-hassan",
    name: "Chef Amir Hassan",
    tagline: "Five season Food Network veteran and Lebanese culinary personality who brings humor and spice to every dish.",
    credits: [
      { show: "Chopped", network: "Food Network", seasons: "3 Seasons", role: "Champion" },
      { show: "Survivor", network: "CBS", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "3.4M",
    engagement: "4.6%",
    networks: ["Food Network", "CBS"],
    specialties: ["Food", "Comedy"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-057",
    previousBrands: ["McCormick", "Williams Sonoma", "DoorDash"],
    social: { instagram: "@chefamirhassan", tiktok: "@chefamirhassan", youtube: "@ChefAmirHassan" },
  },
  {
    slug: "thanh-nguyen",
    name: "Thanh Nguyen",
    tagline: "Vietnamese American chef with two seasons on Food Network and NBC, specializing in Southeast Asian fusion cuisine.",
    credits: [
      { show: "MasterChef", network: "Food Network", seasons: "1 Season", role: "Finalist" },
      { show: "The Great American Recipe", network: "NBC", seasons: "1 Season", role: "Contestant" },
    ],
    following: "1.1M",
    engagement: "6.7%",
    networks: ["Food Network", "NBC"],
    specialties: ["Food", "Lifestyle"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1566554273541-37a9ca77b91f?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-058",
    previousBrands: ["Blue Apron", "Vitamix", "Whole Foods"],
    social: { instagram: "@thanhnguyen", tiktok: "@thanhnguyen" },
  },
  {
    slug: "bianca-ferretti",
    name: "Bianca Ferretti",
    tagline: "Italian food and beauty creator with three seasons on BRAVO and Food Network, blending culinary art with lifestyle content.",
    credits: [
      { show: "The Real Housewives", network: "BRAVO", seasons: "2 Seasons", role: "Friend Of" },
      { show: "The Kitchen", network: "Food Network", seasons: "1 Season", role: "Guest" },
    ],
    following: "1.8M",
    engagement: "5.1%",
    networks: ["BRAVO", "Food Network"],
    specialties: ["Food", "Beauty"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1496440737103-cd596325d314?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-059",
    previousBrands: ["Le Creuset", "Glossier", "Eataly"],
    social: { instagram: "@biancaferretti", tiktok: "@biancaferretticooks" },
  },
  {
    slug: "jiro-watanabe",
    name: "Jiro Watanabe",
    tagline: "Japanese culinary storyteller with three Food Network seasons, celebrated for modernizing traditional sushi and ramen techniques.",
    credits: [
      { show: "Chopped", network: "Food Network", seasons: "2 Seasons", role: "Contestant" },
      { show: "Beat Bobby Flay", network: "Food Network", seasons: "1 Season", role: "Winner" },
    ],
    following: "1.3M",
    engagement: "6.0%",
    networks: ["Food Network"],
    specialties: ["Food", "Travel"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-060",
    previousBrands: ["Instant Pot", "Sur La Table", "Sake One"],
    social: { instagram: "@jirowatanabe", tiktok: "@jirowatanabe" },
  },
  {
    slug: "fatima-al-rashid",
    name: "Fatima Al-Rashid",
    tagline: "Emirati food and lifestyle creator with two seasons on Food Network and OWN, sharing Middle Eastern cuisine with global audiences.",
    credits: [
      { show: "MasterChef", network: "Food Network", seasons: "1 Season", role: "Contestant" },
      { show: "Super Soul Sunday", network: "OWN", seasons: "1 Season", role: "Guest" },
    ],
    following: "950K",
    engagement: "7.0%",
    networks: ["Food Network", "OWN"],
    specialties: ["Food", "Lifestyle"],
    category: "Chefs & Food",
    image: "https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-061",
    previousBrands: ["Whole Foods", "McCormick", "HelloFresh"],
    social: { instagram: "@fatimaalrashid", tiktok: "@fatimaalrashid" },
  },

  // ── Beauty & Skincare (new additions) ──
  {
    slug: "soo-yeon-choi",
    name: "Soo-Yeon Choi",
    tagline: "Korean skincare authority with three seasons on E! and BRAVO, leading the K beauty movement in mainstream television.",
    credits: [
      { show: "The Arrangement", network: "E!", seasons: "2 Seasons", role: "Cast" },
      { show: "Below Deck", network: "BRAVO", seasons: "1 Season", role: "Guest" },
    ],
    following: "2.4M",
    engagement: "4.9%",
    networks: ["E!", "BRAVO"],
    specialties: ["Beauty", "Skincare"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-062",
    previousBrands: ["Laneige", "Glow Recipe", "Sephora"],
    social: { instagram: "@sooyeonchoi", tiktok: "@sooyeonchoi" },
  },
  {
    slug: "naomi-okafor",
    name: "Naomi Okafor",
    tagline: "Nigerian beauty mogul with four seasons on OWN and E!, championing inclusive beauty standards across every platform.",
    credits: [
      { show: "Love & Marriage: DC", network: "OWN", seasons: "2 Seasons", role: "Cast" },
      { show: "Rich Kids of Instagram", network: "E!", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "3.0M",
    engagement: "4.3%",
    networks: ["OWN", "E!"],
    specialties: ["Beauty", "Fashion"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-063",
    previousBrands: ["Fenty Beauty", "Charlotte Tilbury", "Ulta Beauty"],
    social: { instagram: "@naomiokafor", tiktok: "@naomiokafor", youtube: "@NaomiOkaforBeauty" },
  },
  {
    slug: "kenji-tanaka",
    name: "Kenji Tanaka",
    tagline: "Japanese skincare and lifestyle creator with two BRAVO seasons, pioneering men's grooming content in the reality TV space.",
    credits: [
      { show: "Below Deck", network: "BRAVO", seasons: "1 Season", role: "Guest" },
      { show: "The Real Housewives", network: "BRAVO", seasons: "1 Season", role: "Friend Of" },
    ],
    following: "680K",
    engagement: "8.1%",
    networks: ["BRAVO"],
    specialties: ["Skincare", "Lifestyle"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-064",
    previousBrands: ["Harry's", "CeraVe", "Aesop"],
    social: { instagram: "@kenjitanaka", tiktok: "@kenjitanaka" },
  },
  {
    slug: "aaliyah-chen",
    name: "Aaliyah Chen",
    tagline: "Chinese American beauty and wellness creator with three seasons on MTV and E!, known for blending Eastern and Western beauty rituals.",
    credits: [
      { show: "The Challenge", network: "MTV", seasons: "2 Seasons", role: "Cast" },
      { show: "The Arrangement", network: "E!", seasons: "1 Season", role: "Featured" },
    ],
    following: "1.9M",
    engagement: "5.5%",
    networks: ["MTV", "E!"],
    specialties: ["Beauty", "Wellness"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1485893086445-ed75865251e0?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-065",
    previousBrands: ["SK-II", "Drunk Elephant", "Tatcha"],
    social: { instagram: "@aaliyahchen", tiktok: "@aaliyahchen" },
  },
  {
    slug: "daniela-reyes",
    name: "Daniela Reyes",
    tagline: "Dominican beauty and skincare personality with two seasons on BRAVO and OWN, creating content for Latina audiences worldwide.",
    credits: [
      { show: "The Real Housewives", network: "BRAVO", seasons: "1 Season", role: "Friend Of" },
      { show: "Love & Marriage: DC", network: "OWN", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.1M",
    engagement: "6.2%",
    networks: ["BRAVO", "OWN"],
    specialties: ["Beauty", "Skincare"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-066",
    previousBrands: ["Glossier", "Olay", "Morphe"],
    social: { instagram: "@danielareyes", tiktok: "@danielareyes" },
  },
  {
    slug: "hiroshi-sato",
    name: "Hiroshi Sato",
    tagline: "Japanese skincare and fitness creator with three seasons on E! and NBC, merging grooming expertise with athletic lifestyle content.",
    credits: [
      { show: "The Arrangement", network: "E!", seasons: "2 Seasons", role: "Cast" },
      { show: "Access Hollywood", network: "NBC", seasons: "1 Season", role: "Guest" },
    ],
    following: "890K",
    engagement: "6.9%",
    networks: ["E!", "NBC"],
    specialties: ["Skincare", "Fitness"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-067",
    previousBrands: ["Aesop", "Nike", "The Ordinary"],
    social: { instagram: "@hiroshisato", tiktok: "@hiroshisato" },
  },
  {
    slug: "layla-ibrahim",
    name: "Layla Ibrahim",
    tagline: "Egyptian American beauty and lifestyle creator with four seasons on OWN and Hallmark, celebrated for her radiant natural beauty content.",
    credits: [
      { show: "Love & Marriage: Huntsville", network: "OWN", seasons: "2 Seasons", role: "Cast" },
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "2 Seasons", role: "Judge" },
    ],
    following: "1.6M",
    engagement: "5.0%",
    networks: ["OWN", "Hallmark"],
    specialties: ["Beauty", "Lifestyle"],
    category: "Beauty & Skincare",
    image: "https://images.unsplash.com/photo-1581803118522-7b72a50f7e9f?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-068",
    previousBrands: ["Fenty Skin", "Sephora", "Herbivore"],
    social: { instagram: "@laylaibrahim", tiktok: "@laylaibrahim" },
  },

  // ── Comedy & Entertainment (new additions) ──
  {
    slug: "min-jun-lee",
    name: "Min-Jun Lee",
    tagline: "Korean American comedy powerhouse with four seasons across MTV, NBC, and CBS, known for his sharp improvisation and physical comedy.",
    credits: [
      { show: "Wild 'N Out", network: "MTV", seasons: "2 Seasons", role: "Cast" },
      { show: "Access Hollywood", network: "NBC", seasons: "1 Season", role: "Guest" },
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
    ],
    following: "2.1M",
    engagement: "5.3%",
    networks: ["MTV", "NBC", "CBS"],
    specialties: ["Comedy", "Drama"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-069",
    previousBrands: ["Netflix", "Cash App", "State Farm"],
    social: { instagram: "@minjunlee", tiktok: "@minjunlee", youtube: "@MinJunLeeComedy" },
  },
  {
    slug: "gabrielle-fontaine",
    name: "Gabrielle Fontaine",
    tagline: "French Canadian comedy and lifestyle creator with three seasons on NBC and MTV, bringing warmth and wit to every collaboration.",
    credits: [
      { show: "Access Hollywood", network: "NBC", seasons: "2 Seasons", role: "Correspondent" },
      { show: "Wild 'N Out", network: "MTV", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.8M",
    engagement: "4.7%",
    networks: ["NBC", "MTV"],
    specialties: ["Comedy", "Lifestyle"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-070",
    previousBrands: ["Hulu", "BetterHelp", "Fashion Nova"],
    social: { instagram: "@gabriellefontaine", tiktok: "@gabriellefontaine" },
  },
  {
    slug: "andre-baptiste",
    name: "Andre Baptiste",
    tagline: "Five season comedy veteran across CBS and MTV with a natural stage presence that translates seamlessly to brand campaigns.",
    credits: [
      { show: "Survivor", network: "CBS", seasons: "2 Seasons", role: "Cast" },
      { show: "Wild 'N Out", network: "MTV", seasons: "3 Seasons", role: "Cast" },
    ],
    following: "3.3M",
    engagement: "4.2%",
    networks: ["CBS", "MTV"],
    specialties: ["Comedy", "Entertainment"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-071",
    previousBrands: ["Pepsi", "Netflix", "Beats by Dre"],
    social: { instagram: "@andrebaptiste", tiktok: "@andrebaptiste", youtube: "@AndreBaptisteComedy" },
  },
  {
    slug: "priya-kapoor",
    name: "Priya Kapoor",
    tagline: "Indian entertainment and drama creator with two seasons on NBC and OWN, bringing Bollywood energy to American television.",
    credits: [
      { show: "Access Hollywood", network: "NBC", seasons: "1 Season", role: "Guest" },
      { show: "Love & Marriage: DC", network: "OWN", seasons: "1 Season", role: "Cast" },
    ],
    following: "1.0M",
    engagement: "7.3%",
    networks: ["NBC", "OWN"],
    specialties: ["Entertainment", "Drama"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-072",
    previousBrands: ["Disney+", "Savage X Fenty", "BetterHelp"],
    social: { instagram: "@priyakapoor", tiktok: "@priyakapoor" },
  },
  {
    slug: "rio-nakamura",
    name: "Rio Nakamura",
    tagline: "Japanese comedy and music personality with three seasons on MTV and E!, fusing stand up comedy with musical performance.",
    credits: [
      { show: "Wild 'N Out", network: "MTV", seasons: "2 Seasons", role: "Cast" },
      { show: "The Arrangement", network: "E!", seasons: "1 Season", role: "Featured" },
    ],
    following: "1.5M",
    engagement: "5.8%",
    networks: ["MTV", "E!"],
    specialties: ["Comedy", "Music"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1542596768-5d1d21f1cf98?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-073",
    previousBrands: ["Spotify", "Cash App", "Chipotle"],
    social: { instagram: "@rionakamura", tiktok: "@rionakamura" },
  },
  {
    slug: "amira-hassan",
    name: "Amira Hassan",
    tagline: "Somali American entertainment and comedy creator with four seasons on NBC and CBS, known for her bold storytelling and stage command.",
    credits: [
      { show: "Access Hollywood", network: "NBC", seasons: "2 Seasons", role: "Correspondent" },
      { show: "Survivor", network: "CBS", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "2.2M",
    engagement: "4.5%",
    networks: ["NBC", "CBS"],
    specialties: ["Entertainment", "Comedy"],
    category: "Comedy & Entertainment",
    image: "https://images.unsplash.com/photo-1546961342-ea5f71b193f3?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-074",
    previousBrands: ["Netflix", "Pepsi", "Hulu"],
    social: { instagram: "@amirahassan", tiktok: "@amirahassan" },
  },

  // ── Parenting & Family (new additions) ──
  {
    slug: "soon-hee-kang",
    name: "Soon-Hee Kang",
    tagline: "Korean American parenting and lifestyle creator with three seasons on OWN and Hallmark, sharing family stories with authenticity.",
    credits: [
      { show: "Love & Marriage: Huntsville", network: "OWN", seasons: "2 Seasons", role: "Cast" },
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "1 Season", role: "Guest" },
    ],
    following: "1.3M",
    engagement: "6.1%",
    networks: ["OWN", "Hallmark"],
    specialties: ["Parenting", "Lifestyle"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1514315384763-ba401779410f?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-075",
    previousBrands: ["Target", "Pampers", "Gerber"],
    social: { instagram: "@soonheekang", tiktok: "@soonheekang" },
  },
  {
    slug: "emmanuel-okafor",
    name: "Emmanuel Okafor",
    tagline: "Nigerian dad content creator with four seasons on Hallmark and OWN, turning everyday parenting into comedic gold.",
    credits: [
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "2 Seasons", role: "Judge" },
      { show: "Love & Marriage: DC", network: "OWN", seasons: "2 Seasons", role: "Cast" },
    ],
    following: "1.7M",
    engagement: "5.4%",
    networks: ["Hallmark", "OWN"],
    specialties: ["Parenting", "Comedy"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-076",
    previousBrands: ["LEGO", "Disney+", "Huggies"],
    social: { instagram: "@emmanuelokafor", tiktok: "@emmanuelokafor" },
  },
  {
    slug: "lisa-yamada",
    name: "Lisa Yamada",
    tagline: "Japanese American parenting and wellness personality with two seasons on OWN and NBC, advocating for mindful family living.",
    credits: [
      { show: "Super Soul Sunday", network: "OWN", seasons: "1 Season", role: "Guest" },
      { show: "Access Hollywood", network: "NBC", seasons: "1 Season", role: "Guest" },
    ],
    following: "890K",
    engagement: "6.7%",
    networks: ["OWN", "NBC"],
    specialties: ["Parenting", "Wellness"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-077",
    previousBrands: ["Honest Company", "Calm", "Pampers"],
    social: { instagram: "@lisayamada", tiktok: "@lisayamada" },
  },
  {
    slug: "carlos-mendez",
    name: "Carlos Mendez",
    tagline: "Mexican American family lifestyle creator with three seasons on Hallmark and CBS, celebrating bilingual parenting with humor.",
    credits: [
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "2 Seasons", role: "Guest" },
      { show: "Survivor", network: "CBS", seasons: "1 Season", role: "Cast" },
    ],
    following: "760K",
    engagement: "7.8%",
    networks: ["Hallmark", "CBS"],
    specialties: ["Parenting", "Lifestyle"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-078",
    previousBrands: ["Target", "LEGO", "Disney+"],
    social: { instagram: "@carlosmendez", tiktok: "@carlosmendez" },
  },
  {
    slug: "adaeze-nwosu",
    name: "Adaeze Nwosu",
    tagline: "Five season parenting and beauty personality on OWN and Hallmark, one of the most trusted family voices in reality television.",
    credits: [
      { show: "Love & Marriage: Huntsville", network: "OWN", seasons: "3 Seasons", role: "Cast" },
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "2 Seasons", role: "Judge" },
    ],
    following: "2.0M",
    engagement: "4.8%",
    networks: ["OWN", "Hallmark"],
    specialties: ["Parenting", "Beauty"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1596815064285-45ed8a9c0463?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-079",
    previousBrands: ["Fenty Beauty", "Gerber", "Honest Company"],
    social: { instagram: "@adaezenwosu", tiktok: "@adaezenwosu" },
  },
  {
    slug: "jin-woo-cho",
    name: "Jin-Woo Cho",
    tagline: "Korean dad comedian with two Hallmark seasons, creating relatable family content that resonates with parents everywhere.",
    credits: [
      { show: "Christmas Cookie Challenge", network: "Hallmark", seasons: "2 Seasons", role: "Guest" },
    ],
    following: "540K",
    engagement: "8.4%",
    networks: ["Hallmark"],
    specialties: ["Parenting", "Comedy"],
    category: "Parenting & Family",
    image: "https://images.unsplash.com/photo-1504593811423-6dd665756598?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-080",
    previousBrands: ["LEGO", "Pampers", "Huggies"],
    social: { instagram: "@jinwoocho", tiktok: "@jinwoocho" },
  },
  {
    slug: "maya-okonkwo",
    name: "Maya Okonkwo",
    tagline: "Nigerian British lifestyle creator with three seasons on BRAVO and E!, celebrated for her editorial fashion content and cultural storytelling.",
    credits: [
      { show: "Real Housewives", network: "BRAVO", seasons: "2 Seasons", role: "Cast" },
      { show: "The Arrangement", network: "E!", seasons: "1 Season", role: "Featured" },
    ],
    following: "1.9M",
    engagement: "5.7%",
    networks: ["BRAVO", "E!"],
    specialties: ["Fashion", "Lifestyle"],
    category: "Fashion & Lifestyle",
    image: "https://images.unsplash.com/photo-1567784177951-6fa58317e16b?w=600&h=800&fit=crop&crop=face&q=80",
    talentId: "BT-081",
    previousBrands: ["Zara", "ASOS", "Glossier"],
    social: { instagram: "@mayaokonkwo", tiktok: "@mayaokonkwo" },
  },
]

export function getTalentBySlug(slug: string): TalentProfile | undefined {
  return talentRoster.find((t) => t.slug === slug)
}
