export type TalentTier = 'Marquee' | 'Core' | 'Rising'
export type TalentStatus = 'invited' | 'claimed' | 'onboarding' | 'active' | 'inactive'

export interface TalentProfile {
  id: string
  slug: string
  inviteSlug: string
  name: string
  tier: TalentTier
  priority: number
  genre: string
  credits: string
  igHandle: string
  igUrl: string
  ttHandle: string
  ttUrl: string
  igFollowers: string
  ttFollowers: string
  totalFollowing: string
  imageUrl: string
  bio: string
  status: TalentStatus
  email: string
  phone: string
  categories: string[]
  networks: string[]
}

export const talent: TalentProfile[] = [
  // =======================================
  // MARQUEE TIER (13 creators)
  // =======================================
  {
    id: 'bt-001',
    slug: 'bella-poarch',
    inviteSlug: 'bp-invite-2026',
    name: 'Bella Poarch',
    tier: 'Marquee',
    priority: 1,
    genre: 'Music/Fashion/Viral Content',
    credits: 'TikTok Icon. Warner Records artist. Forbes 30 Under 30. 4th most followed on TikTok globally.',
    igHandle: '@bellapoarch',
    igUrl: 'https://instagram.com/bellapoarch',
    ttHandle: '@bellapoarch',
    ttUrl: 'https://tiktok.com/@bellapoarch',
    igFollowers: '11.5M',
    ttFollowers: '92.8M',
    totalFollowing: '104M+',
    imageUrl: '',
    bio: 'Singer, content creator, and cultural phenomenon with over 100 million followers worldwide. Warner Records artist with multiple viral singles and Forbes 30 Under 30 honoree.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Fashion', 'Beauty', 'Lifestyle'],
    networks: ['TikTok', 'YouTube'],
  },
  {
    id: 'bt-002',
    slug: 'john-stamos',
    inviteSlug: 'js-invite-2026',
    name: 'John Stamos',
    tier: 'Marquee',
    priority: 2,
    genre: 'Actor/Music/Family',
    credits: 'Full House. Fuller House. Grandfathered. ER. Palm Royale.',
    igHandle: '@johnstamos',
    igUrl: 'https://instagram.com/johnstamos',
    ttHandle: '@johnstamos',
    ttUrl: 'https://tiktok.com/@johnstamos',
    igFollowers: '7.2M',
    ttFollowers: '1.8M',
    totalFollowing: '9M+',
    imageUrl: '',
    bio: 'Emmy nominated actor with four decades of television credits. Known worldwide for Full House and its sequel Fuller House, currently starring in Palm Royale.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Music', 'Family'],
    networks: ['ABC', 'Netflix', 'Hulu', 'Apple TV+'],
  },
  {
    id: 'bt-003',
    slug: 'raven-symone',
    inviteSlug: 'rs-invite-2026',
    name: 'Raven Symone',
    tier: 'Marquee',
    priority: 3,
    genre: 'Actress/Beauty/Hosting',
    credits: "That's So Raven. The Cheetah Girls. The View. Raven's Home. Host of Scrabble.",
    igHandle: '@ravensymone',
    igUrl: 'https://instagram.com/ravensymone',
    ttHandle: '@ravensymone',
    ttUrl: 'https://tiktok.com/@ravensymone',
    igFollowers: '4.8M',
    ttFollowers: '2.1M',
    totalFollowing: '7M+',
    imageUrl: '',
    bio: 'Disney legend and Emmy nominated actress. Host of Scrabble on CBS and former co host of The View.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Beauty', 'Hosting', 'Comedy'],
    networks: ['Disney Channel', 'ABC', 'CBS'],
  },
  {
    id: 'bt-004',
    slug: 'christina-milian',
    inviteSlug: 'cm-invite-2026',
    name: 'Christina Milian',
    tier: 'Marquee',
    priority: 4,
    genre: 'Actress/Beauty/Food/Music',
    credits: "Dip'd in Chocolate (Netflix). Falling Inn Love. Love Don't Cost a Thing. Meet Me Next Christmas.",
    igHandle: '@christinamilian',
    igUrl: 'https://instagram.com/christinamilian',
    ttHandle: '@christinamilian',
    ttUrl: 'https://tiktok.com/@christinamilian',
    igFollowers: '7.1M',
    ttFollowers: '1.5M',
    totalFollowing: '8.5M+',
    imageUrl: '',
    bio: 'Actress, singer, and entrepreneur. Netflix star with multiple original films and founder of Beignet Box.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Beauty', 'Food', 'Music'],
    networks: ['Netflix', 'Fox', 'MTV'],
  },
  {
    id: 'bt-005',
    slug: 'adam-lambert',
    inviteSlug: 'al-invite-2026',
    name: 'Adam Lambert',
    tier: 'Marquee',
    priority: 5,
    genre: 'Music/Fashion/Makeup/LGBTQ+',
    credits: 'American Idol Season 8 runner up. Lead vocalist of Queen + Adam Lambert. Grammy nominated.',
    igHandle: '@adamlambert',
    igUrl: 'https://instagram.com/adamlambert',
    ttHandle: '@adamlambert',
    ttUrl: 'https://tiktok.com/@adamlambert',
    igFollowers: '3.2M',
    ttFollowers: '1.1M',
    totalFollowing: '4.3M+',
    imageUrl: '',
    bio: "Grammy nominated singer and frontman of Queen + Adam Lambert. American Idol Season 8 runner up who became one of the franchise's most successful artists.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Fashion', 'Beauty', 'LGBTQ+'],
    networks: ['Fox', 'ABC'],
  },
  {
    id: 'bt-006',
    slug: 'kat-von-d',
    inviteSlug: 'kvd-invite-2026',
    name: 'Kat Von D',
    tier: 'Marquee',
    priority: 6,
    genre: 'Fashion/Tattoo/Agriculture',
    credits: 'LA Ink. Miami Ink. Lincoln Lawyer. Founded Kat Von D Beauty (sold to Kendo).',
    igHandle: '@thekatvond',
    igUrl: 'https://instagram.com/thekatvond',
    ttHandle: '@thekatvond',
    ttUrl: 'https://tiktok.com/@thekatvond',
    igFollowers: '7.8M',
    ttFollowers: '2.3M',
    totalFollowing: '10M+',
    imageUrl: '',
    bio: 'Tattoo artist, entrepreneur, and television personality. Founded Kat Von D Beauty, sold for a reported $50M+, and starred in LA Ink.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Tattoo', 'Agriculture', 'Beauty'],
    networks: ['TLC', 'Netflix'],
  },
  {
    id: 'bt-007',
    slug: 'dita-von-teese',
    inviteSlug: 'dvt-invite-2026',
    name: 'Dita Von Teese',
    tier: 'Marquee',
    priority: 7,
    genre: 'Burlesque/Vintage Fashion/Makeup',
    credits: 'Burlesque icon. Author. Lingerie designer. Perfumer. Global touring show.',
    igHandle: '@ditavonteese',
    igUrl: 'https://instagram.com/ditavonteese',
    ttHandle: '@ditavonteese',
    ttUrl: 'https://tiktok.com/@ditavonteese',
    igFollowers: '3.5M',
    ttFollowers: '650K',
    totalFollowing: '4.2M+',
    imageUrl: '',
    bio: 'Queen of burlesque and global style icon. Author, lingerie designer, perfumer, and star of a globally touring theatrical show.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Beauty', 'Vintage', 'Entertainment'],
    networks: [],
  },
  {
    id: 'bt-008',
    slug: 'tiffany-pollard',
    inviteSlug: 'tp-invite-2026',
    name: 'Tiffany Pollard',
    tier: 'Marquee',
    priority: 8,
    genre: 'Entertainment/Comedy/Reality TV Icon',
    credits: 'Flavor of Love (VH1). I Love New York (VH1). Celebrity Big Brother UK. House of Villains S3 (E!).',
    igHandle: '@haborfreak',
    igUrl: 'https://instagram.com/haborfreak',
    ttHandle: '@taborfreak',
    ttUrl: 'https://tiktok.com/@taborfreak',
    igFollowers: '2.8M',
    ttFollowers: '3.5M',
    totalFollowing: '6.3M+',
    imageUrl: '',
    bio: "Reality television royalty known as 'New York,' one of the most iconic and quoted reality TV personalities in history. Currently starring in House of Villains Season 3.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Entertainment', 'Comedy', 'Reality TV'],
    networks: ['VH1', 'E!', 'Channel 5 UK'],
  },
  {
    id: 'bt-009',
    slug: 'riley-green',
    inviteSlug: 'rg-invite-2026',
    name: 'Riley Green',
    tier: 'Marquee',
    priority: 9,
    genre: 'Country Music/Hunting/Outdoors',
    credits: 'Redneck Island. Grammy winner. Multiple platinum singles.',
    igHandle: '@rileygreen',
    igUrl: 'https://instagram.com/rileygreen',
    ttHandle: '@rileygreen',
    ttUrl: 'https://tiktok.com/@rileygreen',
    igFollowers: '2.4M',
    ttFollowers: '3.8M',
    totalFollowing: '6.2M+',
    imageUrl: '',
    bio: 'Grammy winning country music artist with multiple platinum singles including "I Wish Grandpas Never Died." Arena touring headliner and outdoors enthusiast.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Outdoors', 'Hunting', 'Country'],
    networks: ['CMT'],
  },
  {
    id: 'bt-010',
    slug: 'ian-somerhalder',
    inviteSlug: 'is-invite-2026',
    name: 'Ian Somerhalder',
    tier: 'Marquee',
    priority: 10,
    genre: 'Actor/Animals/Clean Living/Health',
    credits: 'Vampire Diaries. Lost. V Wars. Ian Somerhalder Foundation.',
    igHandle: '@iansomerhalder',
    igUrl: 'https://instagram.com/iansomerhalder',
    ttHandle: '@iansomerhalder',
    ttUrl: 'https://tiktok.com/@iansomerhalder',
    igFollowers: '23.5M',
    ttFollowers: '2.1M',
    totalFollowing: '25.5M+',
    imageUrl: '',
    bio: 'Actor, environmental activist, and entrepreneur. Star of The Vampire Diaries and Lost, and co founder of Brothers Bond Bourbon.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Wellness', 'Animals', 'Spirits'],
    networks: ['The CW', 'ABC', 'Netflix'],
  },
  {
    id: 'bt-011',
    slug: 'stassi-schroeder',
    inviteSlug: 'ss-invite-2026',
    name: 'Stassi Schroeder',
    tier: 'Marquee',
    priority: 11,
    genre: 'Fashion/Mom Life/Podcast',
    credits: 'Vanderpump Rules (Bravo, 8 seasons). Author. Podcast host.',
    igHandle: '@stassischroeder',
    igUrl: 'https://instagram.com/stassischroeder',
    ttHandle: '@stassischroeder',
    ttUrl: 'https://tiktok.com/@stassischroeder',
    igFollowers: '4M',
    ttFollowers: '450K',
    totalFollowing: '4.5M+',
    imageUrl: '',
    bio: "Original Vanderpump Rules star and New York Times bestselling author of 'Next Level Basic.' Host of the hit podcast 'Straight Up with Stassi.'",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Lifestyle', 'Parenting', 'Podcast'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-012',
    slug: 'gypsy-rose-blanchard',
    inviteSlug: 'grb-invite-2026',
    name: 'Gypsy Rose Blanchard',
    tier: 'Marquee',
    priority: 12,
    genre: 'Lifestyle/True Crime',
    credits: 'The Act (Hulu). Life After Lock Up. Prison Confessions (Lifetime). Multiple documentaries.',
    igHandle: '@gypsyrose_a_blanchard',
    igUrl: 'https://instagram.com/gypsyrose_a_blanchard',
    ttHandle: '@gypsyrosee',
    ttUrl: 'https://tiktok.com/@gypsyrosee',
    igFollowers: '9.2M',
    ttFollowers: '6.5M',
    totalFollowing: '15.7M+',
    imageUrl: '',
    bio: 'Public figure, author, and advocate. Subject of the award winning Hulu series The Act, documented across multiple networks and streaming platforms.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Lifestyle', 'True Crime', 'Advocacy'],
    networks: ['Hulu', 'Lifetime', 'Investigation Discovery'],
  },
  {
    id: 'bt-013',
    slug: 'johnny-weir',
    inviteSlug: 'jw-invite-2026',
    name: 'Johnny Weir',
    tier: 'Marquee',
    priority: 13,
    genre: 'Figure Skating/Fashion/Comedy',
    credits: 'Olympic figure skater (2006, 2010). NBC Olympics commentator. The Masked Singer. Surreal Life.',
    igHandle: '@johnnygweir',
    igUrl: 'https://instagram.com/johnnygweir',
    ttHandle: '@johnnygweir',
    ttUrl: 'https://tiktok.com/@johnnygweir',
    igFollowers: '950K',
    ttFollowers: '1.2M',
    totalFollowing: '2.2M+',
    imageUrl: '',
    bio: 'Two time Olympian and three time US National Champion in figure skating. NBC Olympics commentator and fashion icon.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Sports', 'Fashion', 'Comedy', 'LGBTQ+'],
    networks: ['NBC', 'Fox', 'VH1'],
  },

  // =======================================
  // CORE TIER (30 creators)
  // =======================================
  {
    id: 'bt-014',
    slug: 'nicole-polizzi',
    inviteSlug: 'np-invite-2026',
    name: 'Nicole "Snooki" Polizzi',
    tier: 'Core',
    priority: 14,
    genre: 'Reality TV/Fashion/Mom Life',
    credits: "Jersey Shore (MTV, 6 seasons). Snooki & JWoww. Jersey Shore Family Vacation. Nicole & Jionni's Shore Flip.",
    igHandle: '@snooki',
    igUrl: 'https://instagram.com/snooki',
    ttHandle: '@snooki',
    ttUrl: 'https://tiktok.com/@snooki',
    igFollowers: '14M',
    ttFollowers: '3.2M',
    totalFollowing: '17.2M+',
    imageUrl: '',
    bio: 'Reality television icon and original Jersey Shore cast member with over 17 million followers. Entrepreneur, New York Times bestselling author, and podcast host.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Parenting', 'Comedy'],
    networks: ['MTV'],
  },
  {
    id: 'bt-015',
    slug: 'phaedra-parks',
    inviteSlug: 'pp-invite-2026',
    name: 'Phaedra Parks',
    tier: 'Core',
    priority: 15,
    genre: 'Reality TV/Law/Entertainment',
    credits: 'The Real Housewives of Atlanta (Bravo). Married to Medicine. House of Villains winner.',
    igHandle: '@phaedraparks',
    igUrl: 'https://instagram.com/phaedraparks',
    ttHandle: '@phaedraparks',
    ttUrl: 'https://tiktok.com/@phaedraparks',
    igFollowers: '3.4M',
    ttFollowers: '800K',
    totalFollowing: '4.2M+',
    imageUrl: '',
    bio: 'Attorney, entrepreneur, and reality television star from The Real Housewives of Atlanta. Winner of House of Villains Season 1 and celebrated media personality.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Law', 'Entertainment', 'Lifestyle'],
    networks: ['Bravo', 'E!'],
  },
  {
    id: 'bt-016',
    slug: 'teresa-giudice',
    inviteSlug: 'tg-invite-2026',
    name: 'Teresa Giudice',
    tier: 'Core',
    priority: 16,
    genre: 'Reality TV/Fitness/Cooking',
    credits: 'The Real Housewives of New Jersey (Bravo, 14 seasons). Celebrity Apprentice. Dancing with the Stars.',
    igHandle: '@teresagiudice',
    igUrl: 'https://instagram.com/teresagiudice',
    ttHandle: '@teresagiudice',
    ttUrl: 'https://tiktok.com/@teresagiudice',
    igFollowers: '2.3M',
    ttFollowers: '600K',
    totalFollowing: '2.9M+',
    imageUrl: '',
    bio: 'OG cast member and longest running star of The Real Housewives of New Jersey. New York Times bestselling cookbook author and fitness entrepreneur.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fitness', 'Cooking', 'Lifestyle'],
    networks: ['Bravo', 'NBC'],
  },
  {
    id: 'bt-017',
    slug: 'bethenny-frankel',
    inviteSlug: 'bf-invite-2026',
    name: 'Bethenny Frankel',
    tier: 'Core',
    priority: 17,
    genre: 'Business/Reality TV/Philanthropy',
    credits: 'The Real Housewives of New York (Bravo). Bethenny Ever After. Shark Tank guest. The Big Shot with Bethenny.',
    igHandle: '@bethennyfrankel',
    igUrl: 'https://instagram.com/bethennyfrankel',
    ttHandle: '@bethennyfrankel',
    ttUrl: 'https://tiktok.com/@bethennyfrankel',
    igFollowers: '3M',
    ttFollowers: '1.5M',
    totalFollowing: '4.5M+',
    imageUrl: '',
    bio: "Self made mogul who sold Skinnygirl Cocktails for an estimated $100M+. Philanthropist, bestselling author, and one of reality television's most successful entrepreneurs.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Business', 'Reality TV', 'Philanthropy', 'Food'],
    networks: ['Bravo', 'HBO Max'],
  },
  {
    id: 'bt-018',
    slug: 'kenya-moore',
    inviteSlug: 'km-invite-2026',
    name: 'Kenya Moore',
    tier: 'Core',
    priority: 18,
    genre: 'Reality TV/Beauty/Fitness',
    credits: 'The Real Housewives of Atlanta (Bravo, 10+ seasons). Miss USA 1993. Dancing with the Stars.',
    igHandle: '@thekenyamoore',
    igUrl: 'https://instagram.com/thekenyamoore',
    ttHandle: '@thekenyamoore',
    ttUrl: 'https://tiktok.com/@thekenyamoore',
    igFollowers: '3.2M',
    ttFollowers: '300K',
    totalFollowing: '3.5M+',
    imageUrl: '',
    bio: 'Former Miss USA and longtime star of The Real Housewives of Atlanta. Actress, producer, entrepreneur, and Kenya Moore Hair Care founder.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Beauty', 'Fitness', 'Business'],
    networks: ['Bravo', 'ABC'],
  },
  {
    id: 'bt-019',
    slug: 'porsha-williams',
    inviteSlug: 'pw-invite-2026',
    name: 'Porsha Williams',
    tier: 'Core',
    priority: 19,
    genre: 'Reality TV/Activism/Family',
    credits: "The Real Housewives of Atlanta (Bravo). Porsha's Family Matters. Dish Nation. Celebrity Apprentice.",
    igHandle: '@porsha4real',
    igUrl: 'https://instagram.com/porsha4real',
    ttHandle: '@porsha4real',
    ttUrl: 'https://tiktok.com/@porsha4real',
    igFollowers: '7.4M',
    ttFollowers: '1M',
    totalFollowing: '8.4M+',
    imageUrl: '',
    bio: 'Reality television star, activist, and entrepreneur from The Real Housewives of Atlanta. Bestselling author and civil rights advocate.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Activism', 'Family', 'Lifestyle'],
    networks: ['Bravo', 'NBC'],
  },
  {
    id: 'bt-020',
    slug: 'heidi-montag',
    inviteSlug: 'hm-invite-2026',
    name: 'Heidi Montag',
    tier: 'Core',
    priority: 20,
    genre: 'Reality TV/Music/Fitness',
    credits: "The Hills (MTV, 6 seasons). Celebrity Big Brother. I'm a Celebrity Get Me Out of Here. Marriage Boot Camp.",
    igHandle: '@heidipratt',
    igUrl: 'https://instagram.com/heidipratt',
    ttHandle: '@heidipratt',
    ttUrl: 'https://tiktok.com/@heidipratt',
    igFollowers: '1.7M',
    ttFollowers: '1.8M',
    totalFollowing: '3.5M+',
    imageUrl: '',
    bio: 'Original cast member of The Hills and pop culture icon of the 2000s. Viral TikTok comeback star and music artist with a passionate fan base.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Music', 'Fitness', 'Fashion'],
    networks: ['MTV', 'Channel 5 UK'],
  },
  {
    id: 'bt-021',
    slug: 'spencer-pratt',
    inviteSlug: 'sp-invite-2026',
    name: 'Spencer Pratt',
    tier: 'Core',
    priority: 21,
    genre: 'Reality TV/Crystals/Comedy',
    credits: 'The Hills (MTV, 6 seasons). Celebrity Big Brother. The Spencer Pratt Show.',
    igHandle: '@spencerpratt',
    igUrl: 'https://instagram.com/spencerpratt',
    ttHandle: '@spencerpratt',
    ttUrl: 'https://tiktok.com/@spencerpratt',
    igFollowers: '1.5M',
    ttFollowers: '4.5M',
    totalFollowing: '6M+',
    imageUrl: '',
    bio: 'Reality TV personality and TikTok sensation known for his comedic content and crystal collection. Original cast member of The Hills with a massive digital following.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Comedy', 'Lifestyle', 'Entertainment'],
    networks: ['MTV', 'Channel 5 UK'],
  },
  {
    id: 'bt-022',
    slug: 'tamar-braxton',
    inviteSlug: 'tb-invite-2026',
    name: 'Tamar Braxton',
    tier: 'Core',
    priority: 22,
    genre: 'Music/Reality TV/Hosting',
    credits: 'Braxton Family Values (WE tv). Celebrity Big Brother winner. The Real (Fox). Tamar & Vince.',
    igHandle: '@tamarbraxton',
    igUrl: 'https://instagram.com/tamarbraxton',
    ttHandle: '@tamarbraxton',
    ttUrl: 'https://tiktok.com/@tamarbraxton',
    igFollowers: '5.2M',
    ttFollowers: '500K',
    totalFollowing: '5.7M+',
    imageUrl: '',
    bio: 'Grammy nominated singer and winner of Celebrity Big Brother Season 2. Star of Braxton Family Values and former co host of The Real.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Reality TV', 'Hosting', 'Entertainment'],
    networks: ['WE tv', 'Fox', 'CBS'],
  },
  {
    id: 'bt-023',
    slug: 'evelyn-lozada',
    inviteSlug: 'el-invite-2026',
    name: 'Evelyn Lozada',
    tier: 'Core',
    priority: 23,
    genre: 'Reality TV/Fashion/Lifestyle',
    credits: "Basketball Wives (VH1, multiple seasons). Livin' Lozada (OWN). Celebrity Fit Club.",
    igHandle: '@evelynlozada',
    igUrl: 'https://instagram.com/evelynlozada',
    ttHandle: '@evelynlozada',
    ttUrl: 'https://tiktok.com/@evelynlozada',
    igFollowers: '4.8M',
    ttFollowers: '600K',
    totalFollowing: '5.4M+',
    imageUrl: '',
    bio: 'Original Basketball Wives star and reality television mainstay across VH1 and OWN. Model, entrepreneur, and fashion influencer.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Lifestyle', 'Beauty'],
    networks: ['VH1', 'OWN'],
  },
  {
    id: 'bt-024',
    slug: 'tia-mowry',
    inviteSlug: 'tm-invite-2026',
    name: 'Tia Mowry',
    tier: 'Core',
    priority: 24,
    genre: 'Actress/Cooking/Family/Lifestyle',
    credits: 'Sister, Sister. Family Reunion (Netflix). Tia Mowry at Home (Cooking Channel). The Game.',
    igHandle: '@tiamowry',
    igUrl: 'https://instagram.com/tiamowry',
    ttHandle: '@tiamowry',
    ttUrl: 'https://tiktok.com/@tiamowry',
    igFollowers: '11.2M',
    ttFollowers: '3.1M',
    totalFollowing: '14.3M+',
    imageUrl: '',
    bio: 'Beloved actress from Sister, Sister and Family Reunion with over 14 million followers. Cookbook author, lifestyle content creator, and wellness advocate.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Cooking', 'Family', 'Lifestyle'],
    networks: ['Netflix', 'Cooking Channel', 'ABC'],
  },
  {
    id: 'bt-025',
    slug: 'sonja-morgan',
    inviteSlug: 'sm-invite-2026',
    name: 'Sonja Morgan',
    tier: 'Core',
    priority: 25,
    genre: 'Reality TV/Fashion/Lifestyle',
    credits: 'The Real Housewives of New York (Bravo, 13 seasons). RHONY Legacy. Crappie Lake.',
    igHandle: '@sonjatmorgan',
    igUrl: 'https://instagram.com/sonjatmorgan',
    ttHandle: '@sonjatmorgan',
    ttUrl: 'https://tiktok.com/@sonjatmorgan',
    igFollowers: '1.2M',
    ttFollowers: '250K',
    totalFollowing: '1.5M+',
    imageUrl: '',
    bio: 'Longtime fan favorite on The Real Housewives of New York City and Sonja by Sonja Morgan fashion founder. Known for her humor, hosting, and iconic one liners.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Lifestyle', 'Comedy'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-026',
    slug: 'luann-de-lesseps',
    inviteSlug: 'ldl-invite-2026',
    name: 'Luann de Lesseps',
    tier: 'Core',
    priority: 26,
    genre: 'Reality TV/Cabaret/Music',
    credits: 'The Real Housewives of New York (Bravo, 13 seasons). Ultimate Girls Trip. Cabaret residency.',
    igHandle: '@countessluann',
    igUrl: 'https://instagram.com/countessluann',
    ttHandle: '@countessluann',
    ttUrl: 'https://tiktok.com/@countessluann',
    igFollowers: '1.5M',
    ttFollowers: '350K',
    totalFollowing: '1.9M+',
    imageUrl: '',
    bio: "The Countess of Bravo, starring on RHONY since Season 1 and headlining a nationally touring cabaret show. Singer of \"Money Can't Buy You Class\" and bestselling author.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Music', 'Cabaret', 'Fashion'],
    networks: ['Bravo', 'Peacock'],
  },
  {
    id: 'bt-027',
    slug: 'erika-jayne',
    inviteSlug: 'ej-invite-2026',
    name: 'Erika Jayne',
    tier: 'Core',
    priority: 27,
    genre: 'Reality TV/Music/Dance/Fashion',
    credits: 'The Real Housewives of Beverly Hills (Bravo). XXpen$ive (Billboard #1). Dancing with the Stars. Chicago (Broadway).',
    igHandle: '@theprettymess',
    igUrl: 'https://instagram.com/theprettymess',
    ttHandle: '@theprettymess',
    ttUrl: 'https://tiktok.com/@theprettymess',
    igFollowers: '2.7M',
    ttFollowers: '400K',
    totalFollowing: '3.1M+',
    imageUrl: '',
    bio: 'Pop recording artist and star of The Real Housewives of Beverly Hills. Broadway actress, bestselling author, and Billboard charting performer.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Music', 'Dance', 'Fashion'],
    networks: ['Bravo', 'ABC'],
  },
  {
    id: 'bt-028',
    slug: 'adrienne-bailon',
    inviteSlug: 'ab-invite-2026',
    name: 'Adrienne Bailon',
    tier: 'Core',
    priority: 28,
    genre: 'Hosting/Music/Beauty/Lifestyle',
    credits: 'The Real (Fox, 8 seasons). The Cheetah Girls. I Can Do That.',
    igHandle: '@adriennebailon',
    igUrl: 'https://instagram.com/adriennebailon',
    ttHandle: '@adriennebailon',
    ttUrl: 'https://tiktok.com/@adriennebailon',
    igFollowers: '5.3M',
    ttFollowers: '800K',
    totalFollowing: '6.1M+',
    imageUrl: '',
    bio: 'Daytime Emmy winning co host of The Real and former Cheetah Girls member. Singer, actress, and beauty mogul with over 6 million followers.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Hosting', 'Music', 'Beauty', 'Lifestyle'],
    networks: ['Fox', 'Disney Channel'],
  },
  {
    id: 'bt-029',
    slug: 'kim-zolciak',
    inviteSlug: 'kz-invite-2026',
    name: 'Kim Zolciak',
    tier: 'Core',
    priority: 29,
    genre: 'Reality TV/Fashion/Music',
    credits: "The Real Housewives of Atlanta (Bravo, 5 seasons). Don't Be Tardy (Bravo, 8 seasons). Dancing with the Stars.",
    igHandle: '@kimzolciakbiermann',
    igUrl: 'https://instagram.com/kimzolciakbiermann',
    ttHandle: '@kimzolciakbiermann',
    ttUrl: 'https://tiktok.com/@kimzolciakbiermann',
    igFollowers: '3.2M',
    ttFollowers: '300K',
    totalFollowing: '3.5M+',
    imageUrl: '',
    bio: "Original Real Housewives of Atlanta cast member and star of the spinoff Don't Be Tardy. Singer of \"Tardy for the Party\" and entrepreneur.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Music', 'Lifestyle'],
    networks: ['Bravo', 'ABC'],
  },
  {
    id: 'bt-030',
    slug: 'savannah-chrisley',
    inviteSlug: 'sc-invite-2026',
    name: 'Savannah Chrisley',
    tier: 'Core',
    priority: 30,
    genre: 'Reality TV/Fashion/Podcast/Family',
    credits: 'Chrisley Knows Best (USA Network, 10 seasons). Growing Up Chrisley. Unlocked podcast.',
    igHandle: '@savannahchrisley',
    igUrl: 'https://instagram.com/savannahchrisley',
    ttHandle: '@savannahchrisley',
    ttUrl: 'https://tiktok.com/@savannahchrisley',
    igFollowers: '3.8M',
    ttFollowers: '900K',
    totalFollowing: '4.7M+',
    imageUrl: '',
    bio: 'Reality television star from Chrisley Knows Best and Growing Up Chrisley. Podcast host, beauty pageant winner, and advocate for criminal justice reform.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Podcast', 'Family'],
    networks: ['USA Network', 'E!'],
  },
  {
    id: 'bt-031',
    slug: 'brie-bella',
    inviteSlug: 'bb-invite-2026',
    name: 'Brie Bella',
    tier: 'Core',
    priority: 31,
    genre: 'Wrestling/Lifestyle/Wine/Family',
    credits: 'Total Bellas (E!). Total Divas (E!). WWE Divas Champion. The Bellas Podcast.',
    igHandle: '@thebriebella',
    igUrl: 'https://instagram.com/thebriebella',
    ttHandle: '@thebriebella',
    ttUrl: 'https://tiktok.com/@thebriebella',
    igFollowers: '9.6M',
    ttFollowers: '2.1M',
    totalFollowing: '11.7M+',
    imageUrl: '',
    bio: 'WWE Hall of Famer and star of Total Bellas and Total Divas. Entrepreneur, wine brand co founder, and podcast host with nearly 12 million followers.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Wrestling', 'Lifestyle', 'Wine', 'Family'],
    networks: ['E!', 'WWE Network'],
  },
  {
    id: 'bt-032',
    slug: 'nikki-bella',
    inviteSlug: 'nb-invite-2026',
    name: 'Nikki Bella',
    tier: 'Core',
    priority: 32,
    genre: 'Wrestling/Fashion/Wellness/Family',
    credits: "Total Bellas (E!). Total Divas (E!). America's Got Talent. Dancing with the Stars. WWE Divas Champion.",
    igHandle: '@nikkibella',
    igUrl: 'https://instagram.com/nikkibella',
    ttHandle: '@nikkibella',
    ttUrl: 'https://tiktok.com/@nikkibella',
    igFollowers: '10.6M',
    ttFollowers: '2.5M',
    totalFollowing: '13.1M+',
    imageUrl: '',
    bio: 'Two time WWE Divas Champion and WWE Hall of Famer with over 13 million followers. Star of Total Bellas, AGT judge, and co founder of Bonita Bonita Wine.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Wrestling', 'Fashion', 'Wellness', 'Family'],
    networks: ['E!', 'NBC', 'ABC', 'WWE Network'],
  },
  {
    id: 'bt-033',
    slug: 'dorinda-medley',
    inviteSlug: 'dm-invite-2026',
    name: 'Dorinda Medley',
    tier: 'Core',
    priority: 33,
    genre: 'Reality TV/Lifestyle/Fashion',
    credits: 'The Real Housewives of New York (Bravo, 6 seasons). Ultimate Girls Trip Season 2. Make It Nice podcast.',
    igHandle: '@dorindamedley',
    igUrl: 'https://instagram.com/dorindamedley',
    ttHandle: '@dorindamedley',
    ttUrl: 'https://tiktok.com/@dorindamedley',
    igFollowers: '800K',
    ttFollowers: '200K',
    totalFollowing: '1M+',
    imageUrl: '',
    bio: 'Fan favorite from The Real Housewives of New York known for the catchphrase "Make It Nice." Author, Blue Stone Manor host, and beloved Bravo personality.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Lifestyle', 'Fashion', 'Hosting'],
    networks: ['Bravo', 'Peacock'],
  },
  {
    id: 'bt-034',
    slug: 'brandi-glanville',
    inviteSlug: 'bg-invite-2026',
    name: 'Brandi Glanville',
    tier: 'Core',
    priority: 34,
    genre: 'Reality TV/Fashion/Podcast',
    credits: 'The Real Housewives of Beverly Hills (Bravo). Celebrity Big Brother. Celebrity Apprentice. Ultimate Girls Trip.',
    igHandle: '@brandiglanville',
    igUrl: 'https://instagram.com/brandiglanville',
    ttHandle: '@brandiglanville',
    ttUrl: 'https://tiktok.com/@brandiglanville',
    igFollowers: '830K',
    ttFollowers: '150K',
    totalFollowing: '980K+',
    imageUrl: '',
    bio: 'Former supermodel and Real Housewives of Beverly Hills star known for unfiltered honesty. Bestselling author, podcast host, and Celebrity Big Brother competitor.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Podcast', 'Modeling'],
    networks: ['Bravo', 'CBS', 'NBC', 'Peacock'],
  },
  {
    id: 'bt-035',
    slug: 'dr-paul-nassif',
    inviteSlug: 'pn-invite-2026',
    name: 'Dr. Paul Nassif',
    tier: 'Core',
    priority: 35,
    genre: 'Medical/Reality TV/Lifestyle',
    credits: 'Botched (E!, 8+ seasons). The Real Housewives of Beverly Hills. E! True Hollywood Story.',
    igHandle: '@drpaulnassif',
    igUrl: 'https://instagram.com/drpaulnassif',
    ttHandle: '@drpaulnassif',
    ttUrl: 'https://tiktok.com/@drpaulnassif',
    igFollowers: '2.2M',
    ttFollowers: '500K',
    totalFollowing: '2.7M+',
    imageUrl: '',
    bio: 'World renowned rhinoplasty surgeon and co star of Botched on E! for over eight seasons. Founder of NassifMD skincare and facial plastic surgery innovator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Medical', 'Reality TV', 'Lifestyle', 'Skincare'],
    networks: ['E!'],
  },
  {
    id: 'bt-036',
    slug: 'lisa-rinna',
    inviteSlug: 'lr-invite-2026',
    name: 'Lisa Rinna',
    tier: 'Core',
    priority: 36,
    genre: 'Reality TV/Acting/Fashion/Beauty',
    credits: 'The Real Housewives of Beverly Hills (Bravo, 8 seasons). Days of Our Lives. Melrose Place. Rinna Beauty.',
    igHandle: '@lisarinna',
    igUrl: 'https://instagram.com/lisarinna',
    ttHandle: '@lisarinna',
    ttUrl: 'https://tiktok.com/@lisarinna',
    igFollowers: '3.6M',
    ttFollowers: '1.2M',
    totalFollowing: '4.8M+',
    imageUrl: '',
    bio: "Actress, entrepreneur, and pop culture fixture known for RHOBH and Days of Our Lives. Founder of Rinna Beauty and one of daytime television's most recognizable faces.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Acting', 'Fashion', 'Beauty'],
    networks: ['Bravo', 'NBC', 'Fox'],
  },
  {
    id: 'bt-037',
    slug: 'ross-mathews',
    inviteSlug: 'rm-invite-2026',
    name: 'Ross Mathews',
    tier: 'Core',
    priority: 37,
    genre: 'Hosting/Comedy/LGBTQ+',
    credits: "RuPaul's Drag Race (judge, VH1/MTV). The Tonight Show with Jay Leno. Hello Ross (E!). Celebrity Big Brother.",
    igHandle: '@helloross',
    igUrl: 'https://instagram.com/helloross',
    ttHandle: '@helloross',
    ttUrl: 'https://tiktok.com/@helloross',
    igFollowers: '750K',
    ttFollowers: '300K',
    totalFollowing: '1.1M+',
    imageUrl: '',
    bio: "Permanent judge on RuPaul's Drag Race and beloved television personality. Former Tonight Show correspondent, bestselling author, and Emmy winning producer.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Hosting', 'Comedy', 'LGBTQ+', 'Entertainment'],
    networks: ['VH1', 'MTV', 'E!', 'NBC'],
  },
  {
    id: 'bt-038',
    slug: 'bob-harper',
    inviteSlug: 'bh-invite-2026',
    name: 'Bob Harper',
    tier: 'Core',
    priority: 38,
    genre: 'Fitness/Health/Wellness',
    credits: 'The Biggest Loser (NBC, 17 seasons). Host and trainer. Bestselling fitness author.',
    igHandle: '@bobharper',
    igUrl: 'https://instagram.com/bobharper',
    ttHandle: '@bobharper',
    ttUrl: 'https://tiktok.com/@bobharper',
    igFollowers: '700K',
    ttFollowers: '100K',
    totalFollowing: '800K+',
    imageUrl: '',
    bio: 'Celebrity fitness trainer and host of The Biggest Loser for 17 seasons on NBC. Bestselling author and heart attack survivor turned wellness advocate.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fitness', 'Health', 'Wellness', 'Motivation'],
    networks: ['NBC'],
  },
  {
    id: 'bt-039',
    slug: 'jill-zarin',
    inviteSlug: 'jz-invite-2026',
    name: 'Jill Zarin',
    tier: 'Core',
    priority: 39,
    genre: 'Reality TV/Fashion/Business',
    credits: 'The Real Housewives of New York (Bravo, 4 seasons). Ultimate Girls Trip. Jill Zarin Rugs.',
    igHandle: '@jillzarin',
    igUrl: 'https://instagram.com/jillzarin',
    ttHandle: '@jillzarin',
    ttUrl: 'https://tiktok.com/@jillzarin',
    igFollowers: '500K',
    ttFollowers: '150K',
    totalFollowing: '650K+',
    imageUrl: '',
    bio: 'Original cast member of The Real Housewives of New York and home decor entrepreneur. Philanthropy advocate and Jill Zarin Rugs founder.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Business', 'Home Decor'],
    networks: ['Bravo', 'Peacock'],
  },
  {
    id: 'bt-040',
    slug: 'tori-spelling',
    inviteSlug: 'ts-invite-2026',
    name: 'Tori Spelling',
    tier: 'Core',
    priority: 40,
    genre: 'Acting/Reality TV/Parenting',
    credits: 'Beverly Hills 90210 (Fox, 10 seasons). True Tori. Tori & Dean: Inn Love. Mystery Girls.',
    igHandle: '@torispelling',
    igUrl: 'https://instagram.com/torispelling',
    ttHandle: '@torispelling',
    ttUrl: 'https://tiktok.com/@torispelling',
    igFollowers: '2.1M',
    ttFollowers: '500K',
    totalFollowing: '2.6M+',
    imageUrl: '',
    bio: 'Actress and pop culture icon best known for a decade on Beverly Hills 90210. Author of six bestselling books and beloved reality television personality.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Reality TV', 'Parenting', 'Lifestyle'],
    networks: ['Fox', 'VH1', 'Oxygen'],
  },
  {
    id: 'bt-041',
    slug: 'kathryn-dennis',
    inviteSlug: 'kd-invite-2026',
    name: 'Kathryn Dennis',
    tier: 'Core',
    priority: 41,
    genre: 'Reality TV/Fashion/Art',
    credits: 'Southern Charm (Bravo, 8 seasons). Southern Charm fan favorite.',
    igHandle: '@kathryndennis',
    igUrl: 'https://instagram.com/kathryndennis',
    ttHandle: '@kathryndennis',
    ttUrl: 'https://tiktok.com/@kathryndennis',
    igFollowers: '550K',
    ttFollowers: '100K',
    totalFollowing: '650K+',
    imageUrl: '',
    bio: 'Original cast member and breakout star of Southern Charm on Bravo. Artist, model, and Charleston socialite.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Art', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-042',
    slug: 'teddi-mellencamp',
    inviteSlug: 'tme-invite-2026',
    name: 'Teddi Mellencamp',
    tier: 'Core',
    priority: 42,
    genre: 'Reality TV/Fitness/Wellness/Podcast',
    credits: 'The Real Housewives of Beverly Hills (Bravo, 3 seasons). Two Ts in a Pod podcast.',
    igHandle: '@teddimellencamp',
    igUrl: 'https://instagram.com/teddimellencamp',
    ttHandle: '@teddimellencamp',
    ttUrl: 'https://tiktok.com/@teddimellencamp',
    igFollowers: '850K',
    ttFollowers: '150K',
    totalFollowing: '1M+',
    imageUrl: '',
    bio: 'Former Real Housewives of Beverly Hills cast member and co host of the Two Ts in a Pod podcast. Accountability coach and ALL IN by Teddi founder.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fitness', 'Wellness', 'Podcast'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-043',
    slug: 'chrishell-stause',
    inviteSlug: 'cs-invite-2026',
    name: 'Chrishell Stause',
    tier: 'Core',
    priority: 43,
    genre: 'Real Estate/Reality TV/Acting',
    credits: 'Selling Sunset (Netflix, 7 seasons). Dancing with the Stars. Days of Our Lives. All My Children.',
    igHandle: '@chrishell.stause',
    igUrl: 'https://instagram.com/chrishell.stause',
    ttHandle: '@chrishellstause',
    ttUrl: 'https://tiktok.com/@chrishellstause',
    igFollowers: '3.8M',
    ttFollowers: '2.3M',
    totalFollowing: '6.1M+',
    imageUrl: '',
    bio: 'Star of Netflix hit Selling Sunset and luxury real estate agent at The Oppenheim Group. Former soap opera actress and Dancing with the Stars competitor.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Real Estate', 'Reality TV', 'Acting', 'Lifestyle'],
    networks: ['Netflix', 'ABC', 'NBC'],
  },

  // =======================================
  // RISING TIER (31 creators)
  // =======================================
  {
    id: 'bt-044',
    slug: 'paige-desorbo',
    inviteSlug: 'pd-invite-2026',
    name: 'Paige DeSorbo',
    tier: 'Rising',
    priority: 44,
    genre: 'Reality TV/Fashion/Podcast',
    credits: 'Summer House (Bravo, 8 seasons). Winter House. Giggly Squad podcast.',
    igHandle: '@paigedesorbo',
    igUrl: 'https://instagram.com/paigedesorbo',
    ttHandle: '@paigedesorbo',
    ttUrl: 'https://tiktok.com/@paigedesorbo',
    igFollowers: '1.3M',
    ttFollowers: '700K',
    totalFollowing: '2M+',
    imageUrl: '',
    bio: "Fashion influencer and star of Bravo's Summer House and Winter House. Co host of the Giggly Squad podcast and Amazon fashion collaborator.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Podcast', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-045',
    slug: 'lindsay-hubbard',
    inviteSlug: 'lh-invite-2026',
    name: 'Lindsay Hubbard',
    tier: 'Rising',
    priority: 45,
    genre: 'Reality TV/PR/Lifestyle',
    credits: 'Summer House (Bravo, 8 seasons). Winter House. Hubb House PR founder.',
    igHandle: '@lindshubbs',
    igUrl: 'https://instagram.com/lindshubbs',
    ttHandle: '@lindshubbs',
    ttUrl: 'https://tiktok.com/@lindshubbs',
    igFollowers: '550K',
    ttFollowers: '150K',
    totalFollowing: '700K+',
    imageUrl: '',
    bio: 'Original cast member of Summer House on Bravo and founder of Hubb House PR. Public relations executive and new mom sharing her journey on and off screen.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'PR', 'Lifestyle', 'Parenting'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-046',
    slug: 'ciara-miller',
    inviteSlug: 'cmi-invite-2026',
    name: 'Ciara Miller',
    tier: 'Rising',
    priority: 46,
    genre: 'Reality TV/Nursing/Fitness/Fashion',
    credits: 'Summer House (Bravo, 5 seasons). Winter House.',
    igHandle: '@ciaramiller',
    igUrl: 'https://instagram.com/ciaramiller',
    ttHandle: '@ciaramiller',
    ttUrl: 'https://tiktok.com/@ciaramiller',
    igFollowers: '400K',
    ttFollowers: '100K',
    totalFollowing: '500K+',
    imageUrl: '',
    bio: "Model, registered nurse, and cast member on Bravo's Summer House. Fashion and fitness content creator breaking out as a brand partnership favorite.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Nursing', 'Fitness', 'Fashion'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-047',
    slug: 'craig-conover',
    inviteSlug: 'cc-invite-2026',
    name: 'Craig Conover',
    tier: 'Rising',
    priority: 47,
    genre: 'Reality TV/Sewing/Entrepreneurship',
    credits: 'Southern Charm (Bravo, 9 seasons). Winter House. Pillow talk podcast. Sewing Down South founder.',
    igHandle: '@caconover',
    igUrl: 'https://instagram.com/caconover',
    ttHandle: '@craigconover',
    ttUrl: 'https://tiktok.com/@craigconover',
    igFollowers: '700K',
    ttFollowers: '200K',
    totalFollowing: '900K+',
    imageUrl: '',
    bio: 'Star of Southern Charm and Winter House, and founder of the lifestyle brand Sewing Down South. Attorney turned entrepreneur and Bravo fan favorite.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Entrepreneurship', 'Lifestyle', 'Home Decor'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-048',
    slug: 'austen-kroll',
    inviteSlug: 'ak-invite-2026',
    name: 'Austen Kroll',
    tier: 'Rising',
    priority: 48,
    genre: 'Reality TV/Beer/Lifestyle',
    credits: 'Southern Charm (Bravo, 8 seasons). Winter House. Trop Hop beer brand.',
    igHandle: '@austenkroll',
    igUrl: 'https://instagram.com/austenkroll',
    ttHandle: '@austenkroll',
    ttUrl: 'https://tiktok.com/@austenkroll',
    igFollowers: '450K',
    ttFollowers: '100K',
    totalFollowing: '550K+',
    imageUrl: '',
    bio: "Cast member on Bravo's Southern Charm and Winter House and craft beer entrepreneur. Known for his laid back personality and Trop Hop brand.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Beer', 'Lifestyle', 'Food'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-049',
    slug: 'madison-lecroy',
    inviteSlug: 'ml-invite-2026',
    name: 'Madison LeCroy',
    tier: 'Rising',
    priority: 49,
    genre: 'Reality TV/Beauty/Hair',
    credits: 'Southern Charm (Bravo, 5 seasons). Madison LeCroy Hair.',
    igHandle: '@madisonlecroy',
    igUrl: 'https://instagram.com/madisonlecroy',
    ttHandle: '@madisonlecroy',
    ttUrl: 'https://tiktok.com/@madisonlecroy',
    igFollowers: '600K',
    ttFollowers: '250K',
    totalFollowing: '850K+',
    imageUrl: '',
    bio: "Hair stylist, entrepreneur, and Southern Charm breakout star. Founder of Madison LeCroy Hair and one of Bravo's most talked about personalities.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Beauty', 'Hair', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-050',
    slug: 'lala-kent',
    inviteSlug: 'lk-invite-2026',
    name: 'Lala Kent',
    tier: 'Rising',
    priority: 50,
    genre: 'Reality TV/Beauty/Podcast',
    credits: 'Vanderpump Rules (Bravo, 11 seasons). The Valley. Give Them Lala podcast. Give Them Lala Beauty.',
    igHandle: '@lalakent',
    igUrl: 'https://instagram.com/lalakent',
    ttHandle: '@lalakent',
    ttUrl: 'https://tiktok.com/@lalakent',
    igFollowers: '1.7M',
    ttFollowers: '600K',
    totalFollowing: '2.3M+',
    imageUrl: '',
    bio: "Vanderpump Rules star and Give Them Lala Beauty founder. Bestselling author, podcast host, and now starring in Bravo's The Valley.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Beauty', 'Podcast', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-051',
    slug: 'ariana-madix',
    inviteSlug: 'am-invite-2026',
    name: 'Ariana Madix',
    tier: 'Rising',
    priority: 51,
    genre: 'Reality TV/Hosting/Acting/Fashion',
    credits: 'Vanderpump Rules (Bravo, 11 seasons). Love Island USA host (Peacock). Dancing with the Stars. Chicago (Broadway).',
    igHandle: '@arianamadix',
    igUrl: 'https://instagram.com/arianamadix',
    ttHandle: '@arianamadix',
    ttUrl: 'https://tiktok.com/@arianamadix',
    igFollowers: '1.8M',
    ttFollowers: '1.5M',
    totalFollowing: '3.3M+',
    imageUrl: '',
    bio: 'Vanderpump Rules star turned cultural moment and host of Love Island USA on Peacock. Broadway actress (Chicago), DWTS competitor, and brand partnership powerhouse.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Hosting', 'Acting', 'Fashion'],
    networks: ['Bravo', 'Peacock', 'ABC'],
  },
  {
    id: 'bt-052',
    slug: 'tom-sandoval',
    inviteSlug: 'tsa-invite-2026',
    name: 'Tom Sandoval',
    tier: 'Rising',
    priority: 52,
    genre: 'Reality TV/Music/Bars',
    credits: "Vanderpump Rules (Bravo, 11 seasons). Special Forces: World's Toughest Test. Tom Tom co owner. The Masked Singer.",
    igHandle: '@tomsandoval1',
    igUrl: 'https://instagram.com/tomsandoval1',
    ttHandle: '@tomsandoval1',
    ttUrl: 'https://tiktok.com/@tomsandoval1',
    igFollowers: '700K',
    ttFollowers: '400K',
    totalFollowing: '1.1M+',
    imageUrl: '',
    bio: 'Vanderpump Rules original cast member and one of the most talked about reality TV figures. Musician, bar co owner, and lead singer of his cover band.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Music', 'Bars', 'Entertainment'],
    networks: ['Bravo', 'Fox'],
  },
  {
    id: 'bt-053',
    slug: 'scheana-shay',
    inviteSlug: 'ssh-invite-2026',
    name: 'Scheana Shay',
    tier: 'Rising',
    priority: 53,
    genre: 'Reality TV/Music/Parenting',
    credits: 'Vanderpump Rules (Bravo, 11 seasons). Scheananigans podcast. Music artist.',
    igHandle: '@scheana',
    igUrl: 'https://instagram.com/scheana',
    ttHandle: '@scheana',
    ttUrl: 'https://tiktok.com/@scheana',
    igFollowers: '1.3M',
    ttFollowers: '600K',
    totalFollowing: '1.9M+',
    imageUrl: '',
    bio: 'Original cast member of Vanderpump Rules and host of the Scheananigans podcast. Singer, content creator, and mom sharing her life with nearly 2 million followers.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Music', 'Parenting', 'Podcast'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-054',
    slug: 'katie-maloney',
    inviteSlug: 'kma-invite-2026',
    name: 'Katie Maloney',
    tier: 'Rising',
    priority: 54,
    genre: 'Reality TV/Food/Entrepreneurship',
    credits: 'Vanderpump Rules (Bravo, 11 seasons). Something About Her sandwich shop co founder.',
    igHandle: '@musickillskate',
    igUrl: 'https://instagram.com/musickillskate',
    ttHandle: '@musickillskate',
    ttUrl: 'https://tiktok.com/@musickillskate',
    igFollowers: '650K',
    ttFollowers: '200K',
    totalFollowing: '850K+',
    imageUrl: '',
    bio: 'Vanderpump Rules original cast member and co founder of Something About Her sandwich shop. Podcast host, food entrepreneur, and fan favorite.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Food', 'Entrepreneurship', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-055',
    slug: 'james-kennedy',
    inviteSlug: 'jk-invite-2026',
    name: 'James Kennedy',
    tier: 'Rising',
    priority: 55,
    genre: 'Reality TV/DJ/Music',
    credits: 'Vanderpump Rules (Bravo, 11 seasons). DJ James Kennedy residency.',
    igHandle: '@itsjameskennedy',
    igUrl: 'https://instagram.com/itsjameskennedy',
    ttHandle: '@itsjameskennedy',
    ttUrl: 'https://tiktok.com/@itsjameskennedy',
    igFollowers: '550K',
    ttFollowers: '300K',
    totalFollowing: '850K+',
    imageUrl: '',
    bio: 'DJ, music producer, and Vanderpump Rules cast member known as the "White Kanye." Touring DJ with residencies in Las Vegas and Los Angeles.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'DJ', 'Music', 'Entertainment'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-056',
    slug: 'malia-white',
    inviteSlug: 'mw-invite-2026',
    name: 'Malia White',
    tier: 'Rising',
    priority: 56,
    genre: 'Reality TV/Yachting/Travel',
    credits: 'Below Deck Mediterranean (Bravo, 4 seasons). Bosun and deckhand.',
    igHandle: '@maliawhite',
    igUrl: 'https://instagram.com/maliawhite',
    ttHandle: '@maliawhite',
    ttUrl: 'https://tiktok.com/@maliawhite',
    igFollowers: '350K',
    ttFollowers: '100K',
    totalFollowing: '450K+',
    imageUrl: '',
    bio: "Bosun on Below Deck Mediterranean and professional yacht crew member. Adventure traveler, diver, and one of the Below Deck franchise's most popular cast members.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Yachting', 'Travel', 'Adventure'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-057',
    slug: 'hannah-berner',
    inviteSlug: 'hb-invite-2026',
    name: 'Hannah Berner',
    tier: 'Rising',
    priority: 57,
    genre: 'Comedy/Reality TV/Podcast',
    credits: 'Summer House (Bravo, 5 seasons). Berning in Hell podcast. Stand up comedy specials.',
    igHandle: '@berrrrna',
    igUrl: 'https://instagram.com/berrrrna',
    ttHandle: '@berrrrna',
    ttUrl: 'https://tiktok.com/@berrrrna',
    igFollowers: '700K',
    ttFollowers: '500K',
    totalFollowing: '1.2M+',
    imageUrl: '',
    bio: 'Stand up comedian and former Summer House cast member selling out shows nationwide. Host of the Berning in Hell podcast and viral comedy content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Comedy', 'Reality TV', 'Podcast', 'Entertainment'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-058',
    slug: 'jax-taylor',
    inviteSlug: 'jt-invite-2026',
    name: 'Jax Taylor',
    tier: 'Rising',
    priority: 58,
    genre: 'Reality TV/Bars/Lifestyle',
    credits: "Vanderpump Rules (Bravo, 8 seasons). The Valley (Bravo). Jax's Studio City bar.",
    igHandle: '@mrjaxtaylor',
    igUrl: 'https://instagram.com/mrjaxtaylor',
    ttHandle: '@mrjaxtaylor',
    ttUrl: 'https://tiktok.com/@mrjaxtaylor',
    igFollowers: '1.2M',
    ttFollowers: '300K',
    totalFollowing: '1.5M+',
    imageUrl: '',
    bio: "Original Vanderpump Rules star and lead of Bravo's The Valley. Self proclaimed \"Number One Guy in the Group\" and reality television personality.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Bars', 'Lifestyle', 'Entertainment'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-059',
    slug: 'brittany-cartwright',
    inviteSlug: 'bc-invite-2026',
    name: 'Brittany Cartwright',
    tier: 'Rising',
    priority: 59,
    genre: 'Reality TV/Family/Lifestyle',
    credits: 'Vanderpump Rules (Bravo, 6 seasons). The Valley (Bravo). Jenny Craig ambassador.',
    igHandle: '@brittanycartwright',
    igUrl: 'https://instagram.com/brittanycartwright',
    ttHandle: '@brittanycartwright',
    ttUrl: 'https://tiktok.com/@brittanycartwright',
    igFollowers: '1.5M',
    ttFollowers: '400K',
    totalFollowing: '1.9M+',
    imageUrl: '',
    bio: "Vanderpump Rules alum and star of The Valley on Bravo. Kentucky native, mom, and one of reality television's most relatable personalities.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Family', 'Lifestyle', 'Parenting'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-060',
    slug: 'gabby-windey',
    inviteSlug: 'gw-invite-2026',
    name: 'Gabby Windey',
    tier: 'Rising',
    priority: 60,
    genre: 'Reality TV/Dance/Lifestyle',
    credits: 'The Bachelorette Season 19 (ABC). Dancing with the Stars. Former Denver Broncos cheerleader.',
    igHandle: '@gabby.windey',
    igUrl: 'https://instagram.com/gabby.windey',
    ttHandle: '@gabbywindey',
    ttUrl: 'https://tiktok.com/@gabbywindey',
    igFollowers: '800K',
    ttFollowers: '200K',
    totalFollowing: '1M+',
    imageUrl: '',
    bio: 'Bachelorette Season 19 lead and Dancing with the Stars finalist. Former ICU nurse, Denver Broncos cheerleader, and emerging lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Dance', 'Lifestyle', 'Wellness'],
    networks: ['ABC'],
  },
  {
    id: 'bt-061',
    slug: 'tyler-cameron',
    inviteSlug: 'tc-invite-2026',
    name: 'Tyler Cameron',
    tier: 'Rising',
    priority: 61,
    genre: 'Reality TV/Modeling/Real Estate',
    credits: 'The Bachelorette Season 15 (ABC). Going Home with Tyler Cameron (Amazon). Model.',
    igHandle: '@tylerjcameron3',
    igUrl: 'https://instagram.com/tylerjcameron3',
    ttHandle: '@tylerjcameron3',
    ttUrl: 'https://tiktok.com/@tylerjcameron3',
    igFollowers: '2.4M',
    ttFollowers: '600K',
    totalFollowing: '3M+',
    imageUrl: '',
    bio: "Bachelorette Season 15 runner up, model, and reality television personality. Star of Amazon's Going Home with Tyler Cameron and real estate entrepreneur.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Modeling', 'Real Estate', 'Fitness'],
    networks: ['ABC', 'Amazon Prime'],
  },
  {
    id: 'bt-062',
    slug: 'matt-james',
    inviteSlug: 'mj-invite-2026',
    name: 'Matt James',
    tier: 'Rising',
    priority: 62,
    genre: 'Reality TV/Fitness/Real Estate',
    credits: 'The Bachelor Season 25 (ABC). Dancing with the Stars. First Black Bachelor lead.',
    igHandle: '@mattjames919',
    igUrl: 'https://instagram.com/mattjames919',
    ttHandle: '@mattjames919',
    ttUrl: 'https://tiktok.com/@mattjames919',
    igFollowers: '1.1M',
    ttFollowers: '300K',
    totalFollowing: '1.4M+',
    imageUrl: '',
    bio: 'First Black lead of The Bachelor (Season 25) and philanthropist. Real estate professional, fitness enthusiast, and ABC Food Tours co founder.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fitness', 'Real Estate', 'Philanthropy'],
    networks: ['ABC'],
  },
  {
    id: 'bt-063',
    slug: 'tayshia-adams',
    inviteSlug: 'ta-invite-2026',
    name: 'Tayshia Adams',
    tier: 'Rising',
    priority: 63,
    genre: 'Reality TV/Hosting/Lifestyle',
    credits: 'The Bachelorette Season 16 (ABC). Bachelor in Paradise. The Bachelorette co host. Click Bait podcast.',
    igHandle: '@tayshia',
    igUrl: 'https://instagram.com/tayshia',
    ttHandle: '@tayshiaadams',
    ttUrl: 'https://tiktok.com/@tayshiaadams',
    igFollowers: '2.5M',
    ttFollowers: '400K',
    totalFollowing: '2.9M+',
    imageUrl: '',
    bio: 'Bachelorette Season 16 lead and former co host of The Bachelorette. Podcast host, brand ambassador, and sought after lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Hosting', 'Lifestyle', 'Beauty'],
    networks: ['ABC'],
  },
  {
    id: 'bt-064',
    slug: 'rachel-lindsay',
    inviteSlug: 'rl-invite-2026',
    name: 'Rachel Lindsay',
    tier: 'Rising',
    priority: 64,
    genre: 'Reality TV/Journalism/Law',
    credits: 'The Bachelorette Season 13 (ABC). Extra correspondent. Higher Learning podcast (The Ringer).',
    igHandle: '@therachlindsay',
    igUrl: 'https://instagram.com/therachlindsay',
    ttHandle: '@therachlindsay',
    ttUrl: 'https://tiktok.com/@therachlindsay',
    igFollowers: '1.1M',
    ttFollowers: '200K',
    totalFollowing: '1.3M+',
    imageUrl: '',
    bio: 'First Black Bachelorette (Season 13), attorney, and Extra correspondent. Podcast host, media commentator, and advocate for diversity in entertainment.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Journalism', 'Law', 'Advocacy'],
    networks: ['ABC', 'Extra'],
  },
  {
    id: 'bt-065',
    slug: 'charity-lawson',
    inviteSlug: 'cl-invite-2026',
    name: 'Charity Lawson',
    tier: 'Rising',
    priority: 65,
    genre: 'Reality TV/Dance/Lifestyle',
    credits: 'The Bachelorette Season 20 (ABC). Dancing with the Stars Season 32.',
    igHandle: '@charitylawson',
    igUrl: 'https://instagram.com/charitylawson',
    ttHandle: '@charitylawson',
    ttUrl: 'https://tiktok.com/@charitylawson',
    igFollowers: '500K',
    ttFollowers: '150K',
    totalFollowing: '650K+',
    imageUrl: '',
    bio: 'Bachelorette Season 20 lead and Dancing with the Stars Season 32 competitor. Child and family therapist turned reality star and lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Dance', 'Lifestyle', 'Wellness'],
    networks: ['ABC'],
  },
  {
    id: 'bt-066',
    slug: 'kyle-cooke',
    inviteSlug: 'kc-invite-2026',
    name: 'Kyle Cooke',
    tier: 'Rising',
    priority: 66,
    genre: 'Reality TV/Entrepreneurship/Spirits',
    credits: 'Summer House (Bravo, 8 seasons). Winter House. Loverboy founder and CEO.',
    igHandle: '@kylecooke',
    igUrl: 'https://instagram.com/kylecooke',
    ttHandle: '@kylecooke',
    ttUrl: 'https://tiktok.com/@kylecooke',
    igFollowers: '350K',
    ttFollowers: '100K',
    totalFollowing: '450K+',
    imageUrl: '',
    bio: 'Founder and CEO of Loverboy, the lifestyle beverage brand, and original Summer House cast member. Serial entrepreneur and Bravo personality.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Entrepreneurship', 'Spirits', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-067',
    slug: 'amanda-batula',
    inviteSlug: 'aba-invite-2026',
    name: 'Amanda Batula',
    tier: 'Rising',
    priority: 67,
    genre: 'Reality TV/Design/Fashion',
    credits: 'Summer House (Bravo, 8 seasons). Winter House. Loverboy creative director.',
    igHandle: '@amandabatula',
    igUrl: 'https://instagram.com/amandabatula',
    ttHandle: '@amandabatula',
    ttUrl: 'https://tiktok.com/@amandabatula',
    igFollowers: '400K',
    ttFollowers: '100K',
    totalFollowing: '500K+',
    imageUrl: '',
    bio: 'Graphic designer, creative director of Loverboy, and Summer House cast member on Bravo. Fashion and home content creator with a growing digital following.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Design', 'Fashion', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-068',
    slug: 'chanel-ayan',
    inviteSlug: 'ca-invite-2026',
    name: 'Chanel Ayan',
    tier: 'Rising',
    priority: 68,
    genre: 'Reality TV/Modeling/Fashion',
    credits: 'The Real Housewives of Dubai (Bravo, 2 seasons). International supermodel.',
    igHandle: '@chanelayan',
    igUrl: 'https://instagram.com/chanelayan',
    ttHandle: '@chanelayan',
    ttUrl: 'https://tiktok.com/@chanelayan',
    igFollowers: '700K',
    ttFollowers: '200K',
    totalFollowing: '900K+',
    imageUrl: '',
    bio: 'International supermodel and breakout star of The Real Housewives of Dubai. First Somali and Kenyan supermodel to appear on a Bravo franchise.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Modeling', 'Fashion', 'Beauty'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-069',
    slug: 'nene-leakes',
    inviteSlug: 'nl-invite-2026',
    name: 'Nene Leakes',
    tier: 'Rising',
    priority: 69,
    genre: 'Reality TV/Acting/Comedy',
    credits: 'The Real Housewives of Atlanta (Bravo, 10 seasons). Glee (Fox). The New Normal (NBC). Broadway (Chicago).',
    igHandle: '@neneleakes',
    igUrl: 'https://instagram.com/neneleakes',
    ttHandle: '@neneleakes',
    ttUrl: 'https://tiktok.com/@neneleakes',
    igFollowers: '4.2M',
    ttFollowers: '800K',
    totalFollowing: '5M+',
    imageUrl: '',
    bio: 'Original Real Housewives of Atlanta star and reality television icon. Broadway actress (Chicago), Glee recurring cast member, and entrepreneur.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Acting', 'Comedy', 'Entertainment'],
    networks: ['Bravo', 'Fox', 'NBC'],
  },
  {
    id: 'bt-070',
    slug: 'quad-webb',
    inviteSlug: 'qw-invite-2026',
    name: 'Quad Webb',
    tier: 'Rising',
    priority: 70,
    genre: 'Reality TV/Fashion/Hosting',
    credits: 'Married to Medicine (Bravo, 10 seasons). Quad Webb brand. Sister Circle (TVOne host).',
    igHandle: '@quadwebb',
    igUrl: 'https://instagram.com/quadwebb',
    ttHandle: '@quadwebb',
    ttUrl: 'https://tiktok.com/@quadwebb',
    igFollowers: '900K',
    ttFollowers: '200K',
    totalFollowing: '1.1M+',
    imageUrl: '',
    bio: 'Original Married to Medicine cast member and former talk show host of Sister Circle on TVOne. Fashion designer, philanthropist, and Bravo personality.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Fashion', 'Hosting', 'Philanthropy'],
    networks: ['Bravo', 'TVOne'],
  },
  {
    id: 'bt-071',
    slug: 'dr-heavenly-kimes',
    inviteSlug: 'dhk-invite-2026',
    name: 'Dr. Heavenly Kimes',
    tier: 'Rising',
    priority: 71,
    genre: 'Reality TV/Dental/Business',
    credits: 'Married to Medicine (Bravo, 10 seasons). Heavenly Dental. YouTube personality.',
    igHandle: '@drheavenly',
    igUrl: 'https://instagram.com/drheavenly',
    ttHandle: '@drheavenly',
    ttUrl: 'https://tiktok.com/@drheavenly',
    igFollowers: '1.4M',
    ttFollowers: '500K',
    totalFollowing: '1.9M+',
    imageUrl: '',
    bio: 'Dentist, entrepreneur, and fan favorite on Married to Medicine. Bestselling author, YouTube personality, and owner of a multi location dental practice.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Dental', 'Business', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-072',
    slug: 'garcelle-beauvais',
    inviteSlug: 'gb-invite-2026',
    name: 'Garcelle Beauvais',
    tier: 'Rising',
    priority: 72,
    genre: 'Reality TV/Acting/Hosting',
    credits: 'The Real Housewives of Beverly Hills (Bravo, 5 seasons). Coming to America. NYPD Blue. The Jamie Foxx Show. The Real (co host).',
    igHandle: '@garcelle',
    igUrl: 'https://instagram.com/garcelle',
    ttHandle: '@garcellebeauvais',
    ttUrl: 'https://tiktok.com/@garcellebeauvais',
    igFollowers: '1.7M',
    ttFollowers: '300K',
    totalFollowing: '2M+',
    imageUrl: '',
    bio: 'Haitian American actress with decades of film and television credits including Coming to America and NYPD Blue. Current RHOBH cast member and former co host of The Real.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Acting', 'Hosting', 'Fashion'],
    networks: ['Bravo', 'Fox', 'ABC'],
  },
  {
    id: 'bt-073',
    slug: 'claudia-oshry',
    inviteSlug: 'co-invite-2026',
    name: 'Claudia Oshry',
    tier: 'Rising',
    priority: 73,
    genre: 'Comedy/Podcast/Lifestyle',
    credits: 'The Morning Toast podcast. The Toast live tour. Bravo adjacent personality. Girl With No Job brand.',
    igHandle: '@girlwithnojob',
    igUrl: 'https://instagram.com/girlwithnojob',
    ttHandle: '@girlwithnojob',
    ttUrl: 'https://tiktok.com/@girlwithnojob',
    igFollowers: '450K',
    ttFollowers: '200K',
    totalFollowing: '650K+',
    imageUrl: '',
    bio: 'Comedian, podcaster, and creator behind the Girl With No Job brand. Co host of The Morning Toast and live touring stand up comedian.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Comedy', 'Podcast', 'Lifestyle', 'Entertainment'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-074',
    slug: 'kenya-duke',
    inviteSlug: 'kdu-invite-2026',
    name: 'Kenya Duke',
    tier: 'Rising',
    priority: 74,
    genre: 'Reality TV/Business/Lifestyle',
    credits: 'Hollywood Exes (VH1, 2 seasons). Entrepreneur. Brand strategist.',
    igHandle: '@kenyaduke',
    igUrl: 'https://instagram.com/kenyaduke',
    ttHandle: '@kenyaduke',
    ttUrl: 'https://tiktok.com/@kenyaduke',
    igFollowers: '200K',
    ttFollowers: '50K',
    totalFollowing: '250K+',
    imageUrl: '',
    bio: 'Entrepreneur and star of Hollywood Exes on VH1. Business strategist, brand consultant, and lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Business', 'Lifestyle', 'Entrepreneurship'],
    networks: ['VH1'],
  },
]

export function getTalentBySlug(slug: string): TalentProfile | undefined {
  return talent.find((t) => t.slug === slug)
}

export function getTalentByInviteSlug(inviteSlug: string): TalentProfile | undefined {
  return talent.find((t) => t.inviteSlug === inviteSlug)
}
