export type TalentTier = 'Marquee' | 'Core' | 'Rising'
export type TalentStatus = 'invited' | 'claimed' | 'onboarding' | 'active' | 'inactive'

export interface TalentProfile {
  id: string
  slug: string
  inviteSlug: string
  name: string
  tier: TalentTier
  priority: number
  genre: string
  credits: string
  igHandle: string
  igUrl: string
  ttHandle: string
  ttUrl: string
  igFollowers: string
  ttFollowers: string
  totalFollowing: string
  imageUrl: string
  bio: string
  status: TalentStatus
  email: string
  phone: string
  categories: string[]
  networks: string[]
}

export const talent: TalentProfile[] = [
  // MARQUEE TIER (13)
  {
    id: 'bt-001',
    slug: 'bella-poarch',
    inviteSlug: 'bp-invite-2026',
    name: 'Bella Poarch',
    tier: 'Marquee',
    priority: 1,
    genre: 'Music, Fashion, Viral Content',
    credits: 'TikTok Icon. Warner Records artist. Forbes 30 Under 30. 4th most followed on TikTok globally.',
    igHandle: '@bellapoarch',
    igUrl: 'https://instagram.com/bellapoarch',
    ttHandle: '@bellapoarch',
    ttUrl: 'https://tiktok.com/@bellapoarch',
    igFollowers: '11.5M',
    ttFollowers: '92.8M',
    totalFollowing: '104M+',
    imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Singer, content creator, and cultural phenomenon with over 100 million followers worldwide. Warner Records artist with multiple viral singles and Forbes 30 Under 30 honoree.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Fashion', 'Beauty', 'Lifestyle'],
    networks: ['TikTok', 'YouTube'],
  },
  {
    id: 'bt-002',
    slug: 'john-stamos',
    inviteSlug: 'js-invite-2026',
    name: 'John Stamos',
    tier: 'Marquee',
    priority: 2,
    genre: 'Actor, Music, Family',
    credits: 'Full House. Fuller House. Grandfathered. ER. Palm Royale.',
    igHandle: '@johnstamos',
    igUrl: 'https://instagram.com/johnstamos',
    ttHandle: '@johnstamos',
    ttUrl: 'https://tiktok.com/@johnstamos',
    igFollowers: '7.2M',
    ttFollowers: '1.8M',
    totalFollowing: '9M+',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Emmy nominated actor with four decades of television credits. Known worldwide for Full House and its sequel Fuller House, currently starring in Palm Royale.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Music', 'Family'],
    networks: ['ABC', 'Netflix', 'Hulu', 'Apple TV+'],
  },
  {
    id: 'bt-003',
    slug: 'raven-symone',
    inviteSlug: 'rs-invite-2026',
    name: 'Raven Symone',
    tier: 'Marquee',
    priority: 3,
    genre: 'Actress, Beauty, Hosting',
    credits: "That's So Raven. The Cheetah Girls. The View. Raven's Home. Host of Scrabble.",
    igHandle: '@ravensymone',
    igUrl: 'https://instagram.com/ravensymone',
    ttHandle: '@ravensymone',
    ttUrl: 'https://tiktok.com/@ravensymone',
    igFollowers: '4.8M',
    ttFollowers: '2.1M',
    totalFollowing: '7M+',
    imageUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&h=750&fit=crop&crop=face&q=80',
    bio: "Disney legend and Emmy nominated actress. Host of Scrabble on CBS and former co host of The View.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Beauty', 'Hosting', 'Comedy'],
    networks: ['Disney Channel', 'ABC', 'CBS'],
  },
  {
    id: 'bt-004',
    slug: 'christina-milian',
    inviteSlug: 'cm-invite-2026',
    name: 'Christina Milian',
    tier: 'Marquee',
    priority: 4,
    genre: 'Actress, Beauty, Food, Music',
    credits: "Dip'd in Chocolate (Netflix). Falling Inn Love. Love Don't Cost a Thing. Meet Me Next Christmas.",
    igHandle: '@christinamilian',
    igUrl: 'https://instagram.com/christinamilian',
    ttHandle: '@christinamilian',
    ttUrl: 'https://tiktok.com/@christinamilian',
    igFollowers: '7.1M',
    ttFollowers: '1.5M',
    totalFollowing: '8.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Actress, singer, and entrepreneur. Netflix star with multiple original films and founder of Beignet Box.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Beauty', 'Food', 'Music'],
    networks: ['Netflix', 'Fox', 'MTV'],
  },
  {
    id: 'bt-005',
    slug: 'adam-lambert',
    inviteSlug: 'al-invite-2026',
    name: 'Adam Lambert',
    tier: 'Marquee',
    priority: 5,
    genre: 'Music, Fashion, Makeup, LGBTQ+',
    credits: 'American Idol Season 8 runner up. Lead vocalist of Queen + Adam Lambert. Grammy nominated.',
    igHandle: '@adamlambert',
    igUrl: 'https://instagram.com/adamlambert',
    ttHandle: '@adamlambert',
    ttUrl: 'https://tiktok.com/@adamlambert',
    igFollowers: '3.2M',
    ttFollowers: '1.1M',
    totalFollowing: '4.3M+',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&h=750&fit=crop&crop=face&q=80',
    bio: "Grammy nominated singer and frontman of Queen + Adam Lambert. American Idol Season 8 runner up who became one of the franchise's most successful artists.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Fashion', 'Beauty', 'LGBTQ+'],
    networks: ['Fox', 'ABC'],
  },
  {
    id: 'bt-006',
    slug: 'kat-von-d',
    inviteSlug: 'kvd-invite-2026',
    name: 'Kat Von D',
    tier: 'Marquee',
    priority: 6,
    genre: 'Fashion, Tattoo, Agriculture',
    credits: 'LA Ink. Miami Ink. Lincoln Lawyer. Founded Kat Von D Beauty (sold to Kendo).',
    igHandle: '@thekatvond',
    igUrl: 'https://instagram.com/thekatvond',
    ttHandle: '@thekatvond',
    ttUrl: 'https://tiktok.com/@thekatvond',
    igFollowers: '7.8M',
    ttFollowers: '2.3M',
    totalFollowing: '10M+',
    imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Tattoo artist, entrepreneur, and television personality. Founded Kat Von D Beauty, sold for a reported $50M+, and starred in LA Ink.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Tattoo', 'Agriculture', 'Beauty'],
    networks: ['TLC', 'Netflix'],
  },
  {
    id: 'bt-007',
    slug: 'dita-von-teese',
    inviteSlug: 'dvt-invite-2026',
    name: 'Dita Von Teese',
    tier: 'Marquee',
    priority: 7,
    genre: 'Burlesque, Vintage Fashion, Makeup',
    credits: 'Burlesque icon. Author. Lingerie designer. Perfumer. Global touring show.',
    igHandle: '@ditavonteese',
    igUrl: 'https://instagram.com/ditavonteese',
    ttHandle: '@ditavonteese',
    ttUrl: 'https://tiktok.com/@ditavonteese',
    igFollowers: '3.5M',
    ttFollowers: '650K',
    totalFollowing: '4.2M+',
    imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Queen of burlesque and global style icon. Author, lingerie designer, perfumer, and star of a globally touring theatrical show.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Beauty', 'Vintage', 'Entertainment'],
    networks: [],
  },
  {
    id: 'bt-008',
    slug: 'tiffany-pollard',
    inviteSlug: 'tp-invite-2026',
    name: 'Tiffany Pollard',
    tier: 'Marquee',
    priority: 8,
    genre: 'Entertainment, Comedy, Reality TV Icon',
    credits: 'Flavor of Love (VH1). I Love New York (VH1). Celebrity Big Brother UK. House of Villains S3 (E!).',
    igHandle: '@taborfreak',
    igUrl: 'https://instagram.com/taborfreak',
    ttHandle: '@taborfreak',
    ttUrl: 'https://tiktok.com/@taborfreak',
    igFollowers: '2.8M',
    ttFollowers: '3.5M',
    totalFollowing: '6.3M+',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=750&fit=crop&crop=face&q=80',
    bio: "Reality television royalty known as 'New York,' one of the most iconic and quoted reality TV personalities in history. Currently starring in House of Villains Season 3.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Entertainment', 'Comedy', 'Reality TV'],
    networks: ['VH1', 'E!'],
  },
  {
    id: 'bt-009',
    slug: 'riley-green',
    inviteSlug: 'rg-invite-2026',
    name: 'Riley Green',
    tier: 'Marquee',
    priority: 9,
    genre: 'Country Music, Hunting, Outdoors',
    credits: 'Redneck Island. Grammy winner. Multiple platinum singles.',
    igHandle: '@rileygreen',
    igUrl: 'https://instagram.com/rileygreen',
    ttHandle: '@rileygreen',
    ttUrl: 'https://tiktok.com/@rileygreen',
    igFollowers: '2.4M',
    ttFollowers: '3.8M',
    totalFollowing: '6.2M+',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Grammy winning country music artist with multiple platinum singles. Arena touring headliner and outdoors enthusiast.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Outdoors', 'Hunting', 'Country'],
    networks: ['CMT'],
  },
  {
    id: 'bt-010',
    slug: 'ian-somerhalder',
    inviteSlug: 'is-invite-2026',
    name: 'Ian Somerhalder',
    tier: 'Marquee',
    priority: 10,
    genre: 'Actor, Animals, Clean Living, Health',
    credits: 'Vampire Diaries. Lost. V Wars. Ian Somerhalder Foundation.',
    igHandle: '@iansomerhalder',
    igUrl: 'https://instagram.com/iansomerhalder',
    ttHandle: '@iansomerhalder',
    ttUrl: 'https://tiktok.com/@iansomerhalder',
    igFollowers: '23.5M',
    ttFollowers: '2.1M',
    totalFollowing: '25.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Actor, environmental activist, and entrepreneur. Star of The Vampire Diaries and Lost, and co founder of Brothers Bond Bourbon.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Wellness', 'Animals', 'Spirits'],
    networks: ['The CW', 'ABC', 'Netflix'],
  },
  {
    id: 'bt-011',
    slug: 'stassi-schroeder',
    inviteSlug: 'ss-invite-2026',
    name: 'Stassi Schroeder',
    tier: 'Marquee',
    priority: 11,
    genre: 'Fashion, Mom Life, Podcast',
    credits: 'Vanderpump Rules (Bravo, 8 seasons). Author. Podcast host.',
    igHandle: '@stassischroeder',
    igUrl: 'https://instagram.com/stassischroeder',
    ttHandle: '@stassischroeder',
    ttUrl: 'https://tiktok.com/@stassischroeder',
    igFollowers: '4M',
    ttFollowers: '450K',
    totalFollowing: '4.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&h=750&fit=crop&crop=face&q=80',
    bio: "Original Vanderpump Rules star and New York Times bestselling author of 'Next Level Basic.' Host of the hit podcast 'Straight Up with Stassi.'",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Lifestyle', 'Parenting', 'Podcast'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-012',
    slug: 'gypsy-rose-blanchard',
    inviteSlug: 'grb-invite-2026',
    name: 'Gypsy Rose Blanchard',
    tier: 'Marquee',
    priority: 12,
    genre: 'Lifestyle, True Crime',
    credits: 'The Act (Hulu). Life After Lock Up. Prison Confessions (Lifetime). Multiple documentaries.',
    igHandle: '@gypsyrose_a_blanchard',
    igUrl: 'https://instagram.com/gypsyrose_a_blanchard',
    ttHandle: '@gypsyrosee',
    ttUrl: 'https://tiktok.com/@gypsyrosee',
    igFollowers: '9.2M',
    ttFollowers: '6.5M',
    totalFollowing: '15.7M+',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Public figure, author, and advocate. Subject of the award winning Hulu series The Act, documented across multiple networks and streaming platforms.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Lifestyle', 'True Crime', 'Advocacy'],
    networks: ['Hulu', 'Lifetime', 'Investigation Discovery'],
  },
  {
    id: 'bt-013',
    slug: 'johnny-weir',
    inviteSlug: 'jw-invite-2026',
    name: 'Johnny Weir',
    tier: 'Marquee',
    priority: 13,
    genre: 'Figure Skating, Fashion, Comedy',
    credits: 'Olympic figure skater (2006, 2010). NBC Olympics commentator. The Masked Singer. Surreal Life.',
    igHandle: '@johnnygweir',
    igUrl: 'https://instagram.com/johnnygweir',
    ttHandle: '@johnnygweir',
    ttUrl: 'https://tiktok.com/@johnnygweir',
    igFollowers: '950K',
    ttFollowers: '1.2M',
    totalFollowing: '2.2M+',
    imageUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Two time Olympian and three time US National Champion in figure skating. NBC Olympics commentator and fashion icon.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Sports', 'Fashion', 'Comedy', 'LGBTQ+'],
    networks: ['NBC', 'Fox', 'VH1'],
  },
  // CORE TIER (30)
  {
    id: 'bt-014',
    slug: 'nicole-polizzi',
    inviteSlug: 'np-invite-2026',
    name: 'Nicole "Snooki" Polizzi',
    tier: 'Core',
    priority: 14,
    genre: 'Reality TV, Lifestyle, Mom Life',
    credits: 'Jersey Shore (MTV, 7 seasons). Snooki & JWoww. Jersey Shore Family Vacation.',
    igHandle: '@saborfreak',
    igUrl: 'https://instagram.com/snooki',
    ttHandle: '@snooki',
    ttUrl: 'https://tiktok.com/@snooki',
    igFollowers: '14M',
    ttFollowers: '3.2M',
    totalFollowing: '17.2M+',
    imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Reality television icon and original Jersey Shore cast member across seven seasons. Entrepreneur, podcast host, and bestselling author.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Lifestyle', 'Parenting', 'Comedy'],
    networks: ['MTV'],
  },
  {
    id: 'bt-015',
    slug: 'phaedra-parks',
    inviteSlug: 'pp-invite-2026',
    name: 'Phaedra Parks',
    tier: 'Core',
    priority: 15,
    genre: 'Entertainment, Law, Lifestyle',
    credits: 'Real Housewives of Atlanta (Bravo, 7 seasons). Married to Medicine. House of Villains winner.',
    igHandle: '@paborfreak',
    igUrl: 'https://instagram.com/phaedraparks',
    ttHandle: '@phaedraparks',
    ttUrl: 'https://tiktok.com/@phaedraparks',
    igFollowers: '3.4M',
    ttFollowers: '800K',
    totalFollowing: '4.2M+',
    imageUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Attorney, television personality, and House of Villains Season 1 winner. Seven season veteran of The Real Housewives of Atlanta.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Entertainment', 'Lifestyle', 'Reality TV'],
    networks: ['Bravo', 'E!'],
  },
  {
    id: 'bt-016',
    slug: 'teresa-giudice',
    inviteSlug: 'tg-invite-2026',
    name: 'Teresa Giudice',
    tier: 'Core',
    priority: 16,
    genre: 'Reality TV, Food, Fitness',
    credits: 'Real Housewives of New Jersey (Bravo, 14 seasons). Celebrity Apprentice. Dancing with the Stars.',
    igHandle: '@teresagiudice',
    igUrl: 'https://instagram.com/teresagiudice',
    ttHandle: '@teresagiudice',
    ttUrl: 'https://tiktok.com/@teresagiudice',
    igFollowers: '2.3M',
    ttFollowers: '600K',
    totalFollowing: '2.9M+',
    imageUrl: 'https://images.unsplash.com/photo-1583195764036-6dc248ac07d9?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Original cast member of The Real Housewives of New Jersey across all 14 seasons. New York Times bestselling author of multiple Italian cookbooks.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Food', 'Fitness', 'Lifestyle'],
    networks: ['Bravo', 'NBC', 'ABC'],
  },
  {
    id: 'bt-017',
    slug: 'bethenny-frankel',
    inviteSlug: 'bf-invite-2026',
    name: 'Bethenny Frankel',
    tier: 'Core',
    priority: 17,
    genre: 'Business, Lifestyle, Philanthropy',
    credits: 'Real Housewives of New York (Bravo). Bethenny Ever After. The Big Shot with Bethenny. Shark Tank.',
    igHandle: '@bethennyfrankel',
    igUrl: 'https://instagram.com/bethennyfrankel',
    ttHandle: '@bethennyfrankel',
    ttUrl: 'https://tiktok.com/@bethennyfrankel',
    igFollowers: '3M',
    ttFollowers: '1.5M',
    totalFollowing: '4.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1558898479-33c0057a5d12?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Entrepreneur who built Skinnygirl into a global brand sold for a reported $100M+. Reality television pioneer and bestselling author.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Business', 'Lifestyle', 'Food', 'Wellness'],
    networks: ['Bravo', 'ABC', 'HBO Max'],
  },
  {
    id: 'bt-018',
    slug: 'kenya-moore',
    inviteSlug: 'km-invite-2026',
    name: 'Kenya Moore',
    tier: 'Core',
    priority: 18,
    genre: 'Beauty, Entertainment, Fitness',
    credits: 'Real Housewives of Atlanta (Bravo, 11 seasons). Celebrity Apprentice. Miss USA 1993.',
    igHandle: '@thekenyamoore',
    igUrl: 'https://instagram.com/thekenyamoore',
    ttHandle: '@kenyamoore',
    ttUrl: 'https://tiktok.com/@kenyamoore',
    igFollowers: '3.2M',
    ttFollowers: '300K',
    totalFollowing: '3.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Former Miss USA 1993 and eleven season star of The Real Housewives of Atlanta. Actress, producer, and Kenya Moore Hair Care founder.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Beauty', 'Entertainment', 'Fitness'],
    networks: ['Bravo', 'NBC'],
  },
  {
    id: 'bt-019',
    slug: 'porsha-williams',
    inviteSlug: 'pw-invite-2026',
    name: 'Porsha Williams',
    tier: 'Core',
    priority: 19,
    genre: 'Entertainment, Activism, Family',
    credits: "Real Housewives of Atlanta (Bravo, 10 seasons). Porsha's Family Matters. Dish Nation.",
    igHandle: '@poraborfreak',
    igUrl: 'https://instagram.com/porsha4real',
    ttHandle: '@porsha4real',
    ttUrl: 'https://tiktok.com/@porsha4real',
    igFollowers: '7.4M',
    ttFollowers: '1M',
    totalFollowing: '8.4M+',
    imageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Television personality, activist, and entrepreneur. Ten season star of The Real Housewives of Atlanta and host of her own spinoff series.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Entertainment', 'Activism', 'Family', 'Lifestyle'],
    networks: ['Bravo', 'Fox'],
  },
  {
    id: 'bt-020',
    slug: 'heidi-montag',
    inviteSlug: 'hm-invite-2026',
    name: 'Heidi Montag',
    tier: 'Core',
    priority: 20,
    genre: 'Reality TV, Music, Lifestyle',
    credits: 'The Hills (MTV, 6 seasons). Celebrity Big Brother. I\'m a Celebrity Get Me Out of Here.',
    igHandle: '@heidimontag',
    igUrl: 'https://instagram.com/heidimontag',
    ttHandle: '@heidimontag',
    ttUrl: 'https://tiktok.com/@heidimontag',
    igFollowers: '1.7M',
    ttFollowers: '1.8M',
    totalFollowing: '3.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1513097633097-329a3a64e0d4?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Original cast member of The Hills across six seasons on MTV. Recording artist with a viral TikTok resurgence reaching millions of new fans.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Music', 'Lifestyle', 'Fashion'],
    networks: ['MTV', 'NBC'],
  },
  {
    id: 'bt-021',
    slug: 'spencer-pratt',
    inviteSlug: 'sp-invite-2026',
    name: 'Spencer Pratt',
    tier: 'Core',
    priority: 21,
    genre: 'Reality TV, Crystals, Comedy',
    credits: 'The Hills (MTV, 6 seasons). Celebrity Big Brother UK. The Hills: New Beginnings.',
    igHandle: '@spencerpratt',
    igUrl: 'https://instagram.com/spencerpratt',
    ttHandle: '@spencerpratt',
    ttUrl: 'https://tiktok.com/@spencerpratt',
    igFollowers: '1.5M',
    ttFollowers: '4.5M',
    totalFollowing: '6M+',
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Television personality and TikTok sensation known for his humming bird content reaching millions daily. Original cast member of The Hills on MTV.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Comedy', 'Lifestyle'],
    networks: ['MTV'],
  },
  {
    id: 'bt-022',
    slug: 'tamar-braxton',
    inviteSlug: 'tb-invite-2026',
    name: 'Tamar Braxton',
    tier: 'Core',
    priority: 22,
    genre: 'Music, Entertainment, Family',
    credits: 'Braxton Family Values (WE tv, 7 seasons). Celebrity Big Brother winner. The Real co host.',
    igHandle: '@tamarbraxton',
    igUrl: 'https://instagram.com/tamarbraxton',
    ttHandle: '@tamarbraxton',
    ttUrl: 'https://tiktok.com/@tamarbraxton',
    igFollowers: '5.2M',
    ttFollowers: '500K',
    totalFollowing: '5.7M+',
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Grammy nominated singer and Celebrity Big Brother Season 2 winner. Star of Braxton Family Values across seven seasons on WE tv.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Entertainment', 'Family'],
    networks: ['WE tv', 'CBS', 'Fox'],
  },
  {
    id: 'bt-023',
    slug: 'evelyn-lozada',
    inviteSlug: 'el-invite-2026',
    name: 'Evelyn Lozada',
    tier: 'Core',
    priority: 23,
    genre: 'Fashion, Fitness, Lifestyle',
    credits: 'Basketball Wives (VH1, 10 seasons). Livin Lozada (OWN).',
    igHandle: '@evelynlozada',
    igUrl: 'https://instagram.com/evelynlozada',
    ttHandle: '@evelynlozada',
    ttUrl: 'https://tiktok.com/@evelynlozada',
    igFollowers: '4.8M',
    ttFollowers: '600K',
    totalFollowing: '5.4M+',
    imageUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Original Basketball Wives cast member across ten seasons on VH1. Entrepreneur, fitness enthusiast, and lifestyle brand founder.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Fitness', 'Lifestyle'],
    networks: ['VH1', 'OWN'],
  },
  {
    id: 'bt-024',
    slug: 'tia-mowry',
    inviteSlug: 'tm-invite-2026',
    name: 'Tia Mowry',
    tier: 'Core',
    priority: 24,
    genre: 'Acting, Food, Family',
    credits: 'Sister, Sister. Family Reunion (Netflix). Tia Mowry at Home (Cooking Channel).',
    igHandle: '@tiamowry',
    igUrl: 'https://instagram.com/tiamowry',
    ttHandle: '@tiamowry',
    ttUrl: 'https://tiktok.com/@tiamowry',
    igFollowers: '11.2M',
    ttFollowers: '3.1M',
    totalFollowing: '14.3M+',
    imageUrl: 'https://images.unsplash.com/photo-1592621385612-4d7129426394?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Actress, author, and cookbook creator known for Sister, Sister and Family Reunion on Netflix. Cooking Channel host and wellness advocate.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Food', 'Family', 'Wellness'],
    networks: ['Netflix', 'ABC', 'Cooking Channel'],
  },
  {
    id: 'bt-025',
    slug: 'sonja-morgan',
    inviteSlug: 'sm-invite-2026',
    name: 'Sonja Morgan',
    tier: 'Core',
    priority: 25,
    genre: 'Fashion, Entertainment, Lifestyle',
    credits: 'Real Housewives of New York (Bravo, 13 seasons). Ultimate Girls Trip.',
    igHandle: '@sonjamorgan',
    igUrl: 'https://instagram.com/sonjamorgan',
    ttHandle: '@sonjamorgan',
    ttUrl: 'https://tiktok.com/@sonjamorgan',
    igFollowers: '1.2M',
    ttFollowers: '250K',
    totalFollowing: '1.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1557862921-37829c790f19?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Thirteen season veteran of The Real Housewives of New York City. Fashion designer, socialite, and founder of Sonja by Sonja Morgan.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Entertainment', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-026',
    slug: 'luann-de-lesseps',
    inviteSlug: 'ldl-invite-2026',
    name: 'Luann de Lesseps',
    tier: 'Core',
    priority: 26,
    genre: 'Entertainment, Music, Cabaret',
    credits: 'Real Housewives of New York (Bravo, 13 seasons). Countess and Friends cabaret tour.',
    igHandle: '@countessluann',
    igUrl: 'https://instagram.com/countessluann',
    ttHandle: '@countessluann',
    ttUrl: 'https://tiktok.com/@countessluann',
    igFollowers: '1.5M',
    ttFollowers: '350K',
    totalFollowing: '1.85M+',
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Television personality and cabaret performer touring nationally with Countess and Friends. Thirteen season star of The Real Housewives of New York City.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Entertainment', 'Music', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-027',
    slug: 'erika-jayne',
    inviteSlug: 'ej-invite-2026',
    name: 'Erika Jayne',
    tier: 'Core',
    priority: 27,
    genre: 'Music, Fashion, Entertainment',
    credits: 'Real Housewives of Beverly Hills (Bravo, 13 seasons). Dancing with the Stars. Broadway.',
    igHandle: '@theprettymess',
    igUrl: 'https://instagram.com/theprettymess',
    ttHandle: '@erikajayne',
    ttUrl: 'https://tiktok.com/@erikajayne',
    igFollowers: '2.7M',
    ttFollowers: '400K',
    totalFollowing: '3.1M+',
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Recording artist, Broadway performer, and thirteen season star of The Real Housewives of Beverly Hills. Known as Erika Jayne on stage.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Fashion', 'Entertainment'],
    networks: ['Bravo', 'ABC'],
  },
  {
    id: 'bt-028',
    slug: 'adrienne-bailon',
    inviteSlug: 'ab-invite-2026',
    name: 'Adrienne Bailon',
    tier: 'Core',
    priority: 28,
    genre: 'Music, Beauty, Hosting',
    credits: 'The Real (Fox, 8 seasons). The Cheetah Girls. I Can Do That (NBC).',
    igHandle: '@adriennebailon',
    igUrl: 'https://instagram.com/adriennebailon',
    ttHandle: '@adriennebailon',
    ttUrl: 'https://tiktok.com/@adriennebailon',
    igFollowers: '5.3M',
    ttFollowers: '800K',
    totalFollowing: '6.1M+',
    imageUrl: 'https://images.unsplash.com/photo-1549351512-c5e12b11e283?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Singer, actress, and television host. Co host of The Real for eight seasons and star of The Cheetah Girls franchise.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Beauty', 'Hosting'],
    networks: ['Fox', 'NBC', 'Disney Channel'],
  },
  {
    id: 'bt-029',
    slug: 'kim-zolciak',
    inviteSlug: 'kz-invite-2026',
    name: 'Kim Zolciak',
    tier: 'Core',
    priority: 29,
    genre: 'Reality TV, Lifestyle, Skincare',
    credits: "Real Housewives of Atlanta (Bravo, 5 seasons). Don't Be Tardy (Bravo, 8 seasons).",
    igHandle: '@kimzolciakbiermann',
    igUrl: 'https://instagram.com/kimzolciakbiermann',
    ttHandle: '@kimzolciak',
    ttUrl: 'https://tiktok.com/@kimzolciak',
    igFollowers: '3.2M',
    ttFollowers: '300K',
    totalFollowing: '3.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&h=750&fit=crop&crop=face&q=80',
    bio: "Original Real Housewives of Atlanta cast member and star of Don't Be Tardy across eight seasons. Entrepreneur and skincare brand founder.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Reality TV', 'Lifestyle', 'Skincare'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-030',
    slug: 'savannah-chrisley',
    inviteSlug: 'sc-invite-2026',
    name: 'Savannah Chrisley',
    tier: 'Core',
    priority: 30,
    genre: 'Faith, Fashion, Family',
    credits: 'Chrisley Knows Best (USA Network, 10 seasons). Growing Up Chrisley.',
    igHandle: '@savannahchrisley',
    igUrl: 'https://instagram.com/savannahchrisley',
    ttHandle: '@savannahchrisley',
    ttUrl: 'https://tiktok.com/@savannahchrisley',
    igFollowers: '3.8M',
    ttFollowers: '900K',
    totalFollowing: '4.7M+',
    imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Television personality, faith advocate, and podcast host. Star of Chrisley Knows Best across ten seasons on USA Network.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Faith', 'Fashion', 'Family', 'Podcast'],
    networks: ['USA Network', 'E!'],
  },
  {
    id: 'bt-031',
    slug: 'brie-bella',
    inviteSlug: 'bb-invite-2026',
    name: 'Brie Bella',
    tier: 'Core',
    priority: 31,
    genre: 'Fitness, Wine, Family',
    credits: 'Total Bellas (E!, 6 seasons). Total Divas (E!, 9 seasons). WWE.',
    igHandle: '@thebriebella',
    igUrl: 'https://instagram.com/thebriebella',
    ttHandle: '@brie_bella',
    ttUrl: 'https://tiktok.com/@brie_bella',
    igFollowers: '9.6M',
    ttFollowers: '2.1M',
    totalFollowing: '11.7M+',
    imageUrl: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'WWE Hall of Famer and star of Total Bellas across six seasons on E!. Co founder of Bonita Bonita Wine and Nicole + Brizee beauty brand.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fitness', 'Wine', 'Family', 'Wellness'],
    networks: ['E!', 'Fox'],
  },
  {
    id: 'bt-032',
    slug: 'nikki-bella',
    inviteSlug: 'nb-invite-2026',
    name: 'Nikki Bella',
    tier: 'Core',
    priority: 32,
    genre: 'Fitness, Beauty, Entertainment',
    credits: 'Total Bellas (E!, 6 seasons). Dancing with the Stars. America\'s Got Talent judge.',
    igHandle: '@thenikkibella',
    igUrl: 'https://instagram.com/thenikkibella',
    ttHandle: '@nikkibella',
    ttUrl: 'https://tiktok.com/@nikkibella',
    igFollowers: '10.6M',
    ttFollowers: '2.5M',
    totalFollowing: '13.1M+',
    imageUrl: 'https://images.unsplash.com/photo-1546961342-ea5f71b193f3?w=600&h=750&fit=crop&crop=face&q=80',
    bio: "WWE Hall of Famer and America's Got Talent judge. Star of Total Bellas across six seasons and Dancing with the Stars competitor.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fitness', 'Beauty', 'Entertainment'],
    networks: ['E!', 'ABC', 'NBC'],
  },
  {
    id: 'bt-033',
    slug: 'dorinda-medley',
    inviteSlug: 'dm-invite-2026',
    name: 'Dorinda Medley',
    tier: 'Core',
    priority: 33,
    genre: 'Lifestyle, Entertaining, Fashion',
    credits: 'Real Housewives of New York (Bravo, 6 seasons). Ultimate Girls Trip (Peacock).',
    igHandle: '@doraborfreak',
    igUrl: 'https://instagram.com/dorindamedley',
    ttHandle: '@dorindamedley',
    ttUrl: 'https://tiktok.com/@dorindamedley',
    igFollowers: '800K',
    ttFollowers: '200K',
    totalFollowing: '1M+',
    imageUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Six season star of The Real Housewives of New York City and fan favorite on Ultimate Girls Trip. Known for hosting at her Berkshires estate Blue Stone Manor.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Lifestyle', 'Entertaining', 'Fashion'],
    networks: ['Bravo', 'Peacock'],
  },
  {
    id: 'bt-034',
    slug: 'brandi-glanville',
    inviteSlug: 'bg-invite-2026',
    name: 'Brandi Glanville',
    tier: 'Core',
    priority: 34,
    genre: 'Entertainment, Podcast, Lifestyle',
    credits: 'Real Housewives of Beverly Hills (Bravo, 4 seasons). Celebrity Big Brother. My Kitchen Rules.',
    igHandle: '@brandiglanville',
    igUrl: 'https://instagram.com/brandiglanville',
    ttHandle: '@brandiglanville',
    ttUrl: 'https://tiktok.com/@brandiglanville',
    igFollowers: '830K',
    ttFollowers: '150K',
    totalFollowing: '980K+',
    imageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Television personality, bestselling author, and podcast host. Star of The Real Housewives of Beverly Hills and Celebrity Big Brother.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Entertainment', 'Podcast', 'Lifestyle'],
    networks: ['Bravo', 'CBS', 'Fox'],
  },
  {
    id: 'bt-035',
    slug: 'dr-paul-nassif',
    inviteSlug: 'pn-invite-2026',
    name: 'Dr. Paul Nassif',
    tier: 'Core',
    priority: 35,
    genre: 'Medicine, Beauty, Skincare',
    credits: 'Botched (E!, 8 seasons). Real Housewives of Beverly Hills.',
    igHandle: '@drpaulnassif',
    igUrl: 'https://instagram.com/drpaulnassif',
    ttHandle: '@drpaulnassif',
    ttUrl: 'https://tiktok.com/@drpaulnassif',
    igFollowers: '2.2M',
    ttFollowers: '500K',
    totalFollowing: '2.7M+',
    imageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'World renowned facial plastic surgeon and co star of Botched across eight seasons on E!. Founder of NassifMD skincare brand.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Medicine', 'Beauty', 'Skincare'],
    networks: ['E!'],
  },
  {
    id: 'bt-036',
    slug: 'lisa-rinna',
    inviteSlug: 'lr-invite-2026',
    name: 'Lisa Rinna',
    tier: 'Core',
    priority: 36,
    genre: 'Fashion, Beauty, Acting',
    credits: 'Real Housewives of Beverly Hills (Bravo, 8 seasons). Days of Our Lives. QVC host.',
    igHandle: '@lisarinna',
    igUrl: 'https://instagram.com/lisarinna',
    ttHandle: '@lisarinna',
    ttUrl: 'https://tiktok.com/@lisarinna',
    igFollowers: '3.6M',
    ttFollowers: '1.2M',
    totalFollowing: '4.8M+',
    imageUrl: 'https://images.unsplash.com/photo-1551292831-023188e78222?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Actress, entrepreneur, and eight season star of The Real Housewives of Beverly Hills. Known for her iconic lip and Rinna Beauty brand.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Beauty', 'Acting'],
    networks: ['Bravo', 'NBC'],
  },
  {
    id: 'bt-037',
    slug: 'ross-mathews',
    inviteSlug: 'rm-invite-2026',
    name: 'Ross Mathews',
    tier: 'Core',
    priority: 37,
    genre: 'Hosting, Comedy, LGBTQ+',
    credits: "RuPaul's Drag Race judge. Hello Ross (E!). Celebrity Big Brother. The Drew Barrymore Show.",
    igHandle: '@haborfreak',
    igUrl: 'https://instagram.com/helloross',
    ttHandle: '@helloross',
    ttUrl: 'https://tiktok.com/@helloross',
    igFollowers: '750K',
    ttFollowers: '300K',
    totalFollowing: '1.05M+',
    imageUrl: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=600&h=750&fit=crop&crop=face&q=80',
    bio: "Permanent judge on RuPaul's Drag Race and Emmy winning television personality. Host, comedian, and bestselling author.",
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Hosting', 'Comedy', 'LGBTQ+'],
    networks: ['VH1', 'E!', 'CBS'],
  },
  {
    id: 'bt-038',
    slug: 'bob-harper',
    inviteSlug: 'bh-invite-2026',
    name: 'Bob Harper',
    tier: 'Core',
    priority: 38,
    genre: 'Fitness, Health, Wellness',
    credits: 'The Biggest Loser (NBC, 17 seasons). Celebrity trainer.',
    igHandle: '@bobharper',
    igUrl: 'https://instagram.com/bobharper',
    ttHandle: '@bobharper',
    ttUrl: 'https://tiktok.com/@bobharper',
    igFollowers: '700K',
    ttFollowers: '100K',
    totalFollowing: '800K+',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Celebrity fitness trainer and host of The Biggest Loser across seventeen seasons on NBC. Bestselling author and heart health advocate.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fitness', 'Health', 'Wellness'],
    networks: ['NBC'],
  },
  {
    id: 'bt-039',
    slug: 'jill-zarin',
    inviteSlug: 'jz-invite-2026',
    name: 'Jill Zarin',
    tier: 'Core',
    priority: 39,
    genre: 'Lifestyle, Business, Fashion',
    credits: 'Real Housewives of New York (Bravo, 4 seasons). Ultimate Girls Trip.',
    igHandle: '@jillzarin',
    igUrl: 'https://instagram.com/jillzarin',
    ttHandle: '@jillzarin',
    ttUrl: 'https://tiktok.com/@jillzarin',
    igFollowers: '500K',
    ttFollowers: '150K',
    totalFollowing: '650K+',
    imageUrl: 'https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Original Real Housewives of New York City cast member and serial entrepreneur. Bestselling author and philanthropist.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Lifestyle', 'Business', 'Fashion'],
    networks: ['Bravo', 'Peacock'],
  },
  {
    id: 'bt-040',
    slug: 'tori-spelling',
    inviteSlug: 'ts-invite-2026',
    name: 'Tori Spelling',
    tier: 'Core',
    priority: 40,
    genre: 'Acting, Lifestyle, Parenting',
    credits: 'Beverly Hills 90210. True Tori. Tori & Dean: Home Sweet Hollywood. Celebrity Big Brother.',
    igHandle: '@torispelling',
    igUrl: 'https://instagram.com/torispelling',
    ttHandle: '@torispelling',
    ttUrl: 'https://tiktok.com/@torispelling',
    igFollowers: '2.1M',
    ttFollowers: '500K',
    totalFollowing: '2.6M+',
    imageUrl: 'https://images.unsplash.com/photo-1499557354967-2b2d8910bcca?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Actress and television personality known for Beverly Hills 90210 and multiple reality series. Bestselling author and lifestyle brand creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Lifestyle', 'Parenting'],
    networks: ['Fox', 'Oxygen', 'CBS'],
  },
  {
    id: 'bt-041',
    slug: 'kathryn-dennis',
    inviteSlug: 'kd-invite-2026',
    name: 'Kathryn Dennis',
    tier: 'Core',
    priority: 41,
    genre: 'Lifestyle, Fashion, Southern Living',
    credits: 'Southern Charm (Bravo, 8 seasons).',
    igHandle: '@kathryndennis',
    igUrl: 'https://instagram.com/kathryndennis',
    ttHandle: '@kathryndennis',
    ttUrl: 'https://tiktok.com/@kathryndennis',
    igFollowers: '550K',
    ttFollowers: '100K',
    totalFollowing: '650K+',
    imageUrl: 'https://images.unsplash.com/photo-1485893086445-ed75865251e0?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Eight season star of Southern Charm on Bravo. Model, painter, and advocate for mental health awareness.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Lifestyle', 'Fashion', 'Art'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-042',
    slug: 'teddi-mellencamp',
    inviteSlug: 'tme-invite-2026',
    name: 'Teddi Mellencamp',
    tier: 'Core',
    priority: 42,
    genre: 'Fitness, Wellness, Podcast',
    credits: 'Real Housewives of Beverly Hills (Bravo, 3 seasons). Podcast host.',
    igHandle: '@teddimellencamp',
    igUrl: 'https://instagram.com/teddimellencamp',
    ttHandle: '@teddimellencamp',
    ttUrl: 'https://tiktok.com/@teddimellencamp',
    igFollowers: '850K',
    ttFollowers: '150K',
    totalFollowing: '1M+',
    imageUrl: 'https://images.unsplash.com/photo-1589571894960-20bbe2828d0a?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Accountability coach and star of The Real Housewives of Beverly Hills. Founder of All In by Teddi fitness program and podcast host.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fitness', 'Wellness', 'Podcast'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-043',
    slug: 'chrishell-stause',
    inviteSlug: 'cs-invite-2026',
    name: 'Chrishell Stause',
    tier: 'Core',
    priority: 43,
    genre: 'Real Estate, Acting, Lifestyle',
    credits: 'Selling Sunset (Netflix, 7 seasons). Dancing with the Stars. Days of Our Lives.',
    igHandle: '@chrishell.stause',
    igUrl: 'https://instagram.com/chrishell.stause',
    ttHandle: '@chrishellstause',
    ttUrl: 'https://tiktok.com/@chrishellstause',
    igFollowers: '3.8M',
    ttFollowers: '2.3M',
    totalFollowing: '6.1M+',
    imageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Star of Selling Sunset across seven seasons on Netflix and former Days of Our Lives actress. Real estate agent and Dancing with the Stars competitor.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Real Estate', 'Acting', 'Lifestyle'],
    networks: ['Netflix', 'ABC', 'NBC'],
  },
  // RISING TIER (31)
  {
    id: 'bt-044',
    slug: 'paige-desorbo',
    inviteSlug: 'pd-invite-2026',
    name: 'Paige DeSorbo',
    tier: 'Rising',
    priority: 44,
    genre: 'Fashion, Podcast, Reality TV',
    credits: 'Summer House (Bravo, 8 seasons). Winter House. Giggly Squad podcast.',
    igHandle: '@paborfreak',
    igUrl: 'https://instagram.com/paige_desorbo',
    ttHandle: '@paige_desorbo',
    ttUrl: 'https://tiktok.com/@paige_desorbo',
    igFollowers: '1.3M',
    ttFollowers: '700K',
    totalFollowing: '2M+',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Fashion influencer and eight season star of Summer House on Bravo. Co host of the Giggly Squad podcast.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fashion', 'Podcast', 'Reality TV'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-045',
    slug: 'lindsay-hubbard',
    inviteSlug: 'lh-invite-2026',
    name: 'Lindsay Hubbard',
    tier: 'Rising',
    priority: 45,
    genre: 'PR, Lifestyle, Dating',
    credits: 'Summer House (Bravo, 8 seasons). Winter House.',
    igHandle: '@lindshub',
    igUrl: 'https://instagram.com/lindshub',
    ttHandle: '@lindshub',
    ttUrl: 'https://tiktok.com/@lindshub',
    igFollowers: '550K',
    ttFollowers: '150K',
    totalFollowing: '700K+',
    imageUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Public relations executive and eight season star of Summer House on Bravo. Founder of Hubb House PR and lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['PR', 'Lifestyle', 'Dating'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-046',
    slug: 'ciara-miller',
    inviteSlug: 'cmi-invite-2026',
    name: 'Ciara Miller',
    tier: 'Rising',
    priority: 46,
    genre: 'Nursing, Fashion, Fitness',
    credits: 'Summer House (Bravo, 4 seasons). Winter House.',
    igHandle: '@ciaramiller__',
    igUrl: 'https://instagram.com/ciaramiller__',
    ttHandle: '@ciaramiller',
    ttUrl: 'https://tiktok.com/@ciaramiller',
    igFollowers: '400K',
    ttFollowers: '100K',
    totalFollowing: '500K+',
    imageUrl: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'ICU nurse turned television personality on Summer House and Winter House. Model, fitness enthusiast, and fashion content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Nursing', 'Fashion', 'Fitness'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-047',
    slug: 'craig-conover',
    inviteSlug: 'cc-invite-2026',
    name: 'Craig Conover',
    tier: 'Rising',
    priority: 47,
    genre: 'Lifestyle, Home, Entrepreneurship',
    credits: 'Southern Charm (Bravo, 9 seasons). Winter House. Pillow Talk.',
    igHandle: '@caconover',
    igUrl: 'https://instagram.com/caconover',
    ttHandle: '@caconover',
    ttUrl: 'https://tiktok.com/@caconover',
    igFollowers: '700K',
    ttFollowers: '200K',
    totalFollowing: '900K+',
    imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Nine season star of Southern Charm on Bravo and founder of Sewing Down South pillow company. Entrepreneur, attorney, and lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Lifestyle', 'Home', 'Entrepreneurship'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-048',
    slug: 'austen-kroll',
    inviteSlug: 'ak-invite-2026',
    name: 'Austen Kroll',
    tier: 'Rising',
    priority: 48,
    genre: 'Beer, Lifestyle, Southern Living',
    credits: 'Southern Charm (Bravo, 8 seasons). Winter House.',
    igHandle: '@kaborfreak',
    igUrl: 'https://instagram.com/austenkroll',
    ttHandle: '@austenkroll',
    ttUrl: 'https://tiktok.com/@austenkroll',
    igFollowers: '450K',
    ttFollowers: '100K',
    totalFollowing: '550K+',
    imageUrl: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Eight season star of Southern Charm on Bravo and craft beer entrepreneur. Founder of Kings Calling Brewing Company.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Beer', 'Lifestyle', 'Entrepreneurship'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-049',
    slug: 'madison-lecroy',
    inviteSlug: 'ml-invite-2026',
    name: 'Madison LeCroy',
    tier: 'Rising',
    priority: 49,
    genre: 'Beauty, Salon, Southern Living',
    credits: 'Southern Charm (Bravo, 5 seasons).',
    igHandle: '@madisonlecroy',
    igUrl: 'https://instagram.com/madisonlecroy',
    ttHandle: '@madisonlecroy',
    ttUrl: 'https://tiktok.com/@madisonlecroy',
    igFollowers: '600K',
    ttFollowers: '250K',
    totalFollowing: '850K+',
    imageUrl: 'https://images.unsplash.com/photo-1514315384763-ba401779410f?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Hair stylist and television personality from Southern Charm on Bravo. Salon owner and beauty content creator based in Charleston.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Beauty', 'Salon', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-050',
    slug: 'lala-kent',
    inviteSlug: 'lk-invite-2026',
    name: 'Lala Kent',
    tier: 'Rising',
    priority: 50,
    genre: 'Beauty, Acting, Mom Life',
    credits: 'Vanderpump Rules (Bravo, 11 seasons). The Valley (Bravo).',
    igHandle: '@lalakent',
    igUrl: 'https://instagram.com/lalakent',
    ttHandle: '@lalakent',
    ttUrl: 'https://tiktok.com/@lalakent',
    igFollowers: '1.7M',
    ttFollowers: '600K',
    totalFollowing: '2.3M+',
    imageUrl: 'https://images.unsplash.com/photo-1503104834685-7205e8607eb9?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Eleven season star of Vanderpump Rules and cast member of The Valley on Bravo. Founder of Give Them Lala Beauty and bestselling author.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Beauty', 'Acting', 'Parenting'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-051',
    slug: 'ariana-madix',
    inviteSlug: 'am-invite-2026',
    name: 'Ariana Madix',
    tier: 'Rising',
    priority: 51,
    genre: 'Hosting, Cocktails, Entertainment',
    credits: 'Vanderpump Rules (Bravo, 11 seasons). Love Island USA host. Dancing with the Stars.',
    igHandle: '@arianamadix',
    igUrl: 'https://instagram.com/arianamadix',
    ttHandle: '@arianamadix',
    ttUrl: 'https://tiktok.com/@arianamadix',
    igFollowers: '1.8M',
    ttFollowers: '1.5M',
    totalFollowing: '3.3M+',
    imageUrl: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Host of Love Island USA on Peacock and eleven season star of Vanderpump Rules. Cocktail book author and Dancing with the Stars finalist.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Hosting', 'Cocktails', 'Entertainment'],
    networks: ['Bravo', 'Peacock', 'ABC'],
  },
  {
    id: 'bt-052',
    slug: 'tom-sandoval',
    inviteSlug: 'tsa-invite-2026',
    name: 'Tom Sandoval',
    tier: 'Rising',
    priority: 52,
    genre: 'Music, Bars, Entertainment',
    credits: 'Vanderpump Rules (Bravo, 11 seasons). Special Forces. The Traitors.',
    igHandle: '@tomsandoval1',
    igUrl: 'https://instagram.com/tomsandoval1',
    ttHandle: '@tomsandoval1',
    ttUrl: 'https://tiktok.com/@tomsandoval1',
    igFollowers: '700K',
    ttFollowers: '400K',
    totalFollowing: '1.1M+',
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Eleven season star of Vanderpump Rules and co owner of Schwartz and Sandy bar. Musician, model, and reality television personality.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Bars', 'Entertainment'],
    networks: ['Bravo', 'Fox', 'Peacock'],
  },
  {
    id: 'bt-053',
    slug: 'scheana-shay',
    inviteSlug: 'ssh-invite-2026',
    name: 'Scheana Shay',
    tier: 'Rising',
    priority: 53,
    genre: 'Music, Mom Life, Entertainment',
    credits: 'Vanderpump Rules (Bravo, 11 seasons).',
    igHandle: '@scheana',
    igUrl: 'https://instagram.com/scheana',
    ttHandle: '@scheana',
    ttUrl: 'https://tiktok.com/@scheana',
    igFollowers: '1.3M',
    ttFollowers: '600K',
    totalFollowing: '1.9M+',
    imageUrl: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Original Vanderpump Rules cast member across all eleven seasons on Bravo. Recording artist, podcast host, and content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Music', 'Parenting', 'Entertainment'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-054',
    slug: 'katie-maloney',
    inviteSlug: 'kma-invite-2026',
    name: 'Katie Maloney',
    tier: 'Rising',
    priority: 54,
    genre: 'Food, Entrepreneurship, Lifestyle',
    credits: 'Vanderpump Rules (Bravo, 11 seasons).',
    igHandle: '@musickillskate',
    igUrl: 'https://instagram.com/musickillskate',
    ttHandle: '@katiemaloney',
    ttUrl: 'https://tiktok.com/@katiemaloney',
    igFollowers: '650K',
    ttFollowers: '200K',
    totalFollowing: '850K+',
    imageUrl: 'https://images.unsplash.com/photo-1521146764736-56c929d59c83?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Eleven season star of Vanderpump Rules and founder of Something About Her sandwich shop. Entrepreneur, podcast host, and lifestyle creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Food', 'Entrepreneurship', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-055',
    slug: 'james-kennedy',
    inviteSlug: 'jk-invite-2026',
    name: 'James Kennedy',
    tier: 'Rising',
    priority: 55,
    genre: 'DJing, Music, Entertainment',
    credits: 'Vanderpump Rules (Bravo, 11 seasons).',
    igHandle: '@itsjameskennedy',
    igUrl: 'https://instagram.com/itsjameskennedy',
    ttHandle: '@itsjameskennedy',
    ttUrl: 'https://tiktok.com/@itsjameskennedy',
    igFollowers: '550K',
    ttFollowers: '300K',
    totalFollowing: '850K+',
    imageUrl: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'DJ, music producer, and eleven season star of Vanderpump Rules on Bravo. Touring DJ performing at clubs and festivals worldwide.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['DJing', 'Music', 'Entertainment'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-056',
    slug: 'malia-white',
    inviteSlug: 'mw-invite-2026',
    name: 'Malia White',
    tier: 'Rising',
    priority: 56,
    genre: 'Yachting, Travel, Adventure',
    credits: 'Below Deck Mediterranean (Bravo, 4 seasons).',
    igHandle: '@maborfreak',
    igUrl: 'https://instagram.com/maliawhite',
    ttHandle: '@maliawhite',
    ttUrl: 'https://tiktok.com/@maliawhite',
    igFollowers: '350K',
    ttFollowers: '100K',
    totalFollowing: '450K+',
    imageUrl: 'https://images.unsplash.com/photo-1502768040783-423da5fd5fa0?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Professional yacht bosun and four season star of Below Deck Mediterranean on Bravo. Certified divemaster and ocean adventure content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Yachting', 'Travel', 'Adventure'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-057',
    slug: 'hannah-berner',
    inviteSlug: 'hb-invite-2026',
    name: 'Hannah Berner',
    tier: 'Rising',
    priority: 57,
    genre: 'Comedy, Podcast, Tennis',
    credits: 'Summer House (Bravo, 3 seasons). Sold out comedy tours.',
    igHandle: '@beingbernz',
    igUrl: 'https://instagram.com/beingbernz',
    ttHandle: '@beingbernz',
    ttUrl: 'https://tiktok.com/@beingbernz',
    igFollowers: '700K',
    ttFollowers: '500K',
    totalFollowing: '1.2M+',
    imageUrl: 'https://images.unsplash.com/photo-1541823709867-1b206113eafd?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Stand up comedian selling out theaters nationwide and former Summer House cast member. Co host of the Giggly Squad podcast with Paige DeSorbo.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Comedy', 'Podcast', 'Sports'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-058',
    slug: 'jax-taylor',
    inviteSlug: 'jt-invite-2026',
    name: 'Jax Taylor',
    tier: 'Rising',
    priority: 58,
    genre: 'Bars, Hockey, Entertainment',
    credits: 'Vanderpump Rules (Bravo, 8 seasons). The Valley (Bravo).',
    igHandle: '@mrjaxtaylor',
    igUrl: 'https://instagram.com/mrjaxtaylor',
    ttHandle: '@jaxtaylor',
    ttUrl: 'https://tiktok.com/@jaxtaylor',
    igFollowers: '1.2M',
    ttFollowers: '300K',
    totalFollowing: '1.5M+',
    imageUrl: 'https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Original Vanderpump Rules cast member across eight seasons and star of The Valley on Bravo. Former model and bar industry entrepreneur.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Bars', 'Entertainment', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-059',
    slug: 'brittany-cartwright',
    inviteSlug: 'bc-invite-2026',
    name: 'Brittany Cartwright',
    tier: 'Rising',
    priority: 59,
    genre: 'Mom Life, Southern Living, Lifestyle',
    credits: 'Vanderpump Rules (Bravo, 5 seasons). The Valley (Bravo).',
    igHandle: '@brittany',
    igUrl: 'https://instagram.com/brittany',
    ttHandle: '@brittanycartwright',
    ttUrl: 'https://tiktok.com/@brittanycartwright',
    igFollowers: '1.5M',
    ttFollowers: '400K',
    totalFollowing: '1.9M+',
    imageUrl: 'https://images.unsplash.com/photo-1508326099025-55ef1d46793b?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Star of Vanderpump Rules and The Valley on Bravo. Kentucky native, proud mom, and lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Parenting', 'Lifestyle', 'Southern Living'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-060',
    slug: 'gabby-windey',
    inviteSlug: 'gw-invite-2026',
    name: 'Gabby Windey',
    tier: 'Rising',
    priority: 60,
    genre: 'Nursing, Dancing, LGBTQ+',
    credits: 'The Bachelorette (ABC, Season 19). Dancing with the Stars finalist.',
    igHandle: '@gabby.windey',
    igUrl: 'https://instagram.com/gabby.windey',
    ttHandle: '@gabbywindey',
    ttUrl: 'https://tiktok.com/@gabbywindey',
    igFollowers: '800K',
    ttFollowers: '200K',
    totalFollowing: '1M+',
    imageUrl: 'https://images.unsplash.com/photo-1529635707364-083ca7ac5a68?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Season 19 Bachelorette and Dancing with the Stars finalist. Former ICU nurse, comedy lover, and LGBTQ+ advocate.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Nursing', 'Dancing', 'LGBTQ+'],
    networks: ['ABC'],
  },
  {
    id: 'bt-061',
    slug: 'tyler-cameron',
    inviteSlug: 'tc-invite-2026',
    name: 'Tyler Cameron',
    tier: 'Rising',
    priority: 61,
    genre: 'Modeling, Construction, Fitness',
    credits: 'The Bachelorette (ABC, Season 15). Going Home with Tyler Cameron (Amazon).',
    igHandle: '@tylerjcameron3',
    igUrl: 'https://instagram.com/tylerjcameron3',
    ttHandle: '@tylercameron',
    ttUrl: 'https://tiktok.com/@tylercameron',
    igFollowers: '2.4M',
    ttFollowers: '600K',
    totalFollowing: '3M+',
    imageUrl: 'https://images.unsplash.com/photo-1545996124-0501ebae84d0?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Model, general contractor, and Season 15 Bachelorette fan favorite. Host of Going Home with Tyler Cameron on Amazon and bestselling author.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Modeling', 'Construction', 'Fitness'],
    networks: ['ABC', 'Amazon'],
  },
  {
    id: 'bt-062',
    slug: 'matt-james',
    inviteSlug: 'mj-invite-2026',
    name: 'Matt James',
    tier: 'Rising',
    priority: 62,
    genre: 'Fitness, Real Estate, Philanthropy',
    credits: 'The Bachelor (ABC, Season 25). Dancing with the Stars.',
    igHandle: '@mattjames919',
    igUrl: 'https://instagram.com/mattjames919',
    ttHandle: '@mattjames919',
    ttUrl: 'https://tiktok.com/@mattjames919',
    igFollowers: '1.1M',
    ttFollowers: '300K',
    totalFollowing: '1.4M+',
    imageUrl: 'https://images.unsplash.com/photo-1507081323647-4d250478b919?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Season 25 Bachelor and first Black lead in the franchise history. Real estate professional, marathon runner, and founder of ABC Food Tours.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Fitness', 'Real Estate', 'Philanthropy'],
    networks: ['ABC'],
  },
  {
    id: 'bt-063',
    slug: 'tayshia-adams',
    inviteSlug: 'ta-invite-2026',
    name: 'Tayshia Adams',
    tier: 'Rising',
    priority: 63,
    genre: 'Hosting, Beauty, Lifestyle',
    credits: 'The Bachelorette (ABC, Season 16). Bachelor in Paradise. Click Bait podcast.',
    igHandle: '@tayshia',
    igUrl: 'https://instagram.com/tayshia',
    ttHandle: '@tayshia',
    ttUrl: 'https://tiktok.com/@tayshia',
    igFollowers: '2.5M',
    ttFollowers: '400K',
    totalFollowing: '2.9M+',
    imageUrl: 'https://images.unsplash.com/photo-1502767089025-6572583495f6?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Season 16 Bachelorette and co host of the Click Bait podcast. Former phlebotomist turned television host and beauty brand ambassador.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Hosting', 'Beauty', 'Lifestyle'],
    networks: ['ABC'],
  },
  {
    id: 'bt-064',
    slug: 'rachel-lindsay',
    inviteSlug: 'rl-invite-2026',
    name: 'Rachel Lindsay',
    tier: 'Rising',
    priority: 64,
    genre: 'Hosting, Law, Advocacy',
    credits: 'The Bachelorette (ABC, Season 13). Extra correspondent. Higher Learning podcast.',
    igHandle: '@therachlindsay',
    igUrl: 'https://instagram.com/therachlindsay',
    ttHandle: '@rachlindsay',
    ttUrl: 'https://tiktok.com/@rachlindsay',
    igFollowers: '1.1M',
    ttFollowers: '200K',
    totalFollowing: '1.3M+',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Attorney, television host, and the first Black Bachelorette in franchise history. Extra correspondent and co host of the Higher Learning podcast.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Hosting', 'Law', 'Advocacy'],
    networks: ['ABC'],
  },
  {
    id: 'bt-065',
    slug: 'charity-lawson',
    inviteSlug: 'cl-invite-2026',
    name: 'Charity Lawson',
    tier: 'Rising',
    priority: 65,
    genre: 'Family, Dance, Lifestyle',
    credits: 'The Bachelorette (ABC, Season 20). Dancing with the Stars.',
    igHandle: '@charitylawson',
    igUrl: 'https://instagram.com/charitylawson',
    ttHandle: '@charitylawson',
    ttUrl: 'https://tiktok.com/@charitylawson',
    igFollowers: '500K',
    ttFollowers: '150K',
    totalFollowing: '650K+',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Season 20 Bachelorette and Dancing with the Stars competitor. Child and family therapist and lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Family', 'Dance', 'Lifestyle'],
    networks: ['ABC'],
  },
  {
    id: 'bt-066',
    slug: 'kyle-cooke',
    inviteSlug: 'kc-invite-2026',
    name: 'Kyle Cooke',
    tier: 'Rising',
    priority: 66,
    genre: 'Entrepreneurship, Spirits, Lifestyle',
    credits: 'Summer House (Bravo, 8 seasons). Winter House.',
    igHandle: '@kylecooke',
    igUrl: 'https://instagram.com/kylecooke',
    ttHandle: '@kylecooke',
    ttUrl: 'https://tiktok.com/@kylecooke',
    igFollowers: '350K',
    ttFollowers: '100K',
    totalFollowing: '450K+',
    imageUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Eight season star of Summer House on Bravo and founder of Loverboy beverage brand. Entrepreneur and content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Entrepreneurship', 'Spirits', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-067',
    slug: 'amanda-batula',
    inviteSlug: 'aba-invite-2026',
    name: 'Amanda Batula',
    tier: 'Rising',
    priority: 67,
    genre: 'Design, Fashion, Lifestyle',
    credits: 'Summer House (Bravo, 8 seasons). Winter House.',
    igHandle: '@amandabatula',
    igUrl: 'https://instagram.com/amandabatula',
    ttHandle: '@amandabatula',
    ttUrl: 'https://tiktok.com/@amandabatula',
    igFollowers: '400K',
    ttFollowers: '100K',
    totalFollowing: '500K+',
    imageUrl: 'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Graphic designer and eight season star of Summer House on Bravo. Creative director of Loverboy beverage brand and fashion content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Design', 'Fashion', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-068',
    slug: 'chanel-ayan',
    inviteSlug: 'ca-invite-2026',
    name: 'Chanel Ayan',
    tier: 'Rising',
    priority: 68,
    genre: 'Modeling, Fashion, Culture',
    credits: 'Real Housewives of Dubai (Bravo, 2 seasons).',
    igHandle: '@chanelayan',
    igUrl: 'https://instagram.com/chanelayan',
    ttHandle: '@chanelayan',
    ttUrl: 'https://tiktok.com/@chanelayan',
    igFollowers: '700K',
    ttFollowers: '200K',
    totalFollowing: '900K+',
    imageUrl: 'https://images.unsplash.com/photo-1504703395950-b89145a5425b?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Supermodel and breakout star of The Real Housewives of Dubai on Bravo. Kenyan born fashion icon and cultural ambassador.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Modeling', 'Fashion', 'Culture'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-069',
    slug: 'nene-leakes',
    inviteSlug: 'nl-invite-2026',
    name: 'NeNe Leakes',
    tier: 'Rising',
    priority: 69,
    genre: 'Entertainment, Comedy, Fashion',
    credits: 'Real Housewives of Atlanta (Bravo, 12 seasons). Glee. The New Normal. Celebrity Apprentice.',
    igHandle: '@neneleakes',
    igUrl: 'https://instagram.com/neneleakes',
    ttHandle: '@neneleakes',
    ttUrl: 'https://tiktok.com/@neneleakes',
    igFollowers: '4.2M',
    ttFollowers: '800K',
    totalFollowing: '5M+',
    imageUrl: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Television personality, actress, and twelve season star of The Real Housewives of Atlanta. Appeared on Glee, The New Normal, and Celebrity Apprentice.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Entertainment', 'Comedy', 'Fashion'],
    networks: ['Bravo', 'Fox', 'NBC'],
  },
  {
    id: 'bt-070',
    slug: 'quad-webb',
    inviteSlug: 'qw-invite-2026',
    name: 'Quad Webb',
    tier: 'Rising',
    priority: 70,
    genre: 'Medicine, Lifestyle, Entrepreneurship',
    credits: 'Married to Medicine (Bravo, 10 seasons).',
    igHandle: '@quadwebb',
    igUrl: 'https://instagram.com/quadwebb',
    ttHandle: '@quadwebb',
    ttUrl: 'https://tiktok.com/@quadwebb',
    igFollowers: '900K',
    ttFollowers: '200K',
    totalFollowing: '1.1M+',
    imageUrl: 'https://images.unsplash.com/photo-1611432579699-484f7990b127?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Ten season star of Married to Medicine on Bravo and entrepreneur. Fashion designer, author, and lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Medicine', 'Lifestyle', 'Entrepreneurship'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-071',
    slug: 'dr-heavenly-kimes',
    inviteSlug: 'hk-invite-2026',
    name: 'Dr. Heavenly Kimes',
    tier: 'Rising',
    priority: 71,
    genre: 'Dentistry, Comedy, Lifestyle',
    credits: 'Married to Medicine (Bravo, 10 seasons). YouTube personality.',
    igHandle: '@drheavenly',
    igUrl: 'https://instagram.com/drheavenly',
    ttHandle: '@drheavenly',
    ttUrl: 'https://tiktok.com/@drheavenly',
    igFollowers: '1.4M',
    ttFollowers: '500K',
    totalFollowing: '1.9M+',
    imageUrl: 'https://images.unsplash.com/photo-1567532900872-f4e906cbf06a?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Dentist, author, and ten season star of Married to Medicine on Bravo. Known for her sharp wit and popular YouTube channel.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Dentistry', 'Comedy', 'Lifestyle'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-072',
    slug: 'garcelle-beauvais',
    inviteSlug: 'gb-invite-2026',
    name: 'Garcelle Beauvais',
    tier: 'Rising',
    priority: 72,
    genre: 'Acting, Hosting, Fashion',
    credits: 'Real Housewives of Beverly Hills (Bravo, 5 seasons). Coming to America. The Jamie Foxx Show.',
    igHandle: '@garcelle',
    igUrl: 'https://instagram.com/garcelle',
    ttHandle: '@garcelle',
    ttUrl: 'https://tiktok.com/@garcelle',
    igFollowers: '1.7M',
    ttFollowers: '300K',
    totalFollowing: '2M+',
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Actress, television host, and five season star of The Real Housewives of Beverly Hills. Known for Coming to America and The Jamie Foxx Show.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Acting', 'Hosting', 'Fashion'],
    networks: ['Bravo', 'Amazon', 'The CW'],
  },
  {
    id: 'bt-073',
    slug: 'claudia-oshry',
    inviteSlug: 'co-invite-2026',
    name: 'Claudia Oshry',
    tier: 'Rising',
    priority: 73,
    genre: 'Comedy, Podcast, Pop Culture',
    credits: 'The Morning Toast podcast. Bravo superfan. Sold out comedy tours.',
    igHandle: '@girlwithnojob',
    igUrl: 'https://instagram.com/girlwithnojob',
    ttHandle: '@girlwithnojob',
    ttUrl: 'https://tiktok.com/@girlwithnojob',
    igFollowers: '450K',
    ttFollowers: '200K',
    totalFollowing: '650K+',
    imageUrl: 'https://images.unsplash.com/photo-1518577915332-c2a19f149a75?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Stand up comedian and host of The Morning Toast podcast. Known online as Girl With No Job, performing sold out comedy shows nationwide.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Comedy', 'Podcast', 'Pop Culture'],
    networks: ['Bravo'],
  },
  {
    id: 'bt-074',
    slug: 'kenya-duke',
    inviteSlug: 'kdu-invite-2026',
    name: 'Kenya Duke',
    tier: 'Rising',
    priority: 74,
    genre: 'Business, Lifestyle, Entertainment',
    credits: 'Hollywood Exes (VH1, 2 seasons). Entrepreneur.',
    igHandle: '@kenyaduke',
    igUrl: 'https://instagram.com/kenyaduke',
    ttHandle: '@kenyaduke',
    ttUrl: 'https://tiktok.com/@kenyaduke',
    igFollowers: '200K',
    ttFollowers: '50K',
    totalFollowing: '250K+',
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&h=750&fit=crop&crop=face&q=80',
    bio: 'Entrepreneur and star of Hollywood Exes on VH1. Business owner and lifestyle content creator.',
    status: 'invited',
    email: '',
    phone: '',
    categories: ['Business', 'Lifestyle', 'Entertainment'],
    networks: ['VH1'],
  },
]

export function getTalentBySlug(slug: string): TalentProfile | undefined {
  return talent.find((t) => t.slug === slug)
}

export function getTalentByInviteSlug(inviteSlug: string): TalentProfile | undefined {
  return talent.find((t) => t.inviteSlug === inviteSlug)
}
